// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module cnn_accel_cnn_accel_Pipeline_pool2_loop_VITIS_LOOP_124_1_VITIS_LOOP_125_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        cnn_accel_ap_int_8_const_ap_uint_4_pool2_address0,
        cnn_accel_ap_int_8_const_ap_uint_4_pool2_ce0,
        cnn_accel_ap_int_8_const_ap_uint_4_pool2_we0,
        cnn_accel_ap_int_8_const_ap_uint_4_pool2_d0,
        cnn_accel_ap_int_8_const_ap_uint_4_conv2_address0,
        cnn_accel_ap_int_8_const_ap_uint_4_conv2_ce0,
        cnn_accel_ap_int_8_const_ap_uint_4_conv2_q0,
        cnn_accel_ap_int_8_const_ap_uint_4_conv2_address1,
        cnn_accel_ap_int_8_const_ap_uint_4_conv2_ce1,
        cnn_accel_ap_int_8_const_ap_uint_4_conv2_q1,
        cnn_accel_ap_int_8_const_ap_uint_4_conv2_57_address0,
        cnn_accel_ap_int_8_const_ap_uint_4_conv2_57_ce0,
        cnn_accel_ap_int_8_const_ap_uint_4_conv2_57_q0,
        cnn_accel_ap_int_8_const_ap_uint_4_conv2_57_address1,
        cnn_accel_ap_int_8_const_ap_uint_4_conv2_57_ce1,
        cnn_accel_ap_int_8_const_ap_uint_4_conv2_57_q1,
        cnn_accel_ap_int_8_const_ap_uint_4_pool2_58_address0,
        cnn_accel_ap_int_8_const_ap_uint_4_pool2_58_ce0,
        cnn_accel_ap_int_8_const_ap_uint_4_pool2_58_we0,
        cnn_accel_ap_int_8_const_ap_uint_4_pool2_58_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [8:0] cnn_accel_ap_int_8_const_ap_uint_4_pool2_address0;
output   cnn_accel_ap_int_8_const_ap_uint_4_pool2_ce0;
output   cnn_accel_ap_int_8_const_ap_uint_4_pool2_we0;
output  [7:0] cnn_accel_ap_int_8_const_ap_uint_4_pool2_d0;
output  [10:0] cnn_accel_ap_int_8_const_ap_uint_4_conv2_address0;
output   cnn_accel_ap_int_8_const_ap_uint_4_conv2_ce0;
input  [7:0] cnn_accel_ap_int_8_const_ap_uint_4_conv2_q0;
output  [10:0] cnn_accel_ap_int_8_const_ap_uint_4_conv2_address1;
output   cnn_accel_ap_int_8_const_ap_uint_4_conv2_ce1;
input  [7:0] cnn_accel_ap_int_8_const_ap_uint_4_conv2_q1;
output  [10:0] cnn_accel_ap_int_8_const_ap_uint_4_conv2_57_address0;
output   cnn_accel_ap_int_8_const_ap_uint_4_conv2_57_ce0;
input  [7:0] cnn_accel_ap_int_8_const_ap_uint_4_conv2_57_q0;
output  [10:0] cnn_accel_ap_int_8_const_ap_uint_4_conv2_57_address1;
output   cnn_accel_ap_int_8_const_ap_uint_4_conv2_57_ce1;
input  [7:0] cnn_accel_ap_int_8_const_ap_uint_4_conv2_57_q1;
output  [8:0] cnn_accel_ap_int_8_const_ap_uint_4_pool2_58_address0;
output   cnn_accel_ap_int_8_const_ap_uint_4_pool2_58_ce0;
output   cnn_accel_ap_int_8_const_ap_uint_4_pool2_58_we0;
output  [7:0] cnn_accel_ap_int_8_const_ap_uint_4_pool2_58_d0;

reg ap_idle;
reg cnn_accel_ap_int_8_const_ap_uint_4_pool2_ce0;
reg cnn_accel_ap_int_8_const_ap_uint_4_pool2_we0;
reg cnn_accel_ap_int_8_const_ap_uint_4_conv2_ce0;
reg cnn_accel_ap_int_8_const_ap_uint_4_conv2_ce1;
reg cnn_accel_ap_int_8_const_ap_uint_4_conv2_57_ce0;
reg cnn_accel_ap_int_8_const_ap_uint_4_conv2_57_ce1;
reg cnn_accel_ap_int_8_const_ap_uint_4_pool2_58_ce0;
reg cnn_accel_ap_int_8_const_ap_uint_4_pool2_58_we0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln123_fu_201_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire   [2:0] select_ln124_fu_306_p3;
reg   [2:0] select_ln124_reg_547;
wire   [9:0] add_ln127_fu_326_p2;
reg   [9:0] add_ln127_reg_552;
wire   [6:0] trunc_ln127_fu_332_p1;
reg   [6:0] trunc_ln127_reg_557;
reg   [6:0] trunc_ln127_reg_557_pp0_iter1_reg;
reg   [6:0] trunc_ln127_reg_557_pp0_iter2_reg;
reg   [6:0] trunc_ln127_reg_557_pp0_iter3_reg;
reg   [1:0] lshr_ln_reg_563;
reg   [1:0] lshr_ln_reg_563_pp0_iter1_reg;
reg   [1:0] lshr_ln_reg_563_pp0_iter2_reg;
reg   [1:0] lshr_ln_reg_563_pp0_iter3_reg;
wire   [0:0] trunc_ln134_fu_346_p1;
reg   [0:0] trunc_ln134_reg_568;
reg   [0:0] trunc_ln134_reg_568_pp0_iter1_reg;
reg   [0:0] trunc_ln134_reg_568_pp0_iter2_reg;
reg   [0:0] trunc_ln134_reg_568_pp0_iter3_reg;
wire   [63:0] zext_ln127_4_fu_432_p1;
reg   [63:0] zext_ln127_4_reg_572;
wire   [63:0] zext_ln128_1_fu_453_p1;
reg   [63:0] zext_ln128_1_reg_582;
wire   [7:0] m_V_1_fu_464_p3;
reg   [7:0] m_V_1_reg_602;
reg   [7:0] v3_V_reg_608;
wire   [7:0] m_V_3_fu_477_p3;
reg   [7:0] m_V_3_reg_614;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln134_fu_502_p1;
reg   [2:0] x_fu_74;
wire   [2:0] add_ln125_fu_350_p2;
wire    ap_loop_init;
reg   [2:0] ap_sig_allocacmp_x_load;
reg   [2:0] y_fu_78;
wire   [2:0] select_ln124_1_fu_314_p3;
reg   [2:0] ap_sig_allocacmp_y_load;
reg   [5:0] indvar_flatten28_fu_82;
wire   [5:0] select_ln124_2_fu_362_p3;
reg   [5:0] ap_sig_allocacmp_indvar_flatten28_load;
reg   [4:0] c_fu_86;
wire   [4:0] select_ln123_1_fu_242_p3;
reg   [4:0] ap_sig_allocacmp_c_load;
reg   [9:0] indvar_flatten42_fu_90;
wire   [9:0] add_ln123_1_fu_207_p2;
reg   [9:0] ap_sig_allocacmp_indvar_flatten42_load;
wire   [7:0] m_V_4_fu_488_p3;
wire   [0:0] icmp_ln124_fu_228_p2;
wire   [4:0] add_ln123_fu_222_p2;
wire   [7:0] tmp_s_fu_254_p3;
wire   [8:0] zext_ln127_1_fu_262_p1;
wire   [8:0] zext_ln127_fu_250_p1;
wire   [8:0] sub_ln127_fu_266_p2;
wire   [0:0] icmp_ln125_fu_282_p2;
wire   [0:0] xor_ln123_fu_276_p2;
wire   [2:0] select_ln123_fu_234_p3;
wire   [0:0] and_ln123_fu_288_p2;
wire   [0:0] or_ln124_fu_300_p2;
wire   [2:0] add_ln124_fu_294_p2;
wire  signed [9:0] sext_ln124_fu_272_p1;
wire   [9:0] zext_ln127_2_fu_322_p1;
wire   [5:0] add_ln124_1_fu_356_p2;
wire   [10:0] p_shl8_fu_395_p3;
wire   [10:0] p_shl9_fu_402_p3;
wire   [3:0] shl_ln1_fu_415_p3;
wire   [10:0] sub_ln127_1_fu_409_p2;
wire   [10:0] zext_ln127_3_fu_422_p1;
wire   [10:0] add_ln127_1_fu_426_p2;
wire   [3:0] or_ln128_fu_437_p2;
wire   [10:0] zext_ln128_fu_443_p1;
wire   [10:0] add_ln128_fu_447_p2;
wire   [0:0] icmp_ln1035_fu_458_p2;
wire   [0:0] icmp_ln1035_1_fu_472_p2;
wire   [0:0] icmp_ln1035_2_fu_484_p2;
wire   [8:0] tmp_371_fu_496_p3;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_done_reg = 1'b0;
end

cnn_accel_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln123_fu_201_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            c_fu_86 <= select_ln123_1_fu_242_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            c_fu_86 <= 5'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln123_fu_201_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten28_fu_82 <= select_ln124_2_fu_362_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten28_fu_82 <= 6'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln123_fu_201_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten42_fu_90 <= add_ln123_1_fu_207_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten42_fu_90 <= 10'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln123_fu_201_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            x_fu_74 <= add_ln125_fu_350_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            x_fu_74 <= 3'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln123_fu_201_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            y_fu_78 <= select_ln124_1_fu_314_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            y_fu_78 <= 3'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln123_fu_201_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln127_reg_552 <= add_ln127_fu_326_p2;
        lshr_ln_reg_563 <= {{select_ln124_fu_306_p3[2:1]}};
        select_ln124_reg_547 <= select_ln124_fu_306_p3;
        trunc_ln127_reg_557 <= trunc_ln127_fu_332_p1;
        trunc_ln134_reg_568 <= trunc_ln134_fu_346_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        lshr_ln_reg_563_pp0_iter1_reg <= lshr_ln_reg_563;
        trunc_ln127_reg_557_pp0_iter1_reg <= trunc_ln127_reg_557;
        trunc_ln134_reg_568_pp0_iter1_reg <= trunc_ln134_reg_568;
        zext_ln127_4_reg_572[10 : 1] <= zext_ln127_4_fu_432_p1[10 : 1];
        zext_ln128_1_reg_582[10 : 1] <= zext_ln128_1_fu_453_p1[10 : 1];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        lshr_ln_reg_563_pp0_iter2_reg <= lshr_ln_reg_563_pp0_iter1_reg;
        lshr_ln_reg_563_pp0_iter3_reg <= lshr_ln_reg_563_pp0_iter2_reg;
        m_V_1_reg_602 <= m_V_1_fu_464_p3;
        m_V_3_reg_614 <= m_V_3_fu_477_p3;
        trunc_ln127_reg_557_pp0_iter2_reg <= trunc_ln127_reg_557_pp0_iter1_reg;
        trunc_ln127_reg_557_pp0_iter3_reg <= trunc_ln127_reg_557_pp0_iter2_reg;
        trunc_ln134_reg_568_pp0_iter2_reg <= trunc_ln134_reg_568_pp0_iter1_reg;
        trunc_ln134_reg_568_pp0_iter3_reg <= trunc_ln134_reg_568_pp0_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        v3_V_reg_608 <= cnn_accel_ap_int_8_const_ap_uint_4_conv2_57_q0;
    end
end

always @ (*) begin
    if (((icmp_ln123_fu_201_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_c_load = 5'd0;
    end else begin
        ap_sig_allocacmp_c_load = c_fu_86;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten28_load = 6'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten28_load = indvar_flatten28_fu_82;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten42_load = 10'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten42_load = indvar_flatten42_fu_90;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_x_load = 3'd0;
    end else begin
        ap_sig_allocacmp_x_load = x_fu_74;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_y_load = 3'd0;
    end else begin
        ap_sig_allocacmp_y_load = y_fu_78;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        cnn_accel_ap_int_8_const_ap_uint_4_conv2_57_ce0 = 1'b1;
    end else begin
        cnn_accel_ap_int_8_const_ap_uint_4_conv2_57_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        cnn_accel_ap_int_8_const_ap_uint_4_conv2_57_ce1 = 1'b1;
    end else begin
        cnn_accel_ap_int_8_const_ap_uint_4_conv2_57_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        cnn_accel_ap_int_8_const_ap_uint_4_conv2_ce0 = 1'b1;
    end else begin
        cnn_accel_ap_int_8_const_ap_uint_4_conv2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        cnn_accel_ap_int_8_const_ap_uint_4_conv2_ce1 = 1'b1;
    end else begin
        cnn_accel_ap_int_8_const_ap_uint_4_conv2_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        cnn_accel_ap_int_8_const_ap_uint_4_pool2_58_ce0 = 1'b1;
    end else begin
        cnn_accel_ap_int_8_const_ap_uint_4_pool2_58_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (trunc_ln134_reg_568_pp0_iter3_reg == 1'd1))) begin
        cnn_accel_ap_int_8_const_ap_uint_4_pool2_58_we0 = 1'b1;
    end else begin
        cnn_accel_ap_int_8_const_ap_uint_4_pool2_58_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        cnn_accel_ap_int_8_const_ap_uint_4_pool2_ce0 = 1'b1;
    end else begin
        cnn_accel_ap_int_8_const_ap_uint_4_pool2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (trunc_ln134_reg_568_pp0_iter3_reg == 1'd0))) begin
        cnn_accel_ap_int_8_const_ap_uint_4_pool2_we0 = 1'b1;
    end else begin
        cnn_accel_ap_int_8_const_ap_uint_4_pool2_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln123_1_fu_207_p2 = (ap_sig_allocacmp_indvar_flatten42_load + 10'd1);

assign add_ln123_fu_222_p2 = (ap_sig_allocacmp_c_load + 5'd1);

assign add_ln124_1_fu_356_p2 = (ap_sig_allocacmp_indvar_flatten28_load + 6'd1);

assign add_ln124_fu_294_p2 = (select_ln123_fu_234_p3 + 3'd1);

assign add_ln125_fu_350_p2 = (select_ln124_fu_306_p3 + 3'd1);

assign add_ln127_1_fu_426_p2 = (sub_ln127_1_fu_409_p2 + zext_ln127_3_fu_422_p1);

assign add_ln127_fu_326_p2 = ($signed(sext_ln124_fu_272_p1) + $signed(zext_ln127_2_fu_322_p1));

assign add_ln128_fu_447_p2 = (sub_ln127_1_fu_409_p2 + zext_ln128_fu_443_p1);

assign and_ln123_fu_288_p2 = (xor_ln123_fu_276_p2 & icmp_ln125_fu_282_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign cnn_accel_ap_int_8_const_ap_uint_4_conv2_57_address0 = zext_ln128_1_reg_582;

assign cnn_accel_ap_int_8_const_ap_uint_4_conv2_57_address1 = zext_ln127_4_reg_572;

assign cnn_accel_ap_int_8_const_ap_uint_4_conv2_address0 = zext_ln128_1_fu_453_p1;

assign cnn_accel_ap_int_8_const_ap_uint_4_conv2_address1 = zext_ln127_4_fu_432_p1;

assign cnn_accel_ap_int_8_const_ap_uint_4_pool2_58_address0 = zext_ln134_fu_502_p1;

assign cnn_accel_ap_int_8_const_ap_uint_4_pool2_58_d0 = m_V_4_fu_488_p3;

assign cnn_accel_ap_int_8_const_ap_uint_4_pool2_address0 = zext_ln134_fu_502_p1;

assign cnn_accel_ap_int_8_const_ap_uint_4_pool2_d0 = m_V_4_fu_488_p3;

assign icmp_ln1035_1_fu_472_p2 = (($signed(cnn_accel_ap_int_8_const_ap_uint_4_conv2_57_q1) > $signed(m_V_1_reg_602)) ? 1'b1 : 1'b0);

assign icmp_ln1035_2_fu_484_p2 = (($signed(v3_V_reg_608) > $signed(m_V_3_reg_614)) ? 1'b1 : 1'b0);

assign icmp_ln1035_fu_458_p2 = (($signed(cnn_accel_ap_int_8_const_ap_uint_4_conv2_q0) > $signed(cnn_accel_ap_int_8_const_ap_uint_4_conv2_q1)) ? 1'b1 : 1'b0);

assign icmp_ln123_fu_201_p2 = ((ap_sig_allocacmp_indvar_flatten42_load == 10'd784) ? 1'b1 : 1'b0);

assign icmp_ln124_fu_228_p2 = ((ap_sig_allocacmp_indvar_flatten28_load == 6'd49) ? 1'b1 : 1'b0);

assign icmp_ln125_fu_282_p2 = ((ap_sig_allocacmp_x_load == 3'd7) ? 1'b1 : 1'b0);

assign m_V_1_fu_464_p3 = ((icmp_ln1035_fu_458_p2[0:0] == 1'b1) ? cnn_accel_ap_int_8_const_ap_uint_4_conv2_q0 : cnn_accel_ap_int_8_const_ap_uint_4_conv2_q1);

assign m_V_3_fu_477_p3 = ((icmp_ln1035_1_fu_472_p2[0:0] == 1'b1) ? cnn_accel_ap_int_8_const_ap_uint_4_conv2_57_q1 : m_V_1_reg_602);

assign m_V_4_fu_488_p3 = ((icmp_ln1035_2_fu_484_p2[0:0] == 1'b1) ? v3_V_reg_608 : m_V_3_reg_614);

assign or_ln124_fu_300_p2 = (icmp_ln124_fu_228_p2 | and_ln123_fu_288_p2);

assign or_ln128_fu_437_p2 = (shl_ln1_fu_415_p3 | 4'd1);

assign p_shl8_fu_395_p3 = {{trunc_ln127_reg_557}, {4'd0}};

assign p_shl9_fu_402_p3 = {{add_ln127_reg_552}, {1'd0}};

assign select_ln123_1_fu_242_p3 = ((icmp_ln124_fu_228_p2[0:0] == 1'b1) ? add_ln123_fu_222_p2 : ap_sig_allocacmp_c_load);

assign select_ln123_fu_234_p3 = ((icmp_ln124_fu_228_p2[0:0] == 1'b1) ? 3'd0 : ap_sig_allocacmp_y_load);

assign select_ln124_1_fu_314_p3 = ((and_ln123_fu_288_p2[0:0] == 1'b1) ? add_ln124_fu_294_p2 : select_ln123_fu_234_p3);

assign select_ln124_2_fu_362_p3 = ((icmp_ln124_fu_228_p2[0:0] == 1'b1) ? 6'd1 : add_ln124_1_fu_356_p2);

assign select_ln124_fu_306_p3 = ((or_ln124_fu_300_p2[0:0] == 1'b1) ? 3'd0 : ap_sig_allocacmp_x_load);

assign sext_ln124_fu_272_p1 = $signed(sub_ln127_fu_266_p2);

assign shl_ln1_fu_415_p3 = {{select_ln124_reg_547}, {1'd0}};

assign sub_ln127_1_fu_409_p2 = (p_shl8_fu_395_p3 - p_shl9_fu_402_p3);

assign sub_ln127_fu_266_p2 = (zext_ln127_1_fu_262_p1 - zext_ln127_fu_250_p1);

assign tmp_371_fu_496_p3 = {{trunc_ln127_reg_557_pp0_iter3_reg}, {lshr_ln_reg_563_pp0_iter3_reg}};

assign tmp_s_fu_254_p3 = {{select_ln123_1_fu_242_p3}, {3'd0}};

assign trunc_ln127_fu_332_p1 = add_ln127_fu_326_p2[6:0];

assign trunc_ln134_fu_346_p1 = select_ln124_fu_306_p3[0:0];

assign xor_ln123_fu_276_p2 = (icmp_ln124_fu_228_p2 ^ 1'd1);

assign zext_ln127_1_fu_262_p1 = tmp_s_fu_254_p3;

assign zext_ln127_2_fu_322_p1 = select_ln124_1_fu_314_p3;

assign zext_ln127_3_fu_422_p1 = shl_ln1_fu_415_p3;

assign zext_ln127_4_fu_432_p1 = add_ln127_1_fu_426_p2;

assign zext_ln127_fu_250_p1 = select_ln123_1_fu_242_p3;

assign zext_ln128_1_fu_453_p1 = add_ln128_fu_447_p2;

assign zext_ln128_fu_443_p1 = or_ln128_fu_437_p2;

assign zext_ln134_fu_502_p1 = tmp_371_fu_496_p3;

always @ (posedge ap_clk) begin
    zext_ln127_4_reg_572[0] <= 1'b0;
    zext_ln127_4_reg_572[63:11] <= 53'b00000000000000000000000000000000000000000000000000000;
    zext_ln128_1_reg_582[0] <= 1'b1;
    zext_ln128_1_reg_582[63:11] <= 53'b00000000000000000000000000000000000000000000000000000;
end

endmodule //cnn_accel_cnn_accel_Pipeline_pool2_loop_VITIS_LOOP_124_1_VITIS_LOOP_125_2
