// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module cnn_accel_cnn_accel_Pipeline_VITIS_LOOP_172_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        sext_ln171,
        zext_ln170,
        zext_ln186,
        cnn_accel_ap_int_8_const_ap_uint_4_fc1_load,
        cnn_accel_ap_int_8_const_ap_uint_4_fc1_59_load,
        cnn_accel_ap_int_8_const_ap_uint_4_fc1_60_load,
        cnn_accel_ap_int_8_const_ap_uint_4_fc1_61_load,
        cnn_accel_ap_int_8_const_ap_uint_4_fc1_62_load,
        cnn_accel_ap_int_8_const_ap_uint_4_fc1_63_load,
        cnn_accel_ap_int_8_const_ap_uint_4_fc1_64_load,
        cnn_accel_ap_int_8_const_ap_uint_4_fc1_65_load,
        cnn_accel_ap_int_8_const_ap_uint_4_fc1_66_load,
        cnn_accel_ap_int_8_const_ap_uint_4_fc1_67_load,
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_10_load,
        cnn_accel_ap_int_8_const_ap_uint_4_fc1_330,
        cnn_accel_ap_int_8_const_ap_uint_4_fc1_331,
        cnn_accel_ap_int_8_const_ap_uint_4_fc1_332,
        cnn_accel_ap_int_8_const_ap_uint_4_fc1_333,
        cnn_accel_ap_int_8_const_ap_uint_4_fc1_334,
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_16_load,
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_17_load,
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_18_load,
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_19_load,
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_20_load,
        cnn_accel_ap_int_8_const_ap_uint_4_fc1_335,
        cnn_accel_ap_int_8_const_ap_uint_4_fc1_336,
        cnn_accel_ap_int_8_const_ap_uint_4_fc1_337,
        cnn_accel_ap_int_8_const_ap_uint_4_fc1_338,
        cnn_accel_ap_int_8_const_ap_uint_4_fc1_339,
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_26_load,
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_27_load,
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_28_load,
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_29_load,
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_30_load,
        cnn_accel_ap_int_8_const_ap_uint_4_fc1,
        logits_V_address0,
        logits_V_ce0,
        logits_V_we0,
        logits_V_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [8:0] sext_ln171;
input  [3:0] zext_ln170;
input  [8:0] zext_ln186;
input  [7:0] cnn_accel_ap_int_8_const_ap_uint_4_fc1_load;
input  [7:0] cnn_accel_ap_int_8_const_ap_uint_4_fc1_59_load;
input  [7:0] cnn_accel_ap_int_8_const_ap_uint_4_fc1_60_load;
input  [7:0] cnn_accel_ap_int_8_const_ap_uint_4_fc1_61_load;
input  [7:0] cnn_accel_ap_int_8_const_ap_uint_4_fc1_62_load;
input  [7:0] cnn_accel_ap_int_8_const_ap_uint_4_fc1_63_load;
input  [7:0] cnn_accel_ap_int_8_const_ap_uint_4_fc1_64_load;
input  [7:0] cnn_accel_ap_int_8_const_ap_uint_4_fc1_65_load;
input  [7:0] cnn_accel_ap_int_8_const_ap_uint_4_fc1_66_load;
input  [7:0] cnn_accel_ap_int_8_const_ap_uint_4_fc1_67_load;
input  [7:0] p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_10_load;
input  [7:0] cnn_accel_ap_int_8_const_ap_uint_4_fc1_330;
input  [7:0] cnn_accel_ap_int_8_const_ap_uint_4_fc1_331;
input  [7:0] cnn_accel_ap_int_8_const_ap_uint_4_fc1_332;
input  [7:0] cnn_accel_ap_int_8_const_ap_uint_4_fc1_333;
input  [7:0] cnn_accel_ap_int_8_const_ap_uint_4_fc1_334;
input  [7:0] p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_16_load;
input  [7:0] p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_17_load;
input  [7:0] p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_18_load;
input  [7:0] p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_19_load;
input  [7:0] p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_20_load;
input  [7:0] cnn_accel_ap_int_8_const_ap_uint_4_fc1_335;
input  [7:0] cnn_accel_ap_int_8_const_ap_uint_4_fc1_336;
input  [7:0] cnn_accel_ap_int_8_const_ap_uint_4_fc1_337;
input  [7:0] cnn_accel_ap_int_8_const_ap_uint_4_fc1_338;
input  [7:0] cnn_accel_ap_int_8_const_ap_uint_4_fc1_339;
input  [7:0] p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_26_load;
input  [7:0] p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_27_load;
input  [7:0] p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_28_load;
input  [7:0] p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_29_load;
input  [7:0] p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_30_load;
input  [7:0] cnn_accel_ap_int_8_const_ap_uint_4_fc1;
output  [3:0] logits_V_address0;
output   logits_V_ce0;
output   logits_V_we0;
output  [19:0] logits_V_d0;

reg ap_idle;
reg logits_V_ce0;
reg logits_V_we0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln172_fu_371_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [8:0] W_FC2_V_address0;
reg    W_FC2_V_ce0;
wire  signed [7:0] W_FC2_V_q0;
wire    ap_block_pp0_stage0_11001;
reg   [3:0] logits_V_addr_reg_521;
reg   [3:0] logits_V_addr_reg_521_pp0_iter1_reg;
reg   [3:0] logits_V_addr_reg_521_pp0_iter2_reg;
reg   [3:0] logits_V_addr_reg_521_pp0_iter3_reg;
wire   [7:0] tmp_fu_402_p34;
reg  signed [7:0] tmp_reg_535;
wire   [0:0] icmp_ln172_1_fu_472_p2;
reg   [0:0] icmp_ln172_1_reg_540;
reg   [0:0] icmp_ln172_1_reg_540_pp0_iter1_reg;
reg   [0:0] icmp_ln172_1_reg_540_pp0_iter2_reg;
reg   [0:0] icmp_ln172_1_reg_540_pp0_iter3_reg;
wire   [63:0] zext_ln170_cast_fu_349_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln186_8_fu_393_p1;
reg   [19:0] score_V_fu_106;
wire  signed [19:0] grp_fu_497_p3;
wire  signed [19:0] sext_ln171_cast_fu_354_p1;
reg  signed [19:0] ap_sig_allocacmp_score_V_load;
wire    ap_loop_init;
reg   [5:0] i_fu_110;
wire   [5:0] add_ln172_fu_377_p2;
reg   [5:0] ap_sig_allocacmp_i_1;
wire   [8:0] zext_ln186_7_fu_383_p1;
wire   [8:0] add_ln186_fu_387_p2;
wire   [4:0] tmp_fu_402_p33;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_done_reg = 1'b0;
end

cnn_accel_cnn_accel_Pipeline_VITIS_LOOP_172_1_W_FC2_V_ROM_AUTO_1R #(
    .DataWidth( 8 ),
    .AddressRange( 320 ),
    .AddressWidth( 9 ))
W_FC2_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(W_FC2_V_address0),
    .ce0(W_FC2_V_ce0),
    .q0(W_FC2_V_q0)
);

cnn_accel_mux_325_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 8 ),
    .din5_WIDTH( 8 ),
    .din6_WIDTH( 8 ),
    .din7_WIDTH( 8 ),
    .din8_WIDTH( 8 ),
    .din9_WIDTH( 8 ),
    .din10_WIDTH( 8 ),
    .din11_WIDTH( 8 ),
    .din12_WIDTH( 8 ),
    .din13_WIDTH( 8 ),
    .din14_WIDTH( 8 ),
    .din15_WIDTH( 8 ),
    .din16_WIDTH( 8 ),
    .din17_WIDTH( 8 ),
    .din18_WIDTH( 8 ),
    .din19_WIDTH( 8 ),
    .din20_WIDTH( 8 ),
    .din21_WIDTH( 8 ),
    .din22_WIDTH( 8 ),
    .din23_WIDTH( 8 ),
    .din24_WIDTH( 8 ),
    .din25_WIDTH( 8 ),
    .din26_WIDTH( 8 ),
    .din27_WIDTH( 8 ),
    .din28_WIDTH( 8 ),
    .din29_WIDTH( 8 ),
    .din30_WIDTH( 8 ),
    .din31_WIDTH( 8 ),
    .din32_WIDTH( 5 ),
    .dout_WIDTH( 8 ))
mux_325_8_1_1_U2035(
    .din0(cnn_accel_ap_int_8_const_ap_uint_4_fc1_load),
    .din1(cnn_accel_ap_int_8_const_ap_uint_4_fc1_59_load),
    .din2(cnn_accel_ap_int_8_const_ap_uint_4_fc1_60_load),
    .din3(cnn_accel_ap_int_8_const_ap_uint_4_fc1_61_load),
    .din4(cnn_accel_ap_int_8_const_ap_uint_4_fc1_62_load),
    .din5(cnn_accel_ap_int_8_const_ap_uint_4_fc1_63_load),
    .din6(cnn_accel_ap_int_8_const_ap_uint_4_fc1_64_load),
    .din7(cnn_accel_ap_int_8_const_ap_uint_4_fc1_65_load),
    .din8(cnn_accel_ap_int_8_const_ap_uint_4_fc1_66_load),
    .din9(cnn_accel_ap_int_8_const_ap_uint_4_fc1_67_load),
    .din10(p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_10_load),
    .din11(cnn_accel_ap_int_8_const_ap_uint_4_fc1_330),
    .din12(cnn_accel_ap_int_8_const_ap_uint_4_fc1_331),
    .din13(cnn_accel_ap_int_8_const_ap_uint_4_fc1_332),
    .din14(cnn_accel_ap_int_8_const_ap_uint_4_fc1_333),
    .din15(cnn_accel_ap_int_8_const_ap_uint_4_fc1_334),
    .din16(p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_16_load),
    .din17(p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_17_load),
    .din18(p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_18_load),
    .din19(p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_19_load),
    .din20(p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_20_load),
    .din21(cnn_accel_ap_int_8_const_ap_uint_4_fc1_335),
    .din22(cnn_accel_ap_int_8_const_ap_uint_4_fc1_336),
    .din23(cnn_accel_ap_int_8_const_ap_uint_4_fc1_337),
    .din24(cnn_accel_ap_int_8_const_ap_uint_4_fc1_338),
    .din25(cnn_accel_ap_int_8_const_ap_uint_4_fc1_339),
    .din26(p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_26_load),
    .din27(p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_27_load),
    .din28(p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_28_load),
    .din29(p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_29_load),
    .din30(p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_30_load),
    .din31(cnn_accel_ap_int_8_const_ap_uint_4_fc1),
    .din32(tmp_fu_402_p33),
    .dout(tmp_fu_402_p34)
);

cnn_accel_mac_muladd_8s_8s_20s_20_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 20 ),
    .dout_WIDTH( 20 ))
mac_muladd_8s_8s_20s_20_4_1_U2036(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(W_FC2_V_q0),
    .din1(tmp_reg_535),
    .din2(ap_sig_allocacmp_score_V_load),
    .ce(1'b1),
    .dout(grp_fu_497_p3)
);

cnn_accel_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln172_fu_371_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_fu_110 <= add_ln172_fu_377_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_110 <= 6'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            score_V_fu_106 <= sext_ln171_cast_fu_354_p1;
        end else if ((ap_enable_reg_pp0_iter4 == 1'b1)) begin
            score_V_fu_106 <= grp_fu_497_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        icmp_ln172_1_reg_540_pp0_iter1_reg <= icmp_ln172_1_reg_540;
        logits_V_addr_reg_521 <= zext_ln170_cast_fu_349_p1;
        logits_V_addr_reg_521_pp0_iter1_reg <= logits_V_addr_reg_521;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        icmp_ln172_1_reg_540_pp0_iter2_reg <= icmp_ln172_1_reg_540_pp0_iter1_reg;
        icmp_ln172_1_reg_540_pp0_iter3_reg <= icmp_ln172_1_reg_540_pp0_iter2_reg;
        logits_V_addr_reg_521_pp0_iter2_reg <= logits_V_addr_reg_521_pp0_iter1_reg;
        logits_V_addr_reg_521_pp0_iter3_reg <= logits_V_addr_reg_521_pp0_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln172_fu_371_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln172_1_reg_540 <= icmp_ln172_1_fu_472_p2;
        tmp_reg_535 <= tmp_fu_402_p34;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        W_FC2_V_ce0 = 1'b1;
    end else begin
        W_FC2_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln172_fu_371_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_1 = 6'd0;
    end else begin
        ap_sig_allocacmp_i_1 = i_fu_110;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        ap_sig_allocacmp_score_V_load = grp_fu_497_p3;
    end else begin
        ap_sig_allocacmp_score_V_load = score_V_fu_106;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        logits_V_ce0 = 1'b1;
    end else begin
        logits_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (icmp_ln172_1_reg_540_pp0_iter3_reg == 1'd1))) begin
        logits_V_we0 = 1'b1;
    end else begin
        logits_V_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign W_FC2_V_address0 = zext_ln186_8_fu_393_p1;

assign add_ln172_fu_377_p2 = (ap_sig_allocacmp_i_1 + 6'd1);

assign add_ln186_fu_387_p2 = (zext_ln186 + zext_ln186_7_fu_383_p1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign icmp_ln172_1_fu_472_p2 = ((add_ln172_fu_377_p2 == 6'd32) ? 1'b1 : 1'b0);

assign icmp_ln172_fu_371_p2 = ((ap_sig_allocacmp_i_1 == 6'd32) ? 1'b1 : 1'b0);

assign logits_V_address0 = logits_V_addr_reg_521_pp0_iter3_reg;

assign logits_V_d0 = grp_fu_497_p3;

assign sext_ln171_cast_fu_354_p1 = $signed(sext_ln171);

assign tmp_fu_402_p33 = ap_sig_allocacmp_i_1[4:0];

assign zext_ln170_cast_fu_349_p1 = zext_ln170;

assign zext_ln186_7_fu_383_p1 = ap_sig_allocacmp_i_1;

assign zext_ln186_8_fu_393_p1 = add_ln186_fu_387_p2;

endmodule //cnn_accel_cnn_accel_Pipeline_VITIS_LOOP_172_1
