// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module cnn_accel_fc1_layer_Pipeline_VITIS_LOOP_151_1_VITIS_LOOP_152_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        sext_ln150,
        phi_mul,
        acc_V_2_out,
        acc_V_2_out_ap_vld,
        cnn_accel_ap_int_8_const_ap_uint_4_pool2_address0,
        cnn_accel_ap_int_8_const_ap_uint_4_pool2_ce0,
        cnn_accel_ap_int_8_const_ap_uint_4_pool2_q0,
        cnn_accel_ap_int_8_const_ap_uint_4_pool2_address1,
        cnn_accel_ap_int_8_const_ap_uint_4_pool2_ce1,
        cnn_accel_ap_int_8_const_ap_uint_4_pool2_q1,
        cnn_accel_ap_int_8_const_ap_uint_4_pool2_58_address0,
        cnn_accel_ap_int_8_const_ap_uint_4_pool2_58_ce0,
        cnn_accel_ap_int_8_const_ap_uint_4_pool2_58_q0,
        cnn_accel_ap_int_8_const_ap_uint_4_pool2_58_address1,
        cnn_accel_ap_int_8_const_ap_uint_4_pool2_58_ce1,
        cnn_accel_ap_int_8_const_ap_uint_4_pool2_58_q1
);

parameter    ap_ST_fsm_pp0_stage0 = 2'd1;
parameter    ap_ST_fsm_pp0_stage1 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [8:0] sext_ln150;
input  [13:0] phi_mul;
output  [24:0] acc_V_2_out;
output   acc_V_2_out_ap_vld;
output  [8:0] cnn_accel_ap_int_8_const_ap_uint_4_pool2_address0;
output   cnn_accel_ap_int_8_const_ap_uint_4_pool2_ce0;
input  [7:0] cnn_accel_ap_int_8_const_ap_uint_4_pool2_q0;
output  [8:0] cnn_accel_ap_int_8_const_ap_uint_4_pool2_address1;
output   cnn_accel_ap_int_8_const_ap_uint_4_pool2_ce1;
input  [7:0] cnn_accel_ap_int_8_const_ap_uint_4_pool2_q1;
output  [8:0] cnn_accel_ap_int_8_const_ap_uint_4_pool2_58_address0;
output   cnn_accel_ap_int_8_const_ap_uint_4_pool2_58_ce0;
input  [7:0] cnn_accel_ap_int_8_const_ap_uint_4_pool2_58_q0;
output  [8:0] cnn_accel_ap_int_8_const_ap_uint_4_pool2_58_address1;
output   cnn_accel_ap_int_8_const_ap_uint_4_pool2_58_ce1;
input  [7:0] cnn_accel_ap_int_8_const_ap_uint_4_pool2_58_q1;

reg ap_idle;
reg acc_V_2_out_ap_vld;
reg[8:0] cnn_accel_ap_int_8_const_ap_uint_4_pool2_address0;
reg cnn_accel_ap_int_8_const_ap_uint_4_pool2_ce0;
reg[8:0] cnn_accel_ap_int_8_const_ap_uint_4_pool2_address1;
reg cnn_accel_ap_int_8_const_ap_uint_4_pool2_ce1;
reg[8:0] cnn_accel_ap_int_8_const_ap_uint_4_pool2_58_address0;
reg cnn_accel_ap_int_8_const_ap_uint_4_pool2_58_ce0;
reg cnn_accel_ap_int_8_const_ap_uint_4_pool2_58_ce1;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_state2_pp0_stage1_iter0;
wire    ap_block_state4_pp0_stage1_iter1;
wire    ap_block_state6_pp0_stage1_iter2;
wire    ap_block_state8_pp0_stage1_iter3;
wire    ap_block_state10_pp0_stage1_iter4;
wire    ap_block_pp0_stage1_subdone;
reg   [0:0] icmp_ln151_reg_967;
reg    ap_condition_exit_pp0_iter0_stage1;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg   [13:0] p_ZL5W_FC1_0_address0;
reg    p_ZL5W_FC1_0_ce0;
wire   [7:0] p_ZL5W_FC1_0_q0;
reg   [13:0] p_ZL5W_FC1_0_address1;
reg    p_ZL5W_FC1_0_ce1;
wire   [7:0] p_ZL5W_FC1_0_q1;
reg   [13:0] p_ZL5W_FC1_0_address2;
reg    p_ZL5W_FC1_0_ce2;
wire   [7:0] p_ZL5W_FC1_0_q2;
wire   [13:0] p_ZL5W_FC1_0_address3;
reg    p_ZL5W_FC1_0_ce3;
wire   [7:0] p_ZL5W_FC1_0_q3;
reg   [13:0] p_ZL5W_FC1_1_address0;
reg    p_ZL5W_FC1_1_ce0;
wire   [7:0] p_ZL5W_FC1_1_q0;
reg   [13:0] p_ZL5W_FC1_1_address1;
reg    p_ZL5W_FC1_1_ce1;
wire   [7:0] p_ZL5W_FC1_1_q1;
reg   [13:0] p_ZL5W_FC1_1_address2;
reg    p_ZL5W_FC1_1_ce2;
wire   [7:0] p_ZL5W_FC1_1_q2;
wire   [13:0] p_ZL5W_FC1_1_address3;
reg    p_ZL5W_FC1_1_ce3;
wire   [7:0] p_ZL5W_FC1_1_q3;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state3_pp0_stage0_iter1;
wire    ap_block_state5_pp0_stage0_iter2;
wire    ap_block_state7_pp0_stage0_iter3;
wire    ap_block_state9_pp0_stage0_iter4;
wire    ap_block_state11_pp0_stage0_iter5;
wire    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln151_fu_386_p2;
reg   [0:0] icmp_ln151_reg_967_pp0_iter1_reg;
reg   [0:0] icmp_ln151_reg_967_pp0_iter2_reg;
reg   [0:0] icmp_ln151_reg_967_pp0_iter3_reg;
wire   [2:0] select_ln151_fu_416_p3;
reg   [2:0] select_ln151_reg_971;
wire   [6:0] add_ln157_fu_462_p2;
reg   [6:0] add_ln157_reg_982;
reg   [6:0] add_ln157_reg_982_pp0_iter1_reg;
wire   [8:0] tmp_9_fu_513_p3;
reg   [8:0] tmp_9_reg_992;
wire    ap_block_pp0_stage1_11001;
wire  signed [10:0] grp_fu_883_p3;
reg  signed [10:0] empty_341_reg_1009;
reg  signed [9:0] trunc_ln186_1_reg_1016;
wire   [0:0] trunc_ln186_fu_535_p1;
reg   [0:0] trunc_ln186_reg_1022;
reg   [0:0] trunc_ln186_reg_1022_pp0_iter2_reg;
reg  signed [7:0] cnn_accel_ap_int_8_const_ap_uint_4_pool2_load_reg_1046;
wire  signed [10:0] sext_ln186_1_fu_559_p1;
reg  signed [10:0] sext_ln186_1_reg_1051;
reg  signed [7:0] cnn_accel_ap_int_8_const_ap_uint_4_pool2_58_load_reg_1066;
wire   [7:0] tmp_fu_659_p4;
reg  signed [7:0] tmp_reg_1111;
wire   [7:0] tmp_2_fu_675_p4;
reg  signed [7:0] tmp_2_reg_1126;
reg  signed [7:0] cnn_accel_ap_int_8_const_ap_uint_4_pool2_58_load_2_reg_1151;
reg  signed [7:0] cnn_accel_ap_int_8_const_ap_uint_4_pool2_load_3_reg_1166;
wire   [15:0] mul_ln840_fu_778_p2;
reg  signed [15:0] mul_ln840_reg_1181;
reg  signed [7:0] cnn_accel_ap_int_8_const_ap_uint_4_pool2_58_load_1_reg_1196;
wire  signed [7:0] grp_fu_341_p4;
reg  signed [7:0] tmp_3_reg_1201;
wire   [7:0] tmp_5_fu_791_p4;
reg  signed [7:0] tmp_5_reg_1206;
wire   [15:0] mul_ln840_5_fu_832_p2;
reg  signed [15:0] mul_ln840_5_reg_1231;
wire  signed [16:0] grp_fu_893_p3;
wire  signed [16:0] grp_fu_901_p3;
reg  signed [16:0] add_ln840_2_reg_1246;
wire   [17:0] add_ln840_5_fu_856_p2;
reg   [17:0] add_ln840_5_reg_1251;
reg    ap_enable_reg_pp0_iter0_reg;
wire    ap_block_pp0_stage0_subdone;
wire   [63:0] zext_ln157_2_fu_520_p1;
wire    ap_block_pp0_stage1;
wire   [63:0] zext_ln157_4_fu_543_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln157_5_fu_554_p1;
wire   [63:0] zext_ln186_fu_570_p1;
wire   [63:0] zext_ln186_1_fu_600_p1;
wire   [63:0] zext_ln186_2_fu_621_p1;
wire   [63:0] zext_ln186_4_fu_642_p1;
wire   [63:0] zext_ln157_3_fu_653_p1;
wire   [63:0] zext_ln186_3_fu_708_p1;
wire   [63:0] zext_ln186_5_fu_746_p1;
wire   [63:0] zext_ln186_6_fu_766_p1;
reg   [24:0] acc_V_fu_86;
wire   [24:0] acc_V_2_fu_868_p2;
wire  signed [24:0] sext_ln150_cast_fu_359_p1;
wire    ap_loop_init;
reg   [2:0] y_fu_90;
wire   [2:0] add_ln152_fu_468_p2;
reg   [2:0] ap_sig_allocacmp_y_load;
reg   [4:0] c_fu_94;
wire   [4:0] select_ln151_1_fu_424_p3;
reg   [4:0] ap_sig_allocacmp_c_load;
reg   [6:0] indvar_flatten_fu_98;
wire   [6:0] add_ln151_1_fu_392_p2;
reg   [6:0] ap_sig_allocacmp_indvar_flatten_load;
wire    ap_block_pp0_stage0_01001;
reg   [0:0] grp_fu_341_p3;
reg   [0:0] grp_fu_350_p3;
wire   [0:0] icmp_ln152_fu_410_p2;
wire   [4:0] add_ln151_fu_404_p2;
wire   [3:0] trunc_ln157_fu_436_p1;
wire   [6:0] tmp_7_cast_fu_440_p3;
wire   [6:0] zext_ln157_fu_432_p1;
wire   [6:0] sub_ln157_fu_448_p2;
wire   [6:0] zext_ln157_1_fu_458_p1;
wire   [5:0] p_shl_fu_492_p3;
wire   [6:0] p_shl_cast_fu_499_p1;
wire   [6:0] zext_ln152_fu_489_p1;
wire  signed [6:0] empty_340_fu_503_p2;
wire   [8:0] or_ln157_1_fu_538_p2;
wire   [8:0] or_ln157_2_fu_549_p2;
wire  signed [13:0] sext_ln186_3_fu_562_p1;
wire   [13:0] add_ln186_3_fu_565_p2;
(* use_dsp48 = "no" *) wire   [10:0] add_ln156_fu_576_p2;
wire   [9:0] trunc_ln186_2_fu_581_p4;
wire  signed [13:0] sext_ln186_6_fu_591_p1;
wire   [13:0] add_ln186_4_fu_595_p2;
wire   [10:0] add_ln186_fu_606_p2;
wire  signed [13:0] sext_ln186_9_fu_612_p1;
wire   [13:0] add_ln186_5_fu_616_p2;
wire   [10:0] add_ln186_1_fu_627_p2;
wire  signed [13:0] sext_ln186_12_fu_633_p1;
wire   [13:0] add_ln186_7_fu_637_p2;
wire   [8:0] or_ln157_fu_648_p2;
(* use_dsp48 = "no" *) wire   [10:0] add_ln156_1_fu_684_p2;
wire   [9:0] trunc_ln186_3_fu_689_p4;
wire  signed [13:0] sext_ln186_11_fu_699_p1;
wire   [13:0] add_ln186_6_fu_703_p2;
wire  signed [7:0] grp_fu_350_p4;
(* use_dsp48 = "no" *) wire   [10:0] add_ln156_2_fu_722_p2;
wire   [9:0] trunc_ln186_4_fu_727_p4;
wire  signed [13:0] sext_ln186_13_fu_737_p1;
wire   [13:0] add_ln186_8_fu_741_p2;
wire   [10:0] add_ln186_2_fu_752_p2;
wire  signed [13:0] sext_ln186_14_fu_757_p1;
wire   [13:0] add_ln186_9_fu_761_p2;
wire  signed [15:0] mul_ln840_3_fu_816_p2;
wire  signed [16:0] grp_fu_909_p3;
wire  signed [16:0] grp_fu_918_p3;
wire  signed [17:0] sext_ln840_9_fu_844_p1;
wire  signed [17:0] sext_ln840_10_fu_847_p1;
wire   [17:0] add_ln840_4_fu_850_p2;
wire  signed [17:0] sext_ln840_8_fu_841_p1;
wire  signed [24:0] sext_ln840_11_fu_865_p1;
wire   [4:0] grp_fu_883_p0;
wire   [5:0] grp_fu_883_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_condition_exit_pp0_iter4_stage0;
reg    ap_idle_pp0_0to3;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg   [1:0] ap_NS_fsm;
reg    ap_idle_pp0_1to5;
wire    ap_enable_pp0;
wire    ap_start_int;
wire   [10:0] grp_fu_883_p00;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 ap_done_reg = 1'b0;
end

cnn_accel_fc1_layer_Pipeline_VITIS_LOOP_151_1_VITIS_LOOP_152_2_p_ZL5W_FC1_0_ROM_AUTO_1R #(
    .DataWidth( 8 ),
    .AddressRange( 12544 ),
    .AddressWidth( 14 ))
p_ZL5W_FC1_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL5W_FC1_0_address0),
    .ce0(p_ZL5W_FC1_0_ce0),
    .q0(p_ZL5W_FC1_0_q0),
    .address1(p_ZL5W_FC1_0_address1),
    .ce1(p_ZL5W_FC1_0_ce1),
    .q1(p_ZL5W_FC1_0_q1),
    .address2(p_ZL5W_FC1_0_address2),
    .ce2(p_ZL5W_FC1_0_ce2),
    .q2(p_ZL5W_FC1_0_q2),
    .address3(p_ZL5W_FC1_0_address3),
    .ce3(p_ZL5W_FC1_0_ce3),
    .q3(p_ZL5W_FC1_0_q3)
);

cnn_accel_fc1_layer_Pipeline_VITIS_LOOP_151_1_VITIS_LOOP_152_2_p_ZL5W_FC1_1_ROM_AUTO_1R #(
    .DataWidth( 8 ),
    .AddressRange( 12544 ),
    .AddressWidth( 14 ))
p_ZL5W_FC1_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL5W_FC1_1_address0),
    .ce0(p_ZL5W_FC1_1_ce0),
    .q0(p_ZL5W_FC1_1_q0),
    .address1(p_ZL5W_FC1_1_address1),
    .ce1(p_ZL5W_FC1_1_ce1),
    .q1(p_ZL5W_FC1_1_q1),
    .address2(p_ZL5W_FC1_1_address2),
    .ce2(p_ZL5W_FC1_1_ce2),
    .q2(p_ZL5W_FC1_1_q2),
    .address3(p_ZL5W_FC1_1_address3),
    .ce3(p_ZL5W_FC1_1_ce3),
    .q3(p_ZL5W_FC1_1_q3)
);

cnn_accel_mux_21_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 1 ),
    .dout_WIDTH( 8 ))
mux_21_8_1_1_U1976(
    .din0(p_ZL5W_FC1_1_q2),
    .din1(p_ZL5W_FC1_0_q2),
    .din2(grp_fu_341_p3),
    .dout(grp_fu_341_p4)
);

cnn_accel_mux_21_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 1 ),
    .dout_WIDTH( 8 ))
mux_21_8_1_1_U1977(
    .din0(p_ZL5W_FC1_0_q0),
    .din1(p_ZL5W_FC1_1_q0),
    .din2(grp_fu_350_p3),
    .dout(grp_fu_350_p4)
);

cnn_accel_mux_21_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 1 ),
    .dout_WIDTH( 8 ))
mux_21_8_1_1_U1978(
    .din0(p_ZL5W_FC1_0_q3),
    .din1(p_ZL5W_FC1_1_q3),
    .din2(trunc_ln186_reg_1022),
    .dout(tmp_fu_659_p4)
);

cnn_accel_mux_21_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 1 ),
    .dout_WIDTH( 8 ))
mux_21_8_1_1_U1979(
    .din0(p_ZL5W_FC1_0_q1),
    .din1(p_ZL5W_FC1_1_q1),
    .din2(trunc_ln186_reg_1022),
    .dout(tmp_2_fu_675_p4)
);

cnn_accel_mul_8s_8s_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
mul_8s_8s_16_1_1_U1980(
    .din0(tmp_reg_1111),
    .din1(cnn_accel_ap_int_8_const_ap_uint_4_pool2_load_reg_1046),
    .dout(mul_ln840_fu_778_p2)
);

cnn_accel_mux_21_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 1 ),
    .dout_WIDTH( 8 ))
mux_21_8_1_1_U1981(
    .din0(p_ZL5W_FC1_1_q1),
    .din1(p_ZL5W_FC1_0_q1),
    .din2(trunc_ln186_reg_1022_pp0_iter2_reg),
    .dout(tmp_5_fu_791_p4)
);

cnn_accel_mul_8s_8s_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
mul_8s_8s_16_1_1_U1982(
    .din0(tmp_3_reg_1201),
    .din1(cnn_accel_ap_int_8_const_ap_uint_4_pool2_58_load_1_reg_1196),
    .dout(mul_ln840_3_fu_816_p2)
);

cnn_accel_mul_8s_8s_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
mul_8s_8s_16_1_1_U1983(
    .din0(tmp_5_reg_1206),
    .din1(cnn_accel_ap_int_8_const_ap_uint_4_pool2_58_load_2_reg_1151),
    .dout(mul_ln840_5_fu_832_p2)
);

cnn_accel_mac_muladd_5ns_6ns_7s_11_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 5 ),
    .din1_WIDTH( 6 ),
    .din2_WIDTH( 7 ),
    .dout_WIDTH( 11 ))
mac_muladd_5ns_6ns_7s_11_4_1_U1984(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_883_p0),
    .din1(grp_fu_883_p1),
    .din2(empty_340_fu_503_p2),
    .ce(1'b1),
    .dout(grp_fu_883_p3)
);

cnn_accel_mac_muladd_8s_8s_16s_17_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 17 ))
mac_muladd_8s_8s_16s_17_4_1_U1985(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_341_p4),
    .din1(cnn_accel_ap_int_8_const_ap_uint_4_pool2_58_load_reg_1066),
    .din2(mul_ln840_reg_1181),
    .ce(1'b1),
    .dout(grp_fu_893_p3)
);

cnn_accel_mac_muladd_8s_8s_16s_17_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 17 ))
mac_muladd_8s_8s_16s_17_4_1_U1986(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_350_p4),
    .din1(cnn_accel_ap_int_8_const_ap_uint_4_pool2_q1),
    .din2(mul_ln840_3_fu_816_p2),
    .ce(1'b1),
    .dout(grp_fu_901_p3)
);

cnn_accel_mac_muladd_8s_8s_17s_17_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 17 ),
    .dout_WIDTH( 17 ))
mac_muladd_8s_8s_17s_17_4_1_U1987(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_2_reg_1126),
    .din1(cnn_accel_ap_int_8_const_ap_uint_4_pool2_q0),
    .din2(grp_fu_893_p3),
    .ce(1'b1),
    .dout(grp_fu_909_p3)
);

cnn_accel_mac_muladd_8s_8s_16s_17_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 17 ))
mac_muladd_8s_8s_16s_17_4_1_U1988(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_350_p4),
    .din1(cnn_accel_ap_int_8_const_ap_uint_4_pool2_load_3_reg_1166),
    .din2(mul_ln840_5_reg_1231),
    .ce(1'b1),
    .dout(grp_fu_918_p3)
);

cnn_accel_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage1),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter4_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage1)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter5 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            acc_V_fu_86 <= sext_ln150_cast_fu_359_p1;
        end else if ((ap_enable_reg_pp0_iter5 == 1'b1)) begin
            acc_V_fu_86 <= acc_V_2_fu_868_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to3 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter4_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to3 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter4_stage0))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to3 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter4_stage0))) begin
        ap_loop_exit_ready_pp0_iter3_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to3 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter4_stage0))) begin
        ap_loop_exit_ready_pp0_iter4_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln151_fu_386_p2 == 1'd0))) begin
            c_fu_94 <= select_ln151_1_fu_424_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            c_fu_94 <= 5'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln151_fu_386_p2 == 1'd0))) begin
            indvar_flatten_fu_98 <= add_ln151_1_fu_392_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_98 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln151_fu_386_p2 == 1'd0))) begin
            y_fu_90 <= add_ln152_fu_468_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            y_fu_90 <= 3'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln151_fu_386_p2 == 1'd0))) begin
        add_ln157_reg_982 <= add_ln157_fu_462_p2;
        select_ln151_reg_971 <= select_ln151_fu_416_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln157_reg_982_pp0_iter1_reg <= add_ln157_reg_982;
        icmp_ln151_reg_967 <= icmp_ln151_fu_386_p2;
        icmp_ln151_reg_967_pp0_iter1_reg <= icmp_ln151_reg_967;
        icmp_ln151_reg_967_pp0_iter2_reg <= icmp_ln151_reg_967_pp0_iter1_reg;
        icmp_ln151_reg_967_pp0_iter3_reg <= icmp_ln151_reg_967_pp0_iter2_reg;
        mul_ln840_reg_1181 <= mul_ln840_fu_778_p2;
        sext_ln186_1_reg_1051 <= sext_ln186_1_fu_559_p1;
        tmp_5_reg_1206 <= tmp_5_fu_791_p4;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln840_2_reg_1246 <= grp_fu_901_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        add_ln840_5_reg_1251 <= add_ln840_5_fu_856_p2;
        mul_ln840_5_reg_1231 <= mul_ln840_5_fu_832_p2;
        tmp_2_reg_1126 <= tmp_2_fu_675_p4;
        tmp_9_reg_992[8 : 2] <= tmp_9_fu_513_p3[8 : 2];
        tmp_reg_1111 <= tmp_fu_659_p4;
        trunc_ln186_1_reg_1016 <= {{grp_fu_883_p3[10:1]}};
        trunc_ln186_reg_1022 <= trunc_ln186_fu_535_p1;
        trunc_ln186_reg_1022_pp0_iter2_reg <= trunc_ln186_reg_1022;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        cnn_accel_ap_int_8_const_ap_uint_4_pool2_58_load_1_reg_1196 <= cnn_accel_ap_int_8_const_ap_uint_4_pool2_58_q0;
        tmp_3_reg_1201 <= grp_fu_341_p4;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        cnn_accel_ap_int_8_const_ap_uint_4_pool2_58_load_2_reg_1151 <= cnn_accel_ap_int_8_const_ap_uint_4_pool2_58_q0;
        cnn_accel_ap_int_8_const_ap_uint_4_pool2_load_3_reg_1166 <= cnn_accel_ap_int_8_const_ap_uint_4_pool2_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        cnn_accel_ap_int_8_const_ap_uint_4_pool2_58_load_reg_1066 <= cnn_accel_ap_int_8_const_ap_uint_4_pool2_58_q1;
        cnn_accel_ap_int_8_const_ap_uint_4_pool2_load_reg_1046 <= cnn_accel_ap_int_8_const_ap_uint_4_pool2_q1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        empty_341_reg_1009 <= grp_fu_883_p3;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln151_reg_967_pp0_iter3_reg == 1'd1))) begin
        acc_V_2_out_ap_vld = 1'b1;
    end else begin
        acc_V_2_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln151_reg_967 == 1'd1) & (1'b0 == ap_block_pp0_stage1_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln151_reg_967_pp0_iter3_reg == 1'd1))) begin
        ap_condition_exit_pp0_iter4_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter4_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter4_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to3 = 1'b1;
    end else begin
        ap_idle_pp0_0to3 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0_1to5 = 1'b1;
    end else begin
        ap_idle_pp0_1to5 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_c_load = 5'd0;
    end else begin
        ap_sig_allocacmp_c_load = c_fu_94;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten_load = 7'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten_load = indvar_flatten_fu_98;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_y_load = 3'd0;
    end else begin
        ap_sig_allocacmp_y_load = y_fu_90;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            cnn_accel_ap_int_8_const_ap_uint_4_pool2_58_address0 = zext_ln157_3_fu_653_p1;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            cnn_accel_ap_int_8_const_ap_uint_4_pool2_58_address0 = zext_ln157_4_fu_543_p1;
        end else begin
            cnn_accel_ap_int_8_const_ap_uint_4_pool2_58_address0 = 'bx;
        end
    end else begin
        cnn_accel_ap_int_8_const_ap_uint_4_pool2_58_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        cnn_accel_ap_int_8_const_ap_uint_4_pool2_58_ce0 = 1'b1;
    end else begin
        cnn_accel_ap_int_8_const_ap_uint_4_pool2_58_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        cnn_accel_ap_int_8_const_ap_uint_4_pool2_58_ce1 = 1'b1;
    end else begin
        cnn_accel_ap_int_8_const_ap_uint_4_pool2_58_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            cnn_accel_ap_int_8_const_ap_uint_4_pool2_address0 = zext_ln157_3_fu_653_p1;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            cnn_accel_ap_int_8_const_ap_uint_4_pool2_address0 = zext_ln157_5_fu_554_p1;
        end else begin
            cnn_accel_ap_int_8_const_ap_uint_4_pool2_address0 = 'bx;
        end
    end else begin
        cnn_accel_ap_int_8_const_ap_uint_4_pool2_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        cnn_accel_ap_int_8_const_ap_uint_4_pool2_address1 = zext_ln157_4_fu_543_p1;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        cnn_accel_ap_int_8_const_ap_uint_4_pool2_address1 = zext_ln157_2_fu_520_p1;
    end else begin
        cnn_accel_ap_int_8_const_ap_uint_4_pool2_address1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        cnn_accel_ap_int_8_const_ap_uint_4_pool2_ce0 = 1'b1;
    end else begin
        cnn_accel_ap_int_8_const_ap_uint_4_pool2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        cnn_accel_ap_int_8_const_ap_uint_4_pool2_ce1 = 1'b1;
    end else begin
        cnn_accel_ap_int_8_const_ap_uint_4_pool2_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_341_p3 = trunc_ln186_reg_1022_pp0_iter2_reg;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_341_p3 = trunc_ln186_reg_1022;
    end else begin
        grp_fu_341_p3 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_350_p3 = trunc_ln186_reg_1022_pp0_iter2_reg;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_350_p3 = trunc_ln186_reg_1022;
    end else begin
        grp_fu_350_p3 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            p_ZL5W_FC1_0_address0 = zext_ln186_6_fu_766_p1;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            p_ZL5W_FC1_0_address0 = zext_ln186_4_fu_642_p1;
        end else begin
            p_ZL5W_FC1_0_address0 = 'bx;
        end
    end else begin
        p_ZL5W_FC1_0_address0 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            p_ZL5W_FC1_0_address1 = zext_ln186_5_fu_746_p1;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            p_ZL5W_FC1_0_address1 = zext_ln186_2_fu_621_p1;
        end else begin
            p_ZL5W_FC1_0_address1 = 'bx;
        end
    end else begin
        p_ZL5W_FC1_0_address1 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            p_ZL5W_FC1_0_address2 = zext_ln186_3_fu_708_p1;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            p_ZL5W_FC1_0_address2 = zext_ln186_1_fu_600_p1;
        end else begin
            p_ZL5W_FC1_0_address2 = 'bx;
        end
    end else begin
        p_ZL5W_FC1_0_address2 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        p_ZL5W_FC1_0_ce0 = 1'b1;
    end else begin
        p_ZL5W_FC1_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        p_ZL5W_FC1_0_ce1 = 1'b1;
    end else begin
        p_ZL5W_FC1_0_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        p_ZL5W_FC1_0_ce2 = 1'b1;
    end else begin
        p_ZL5W_FC1_0_ce2 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZL5W_FC1_0_ce3 = 1'b1;
    end else begin
        p_ZL5W_FC1_0_ce3 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            p_ZL5W_FC1_1_address0 = zext_ln186_6_fu_766_p1;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            p_ZL5W_FC1_1_address0 = zext_ln186_4_fu_642_p1;
        end else begin
            p_ZL5W_FC1_1_address0 = 'bx;
        end
    end else begin
        p_ZL5W_FC1_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            p_ZL5W_FC1_1_address1 = zext_ln186_5_fu_746_p1;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            p_ZL5W_FC1_1_address1 = zext_ln186_2_fu_621_p1;
        end else begin
            p_ZL5W_FC1_1_address1 = 'bx;
        end
    end else begin
        p_ZL5W_FC1_1_address1 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            p_ZL5W_FC1_1_address2 = zext_ln186_3_fu_708_p1;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            p_ZL5W_FC1_1_address2 = zext_ln186_1_fu_600_p1;
        end else begin
            p_ZL5W_FC1_1_address2 = 'bx;
        end
    end else begin
        p_ZL5W_FC1_1_address2 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        p_ZL5W_FC1_1_ce0 = 1'b1;
    end else begin
        p_ZL5W_FC1_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        p_ZL5W_FC1_1_ce1 = 1'b1;
    end else begin
        p_ZL5W_FC1_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        p_ZL5W_FC1_1_ce2 = 1'b1;
    end else begin
        p_ZL5W_FC1_1_ce2 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZL5W_FC1_1_ce3 = 1'b1;
    end else begin
        p_ZL5W_FC1_1_ce3 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if (((ap_idle_pp0_0to3 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter4_stage0))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((~((ap_start_int == 1'b0) & (ap_idle_pp0_1to5 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign acc_V_2_fu_868_p2 = ($signed(acc_V_fu_86) + $signed(sext_ln840_11_fu_865_p1));

assign acc_V_2_out = acc_V_fu_86;

assign add_ln151_1_fu_392_p2 = (ap_sig_allocacmp_indvar_flatten_load + 7'd1);

assign add_ln151_fu_404_p2 = (ap_sig_allocacmp_c_load + 5'd1);

assign add_ln152_fu_468_p2 = (select_ln151_fu_416_p3 + 3'd1);

assign add_ln156_1_fu_684_p2 = ($signed(empty_341_reg_1009) + $signed(11'd3));

assign add_ln156_2_fu_722_p2 = ($signed(empty_341_reg_1009) + $signed(11'd5));

assign add_ln156_fu_576_p2 = ($signed(empty_341_reg_1009) + $signed(11'd1));

assign add_ln157_fu_462_p2 = (sub_ln157_fu_448_p2 + zext_ln157_1_fu_458_p1);

assign add_ln186_1_fu_627_p2 = ($signed(sext_ln186_1_fu_559_p1) + $signed(11'd2));

assign add_ln186_2_fu_752_p2 = ($signed(sext_ln186_1_reg_1051) + $signed(11'd3));

assign add_ln186_3_fu_565_p2 = ($signed(phi_mul) + $signed(sext_ln186_3_fu_562_p1));

assign add_ln186_4_fu_595_p2 = ($signed(phi_mul) + $signed(sext_ln186_6_fu_591_p1));

assign add_ln186_5_fu_616_p2 = ($signed(phi_mul) + $signed(sext_ln186_9_fu_612_p1));

assign add_ln186_6_fu_703_p2 = ($signed(phi_mul) + $signed(sext_ln186_11_fu_699_p1));

assign add_ln186_7_fu_637_p2 = ($signed(phi_mul) + $signed(sext_ln186_12_fu_633_p1));

assign add_ln186_8_fu_741_p2 = ($signed(phi_mul) + $signed(sext_ln186_13_fu_737_p1));

assign add_ln186_9_fu_761_p2 = ($signed(phi_mul) + $signed(sext_ln186_14_fu_757_p1));

assign add_ln186_fu_606_p2 = ($signed(sext_ln186_1_fu_559_p1) + $signed(11'd1));

assign add_ln840_4_fu_850_p2 = ($signed(sext_ln840_9_fu_844_p1) + $signed(sext_ln840_10_fu_847_p1));

assign add_ln840_5_fu_856_p2 = ($signed(add_ln840_4_fu_850_p2) + $signed(sext_ln840_8_fu_841_p1));

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_block_state10_pp0_stage1_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage1_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage1_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage1_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage1_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage1;

assign cnn_accel_ap_int_8_const_ap_uint_4_pool2_58_address1 = zext_ln157_2_fu_520_p1;

assign empty_340_fu_503_p2 = (p_shl_cast_fu_499_p1 - zext_ln152_fu_489_p1);

assign grp_fu_883_p0 = grp_fu_883_p00;

assign grp_fu_883_p00 = select_ln151_1_fu_424_p3;

assign grp_fu_883_p1 = 11'd49;

assign icmp_ln151_fu_386_p2 = ((ap_sig_allocacmp_indvar_flatten_load == 7'd112) ? 1'b1 : 1'b0);

assign icmp_ln152_fu_410_p2 = ((ap_sig_allocacmp_y_load == 3'd7) ? 1'b1 : 1'b0);

assign or_ln157_1_fu_538_p2 = (tmp_9_reg_992 | 9'd2);

assign or_ln157_2_fu_549_p2 = (tmp_9_reg_992 | 9'd3);

assign or_ln157_fu_648_p2 = (tmp_9_reg_992 | 9'd1);

assign p_ZL5W_FC1_0_address3 = zext_ln186_fu_570_p1;

assign p_ZL5W_FC1_1_address3 = zext_ln186_fu_570_p1;

assign p_shl_cast_fu_499_p1 = p_shl_fu_492_p3;

assign p_shl_fu_492_p3 = {{select_ln151_reg_971}, {3'd0}};

assign select_ln151_1_fu_424_p3 = ((icmp_ln152_fu_410_p2[0:0] == 1'b1) ? add_ln151_fu_404_p2 : ap_sig_allocacmp_c_load);

assign select_ln151_fu_416_p3 = ((icmp_ln152_fu_410_p2[0:0] == 1'b1) ? 3'd0 : ap_sig_allocacmp_y_load);

assign sext_ln150_cast_fu_359_p1 = $signed(sext_ln150);

assign sext_ln186_11_fu_699_p1 = $signed(trunc_ln186_3_fu_689_p4);

assign sext_ln186_12_fu_633_p1 = $signed(add_ln186_1_fu_627_p2);

assign sext_ln186_13_fu_737_p1 = $signed(trunc_ln186_4_fu_727_p4);

assign sext_ln186_14_fu_757_p1 = $signed(add_ln186_2_fu_752_p2);

assign sext_ln186_1_fu_559_p1 = trunc_ln186_1_reg_1016;

assign sext_ln186_3_fu_562_p1 = trunc_ln186_1_reg_1016;

assign sext_ln186_6_fu_591_p1 = $signed(trunc_ln186_2_fu_581_p4);

assign sext_ln186_9_fu_612_p1 = $signed(add_ln186_fu_606_p2);

assign sext_ln840_10_fu_847_p1 = grp_fu_918_p3;

assign sext_ln840_11_fu_865_p1 = $signed(add_ln840_5_reg_1251);

assign sext_ln840_8_fu_841_p1 = grp_fu_909_p3;

assign sext_ln840_9_fu_844_p1 = add_ln840_2_reg_1246;

assign sub_ln157_fu_448_p2 = (tmp_7_cast_fu_440_p3 - zext_ln157_fu_432_p1);

assign tmp_7_cast_fu_440_p3 = {{trunc_ln157_fu_436_p1}, {3'd0}};

assign tmp_9_fu_513_p3 = {{add_ln157_reg_982_pp0_iter1_reg}, {2'd0}};

assign trunc_ln157_fu_436_p1 = select_ln151_1_fu_424_p3[3:0];

assign trunc_ln186_2_fu_581_p4 = {{add_ln156_fu_576_p2[10:1]}};

assign trunc_ln186_3_fu_689_p4 = {{add_ln156_1_fu_684_p2[10:1]}};

assign trunc_ln186_4_fu_727_p4 = {{add_ln156_2_fu_722_p2[10:1]}};

assign trunc_ln186_fu_535_p1 = grp_fu_883_p3[0:0];

assign zext_ln152_fu_489_p1 = select_ln151_reg_971;

assign zext_ln157_1_fu_458_p1 = select_ln151_fu_416_p3;

assign zext_ln157_2_fu_520_p1 = tmp_9_fu_513_p3;

assign zext_ln157_3_fu_653_p1 = or_ln157_fu_648_p2;

assign zext_ln157_4_fu_543_p1 = or_ln157_1_fu_538_p2;

assign zext_ln157_5_fu_554_p1 = or_ln157_2_fu_549_p2;

assign zext_ln157_fu_432_p1 = select_ln151_1_fu_424_p3;

assign zext_ln186_1_fu_600_p1 = add_ln186_4_fu_595_p2;

assign zext_ln186_2_fu_621_p1 = add_ln186_5_fu_616_p2;

assign zext_ln186_3_fu_708_p1 = add_ln186_6_fu_703_p2;

assign zext_ln186_4_fu_642_p1 = add_ln186_7_fu_637_p2;

assign zext_ln186_5_fu_746_p1 = add_ln186_8_fu_741_p2;

assign zext_ln186_6_fu_766_p1 = add_ln186_9_fu_761_p2;

assign zext_ln186_fu_570_p1 = add_ln186_3_fu_565_p2;

always @ (posedge ap_clk) begin
    tmp_9_reg_992[1:0] <= 2'b00;
end

endmodule //cnn_accel_fc1_layer_Pipeline_VITIS_LOOP_151_1_VITIS_LOOP_152_2
