// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module cnn_accel_cnn_accel_Pipeline_pool1_loop_VITIS_LOOP_53_1_VITIS_LOOP_54_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        cnn_accel_ap_int_8_const_ap_uint_4_conv1_address0,
        cnn_accel_ap_int_8_const_ap_uint_4_conv1_ce0,
        cnn_accel_ap_int_8_const_ap_uint_4_conv1_q0,
        cnn_accel_ap_int_8_const_ap_uint_4_conv1_address1,
        cnn_accel_ap_int_8_const_ap_uint_4_conv1_ce1,
        cnn_accel_ap_int_8_const_ap_uint_4_conv1_q1,
        cnn_accel_ap_int_8_const_ap_uint_4_conv1_1_address0,
        cnn_accel_ap_int_8_const_ap_uint_4_conv1_1_ce0,
        cnn_accel_ap_int_8_const_ap_uint_4_conv1_1_q0,
        cnn_accel_ap_int_8_const_ap_uint_4_conv1_1_address1,
        cnn_accel_ap_int_8_const_ap_uint_4_conv1_1_ce1,
        cnn_accel_ap_int_8_const_ap_uint_4_conv1_1_q1,
        pool1_V_address0,
        pool1_V_ce0,
        pool1_V_we0,
        pool1_V_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [11:0] cnn_accel_ap_int_8_const_ap_uint_4_conv1_address0;
output   cnn_accel_ap_int_8_const_ap_uint_4_conv1_ce0;
input  [7:0] cnn_accel_ap_int_8_const_ap_uint_4_conv1_q0;
output  [11:0] cnn_accel_ap_int_8_const_ap_uint_4_conv1_address1;
output   cnn_accel_ap_int_8_const_ap_uint_4_conv1_ce1;
input  [7:0] cnn_accel_ap_int_8_const_ap_uint_4_conv1_q1;
output  [11:0] cnn_accel_ap_int_8_const_ap_uint_4_conv1_1_address0;
output   cnn_accel_ap_int_8_const_ap_uint_4_conv1_1_ce0;
input  [7:0] cnn_accel_ap_int_8_const_ap_uint_4_conv1_1_q0;
output  [11:0] cnn_accel_ap_int_8_const_ap_uint_4_conv1_1_address1;
output   cnn_accel_ap_int_8_const_ap_uint_4_conv1_1_ce1;
input  [7:0] cnn_accel_ap_int_8_const_ap_uint_4_conv1_1_q1;
output  [10:0] pool1_V_address0;
output   pool1_V_ce0;
output   pool1_V_we0;
output  [7:0] pool1_V_d0;

reg ap_idle;
reg cnn_accel_ap_int_8_const_ap_uint_4_conv1_ce0;
reg cnn_accel_ap_int_8_const_ap_uint_4_conv1_ce1;
reg cnn_accel_ap_int_8_const_ap_uint_4_conv1_1_ce0;
reg cnn_accel_ap_int_8_const_ap_uint_4_conv1_1_ce1;
reg pool1_V_ce0;
reg pool1_V_we0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln52_fu_179_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire   [3:0] select_ln53_fu_295_p3;
reg   [3:0] select_ln53_reg_542;
wire   [9:0] add_ln56_fu_315_p2;
reg   [9:0] add_ln56_reg_548;
wire   [6:0] trunc_ln56_fu_321_p1;
reg   [6:0] trunc_ln56_reg_554;
wire   [10:0] add_ln63_fu_413_p2;
reg   [10:0] add_ln63_reg_560;
reg   [10:0] add_ln63_reg_560_pp0_iter2_reg;
reg   [10:0] add_ln63_reg_560_pp0_iter3_reg;
wire   [63:0] zext_ln56_4_fu_436_p1;
reg   [63:0] zext_ln56_4_reg_565;
wire   [63:0] zext_ln57_1_fu_457_p1;
reg   [63:0] zext_ln57_1_reg_575;
wire   [7:0] m_V_5_fu_468_p3;
reg   [7:0] m_V_5_reg_595;
reg   [7:0] v3_V_reg_601;
wire   [7:0] m_V_7_fu_481_p3;
reg   [7:0] m_V_7_reg_607;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln63_1_fu_488_p1;
reg   [3:0] x_fu_68;
wire   [3:0] add_ln54_fu_325_p2;
wire    ap_loop_init;
reg   [3:0] ap_sig_allocacmp_x_load;
reg   [3:0] y_fu_72;
wire   [3:0] select_ln53_1_fu_303_p3;
reg   [3:0] ap_sig_allocacmp_y_load;
reg   [7:0] indvar_flatten_fu_76;
wire   [7:0] select_ln53_2_fu_337_p3;
reg   [7:0] ap_sig_allocacmp_indvar_flatten_load;
reg   [3:0] c_fu_80;
wire   [3:0] select_ln52_1_fu_223_p3;
reg   [3:0] ap_sig_allocacmp_c_load;
reg   [10:0] indvar_flatten13_fu_84;
wire   [10:0] add_ln52_1_fu_185_p2;
reg   [10:0] ap_sig_allocacmp_indvar_flatten13_load;
wire   [0:0] icmp_ln53_fu_209_p2;
wire   [3:0] add_ln52_fu_203_p2;
wire   [7:0] tmp_4_fu_231_p3;
wire   [4:0] tmp_5_fu_243_p3;
wire   [8:0] zext_ln56_fu_239_p1;
wire   [8:0] zext_ln56_1_fu_251_p1;
wire   [8:0] sub_ln56_fu_255_p2;
wire   [0:0] icmp_ln54_fu_271_p2;
wire   [0:0] xor_ln52_fu_265_p2;
wire   [3:0] select_ln52_fu_215_p3;
wire   [0:0] and_ln52_fu_277_p2;
wire   [0:0] or_ln53_fu_289_p2;
wire   [3:0] add_ln53_fu_283_p2;
wire  signed [9:0] sext_ln53_fu_261_p1;
wire   [9:0] zext_ln56_2_fu_311_p1;
wire   [7:0] add_ln53_1_fu_331_p2;
wire   [11:0] p_shl4_fu_370_p3;
wire   [11:0] p_shl5_fu_377_p3;
wire   [10:0] p_shl_fu_390_p3;
wire   [10:0] p_shl6_fu_397_p3;
wire   [10:0] sub_ln63_fu_404_p2;
wire   [10:0] zext_ln63_fu_410_p1;
wire   [4:0] shl_ln_fu_419_p3;
wire   [11:0] sub_ln56_1_fu_384_p2;
wire   [11:0] zext_ln56_3_fu_426_p1;
wire   [11:0] add_ln56_1_fu_430_p2;
wire   [4:0] or_ln57_fu_441_p2;
wire   [11:0] zext_ln57_fu_447_p1;
wire   [11:0] add_ln57_fu_451_p2;
wire   [0:0] icmp_ln1035_fu_462_p2;
wire   [0:0] icmp_ln1035_1_fu_476_p2;
wire   [0:0] icmp_ln1035_2_fu_492_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_done_reg = 1'b0;
end

cnn_accel_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln52_fu_179_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            c_fu_80 <= select_ln52_1_fu_223_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            c_fu_80 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln52_fu_179_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten13_fu_84 <= add_ln52_1_fu_185_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten13_fu_84 <= 11'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln52_fu_179_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten_fu_76 <= select_ln53_2_fu_337_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_76 <= 8'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln52_fu_179_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            x_fu_68 <= add_ln54_fu_325_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            x_fu_68 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln52_fu_179_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            y_fu_72 <= select_ln53_1_fu_303_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            y_fu_72 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln52_fu_179_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln56_reg_548 <= add_ln56_fu_315_p2;
        select_ln53_reg_542 <= select_ln53_fu_295_p3;
        trunc_ln56_reg_554 <= trunc_ln56_fu_321_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln63_reg_560 <= add_ln63_fu_413_p2;
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        zext_ln56_4_reg_565[11 : 1] <= zext_ln56_4_fu_436_p1[11 : 1];
        zext_ln57_1_reg_575[11 : 1] <= zext_ln57_1_fu_457_p1[11 : 1];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        add_ln63_reg_560_pp0_iter2_reg <= add_ln63_reg_560;
        add_ln63_reg_560_pp0_iter3_reg <= add_ln63_reg_560_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        m_V_5_reg_595 <= m_V_5_fu_468_p3;
        m_V_7_reg_607 <= m_V_7_fu_481_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        v3_V_reg_601 <= cnn_accel_ap_int_8_const_ap_uint_4_conv1_1_q0;
    end
end

always @ (*) begin
    if (((icmp_ln52_fu_179_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_c_load = 4'd0;
    end else begin
        ap_sig_allocacmp_c_load = c_fu_80;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten13_load = 11'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten13_load = indvar_flatten13_fu_84;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten_load = 8'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten_load = indvar_flatten_fu_76;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_x_load = 4'd0;
    end else begin
        ap_sig_allocacmp_x_load = x_fu_68;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_y_load = 4'd0;
    end else begin
        ap_sig_allocacmp_y_load = y_fu_72;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        cnn_accel_ap_int_8_const_ap_uint_4_conv1_1_ce0 = 1'b1;
    end else begin
        cnn_accel_ap_int_8_const_ap_uint_4_conv1_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        cnn_accel_ap_int_8_const_ap_uint_4_conv1_1_ce1 = 1'b1;
    end else begin
        cnn_accel_ap_int_8_const_ap_uint_4_conv1_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        cnn_accel_ap_int_8_const_ap_uint_4_conv1_ce0 = 1'b1;
    end else begin
        cnn_accel_ap_int_8_const_ap_uint_4_conv1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        cnn_accel_ap_int_8_const_ap_uint_4_conv1_ce1 = 1'b1;
    end else begin
        cnn_accel_ap_int_8_const_ap_uint_4_conv1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        pool1_V_ce0 = 1'b1;
    end else begin
        pool1_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        pool1_V_we0 = 1'b1;
    end else begin
        pool1_V_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln52_1_fu_185_p2 = (ap_sig_allocacmp_indvar_flatten13_load + 11'd1);

assign add_ln52_fu_203_p2 = (ap_sig_allocacmp_c_load + 4'd1);

assign add_ln53_1_fu_331_p2 = (ap_sig_allocacmp_indvar_flatten_load + 8'd1);

assign add_ln53_fu_283_p2 = (select_ln52_fu_215_p3 + 4'd1);

assign add_ln54_fu_325_p2 = (select_ln53_fu_295_p3 + 4'd1);

assign add_ln56_1_fu_430_p2 = (sub_ln56_1_fu_384_p2 + zext_ln56_3_fu_426_p1);

assign add_ln56_fu_315_p2 = ($signed(sext_ln53_fu_261_p1) + $signed(zext_ln56_2_fu_311_p1));

assign add_ln57_fu_451_p2 = (sub_ln56_1_fu_384_p2 + zext_ln57_fu_447_p1);

assign add_ln63_fu_413_p2 = (sub_ln63_fu_404_p2 + zext_ln63_fu_410_p1);

assign and_ln52_fu_277_p2 = (xor_ln52_fu_265_p2 & icmp_ln54_fu_271_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign cnn_accel_ap_int_8_const_ap_uint_4_conv1_1_address0 = zext_ln57_1_reg_575;

assign cnn_accel_ap_int_8_const_ap_uint_4_conv1_1_address1 = zext_ln56_4_reg_565;

assign cnn_accel_ap_int_8_const_ap_uint_4_conv1_address0 = zext_ln57_1_fu_457_p1;

assign cnn_accel_ap_int_8_const_ap_uint_4_conv1_address1 = zext_ln56_4_fu_436_p1;

assign icmp_ln1035_1_fu_476_p2 = (($signed(cnn_accel_ap_int_8_const_ap_uint_4_conv1_1_q1) > $signed(m_V_5_reg_595)) ? 1'b1 : 1'b0);

assign icmp_ln1035_2_fu_492_p2 = (($signed(v3_V_reg_601) > $signed(m_V_7_reg_607)) ? 1'b1 : 1'b0);

assign icmp_ln1035_fu_462_p2 = (($signed(cnn_accel_ap_int_8_const_ap_uint_4_conv1_q0) > $signed(cnn_accel_ap_int_8_const_ap_uint_4_conv1_q1)) ? 1'b1 : 1'b0);

assign icmp_ln52_fu_179_p2 = ((ap_sig_allocacmp_indvar_flatten13_load == 11'd1568) ? 1'b1 : 1'b0);

assign icmp_ln53_fu_209_p2 = ((ap_sig_allocacmp_indvar_flatten_load == 8'd196) ? 1'b1 : 1'b0);

assign icmp_ln54_fu_271_p2 = ((ap_sig_allocacmp_x_load == 4'd14) ? 1'b1 : 1'b0);

assign m_V_5_fu_468_p3 = ((icmp_ln1035_fu_462_p2[0:0] == 1'b1) ? cnn_accel_ap_int_8_const_ap_uint_4_conv1_q0 : cnn_accel_ap_int_8_const_ap_uint_4_conv1_q1);

assign m_V_7_fu_481_p3 = ((icmp_ln1035_1_fu_476_p2[0:0] == 1'b1) ? cnn_accel_ap_int_8_const_ap_uint_4_conv1_1_q1 : m_V_5_reg_595);

assign or_ln53_fu_289_p2 = (icmp_ln53_fu_209_p2 | and_ln52_fu_277_p2);

assign or_ln57_fu_441_p2 = (shl_ln_fu_419_p3 | 5'd1);

assign p_shl4_fu_370_p3 = {{trunc_ln56_reg_554}, {5'd0}};

assign p_shl5_fu_377_p3 = {{add_ln56_reg_548}, {2'd0}};

assign p_shl6_fu_397_p3 = {{add_ln56_reg_548}, {1'd0}};

assign p_shl_fu_390_p3 = {{trunc_ln56_reg_554}, {4'd0}};

assign pool1_V_address0 = zext_ln63_1_fu_488_p1;

assign pool1_V_d0 = ((icmp_ln1035_2_fu_492_p2[0:0] == 1'b1) ? v3_V_reg_601 : m_V_7_reg_607);

assign select_ln52_1_fu_223_p3 = ((icmp_ln53_fu_209_p2[0:0] == 1'b1) ? add_ln52_fu_203_p2 : ap_sig_allocacmp_c_load);

assign select_ln52_fu_215_p3 = ((icmp_ln53_fu_209_p2[0:0] == 1'b1) ? 4'd0 : ap_sig_allocacmp_y_load);

assign select_ln53_1_fu_303_p3 = ((and_ln52_fu_277_p2[0:0] == 1'b1) ? add_ln53_fu_283_p2 : select_ln52_fu_215_p3);

assign select_ln53_2_fu_337_p3 = ((icmp_ln53_fu_209_p2[0:0] == 1'b1) ? 8'd1 : add_ln53_1_fu_331_p2);

assign select_ln53_fu_295_p3 = ((or_ln53_fu_289_p2[0:0] == 1'b1) ? 4'd0 : ap_sig_allocacmp_x_load);

assign sext_ln53_fu_261_p1 = $signed(sub_ln56_fu_255_p2);

assign shl_ln_fu_419_p3 = {{select_ln53_reg_542}, {1'd0}};

assign sub_ln56_1_fu_384_p2 = (p_shl4_fu_370_p3 - p_shl5_fu_377_p3);

assign sub_ln56_fu_255_p2 = (zext_ln56_fu_239_p1 - zext_ln56_1_fu_251_p1);

assign sub_ln63_fu_404_p2 = (p_shl_fu_390_p3 - p_shl6_fu_397_p3);

assign tmp_4_fu_231_p3 = {{select_ln52_1_fu_223_p3}, {4'd0}};

assign tmp_5_fu_243_p3 = {{select_ln52_1_fu_223_p3}, {1'd0}};

assign trunc_ln56_fu_321_p1 = add_ln56_fu_315_p2[6:0];

assign xor_ln52_fu_265_p2 = (icmp_ln53_fu_209_p2 ^ 1'd1);

assign zext_ln56_1_fu_251_p1 = tmp_5_fu_243_p3;

assign zext_ln56_2_fu_311_p1 = select_ln53_1_fu_303_p3;

assign zext_ln56_3_fu_426_p1 = shl_ln_fu_419_p3;

assign zext_ln56_4_fu_436_p1 = add_ln56_1_fu_430_p2;

assign zext_ln56_fu_239_p1 = tmp_4_fu_231_p3;

assign zext_ln57_1_fu_457_p1 = add_ln57_fu_451_p2;

assign zext_ln57_fu_447_p1 = or_ln57_fu_441_p2;

assign zext_ln63_1_fu_488_p1 = add_ln63_reg_560_pp0_iter3_reg;

assign zext_ln63_fu_410_p1 = select_ln53_reg_542;

always @ (posedge ap_clk) begin
    zext_ln56_4_reg_565[0] <= 1'b0;
    zext_ln56_4_reg_565[63:12] <= 52'b0000000000000000000000000000000000000000000000000000;
    zext_ln57_1_reg_575[0] <= 1'b1;
    zext_ln57_1_reg_575[63:12] <= 52'b0000000000000000000000000000000000000000000000000000;
end

endmodule //cnn_accel_cnn_accel_Pipeline_pool1_loop_VITIS_LOOP_53_1_VITIS_LOOP_54_2
