// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module cnn_accel_conv1_layer (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_gmem_AWVALID,
        m_axi_gmem_AWREADY,
        m_axi_gmem_AWADDR,
        m_axi_gmem_AWID,
        m_axi_gmem_AWLEN,
        m_axi_gmem_AWSIZE,
        m_axi_gmem_AWBURST,
        m_axi_gmem_AWLOCK,
        m_axi_gmem_AWCACHE,
        m_axi_gmem_AWPROT,
        m_axi_gmem_AWQOS,
        m_axi_gmem_AWREGION,
        m_axi_gmem_AWUSER,
        m_axi_gmem_WVALID,
        m_axi_gmem_WREADY,
        m_axi_gmem_WDATA,
        m_axi_gmem_WSTRB,
        m_axi_gmem_WLAST,
        m_axi_gmem_WID,
        m_axi_gmem_WUSER,
        m_axi_gmem_ARVALID,
        m_axi_gmem_ARREADY,
        m_axi_gmem_ARADDR,
        m_axi_gmem_ARID,
        m_axi_gmem_ARLEN,
        m_axi_gmem_ARSIZE,
        m_axi_gmem_ARBURST,
        m_axi_gmem_ARLOCK,
        m_axi_gmem_ARCACHE,
        m_axi_gmem_ARPROT,
        m_axi_gmem_ARQOS,
        m_axi_gmem_ARREGION,
        m_axi_gmem_ARUSER,
        m_axi_gmem_RVALID,
        m_axi_gmem_RREADY,
        m_axi_gmem_RDATA,
        m_axi_gmem_RLAST,
        m_axi_gmem_RID,
        m_axi_gmem_RFIFONUM,
        m_axi_gmem_RUSER,
        m_axi_gmem_RRESP,
        m_axi_gmem_BVALID,
        m_axi_gmem_BREADY,
        m_axi_gmem_BRESP,
        m_axi_gmem_BID,
        m_axi_gmem_BUSER,
        image_r,
        cnn_accel_ap_int_8_const_ap_uint_4_conv1_address0,
        cnn_accel_ap_int_8_const_ap_uint_4_conv1_ce0,
        cnn_accel_ap_int_8_const_ap_uint_4_conv1_we0,
        cnn_accel_ap_int_8_const_ap_uint_4_conv1_d0,
        cnn_accel_ap_int_8_const_ap_uint_4_conv1_1_address0,
        cnn_accel_ap_int_8_const_ap_uint_4_conv1_1_ce0,
        cnn_accel_ap_int_8_const_ap_uint_4_conv1_1_we0,
        cnn_accel_ap_int_8_const_ap_uint_4_conv1_1_d0,
        grp_fu_1181_p_din0,
        grp_fu_1181_p_din1,
        grp_fu_1181_p_dout0,
        grp_fu_1181_p_ce
);

parameter    ap_ST_fsm_pp0_stage0 = 9'd1;
parameter    ap_ST_fsm_pp0_stage1 = 9'd2;
parameter    ap_ST_fsm_pp0_stage2 = 9'd4;
parameter    ap_ST_fsm_pp0_stage3 = 9'd8;
parameter    ap_ST_fsm_pp0_stage4 = 9'd16;
parameter    ap_ST_fsm_pp0_stage5 = 9'd32;
parameter    ap_ST_fsm_pp0_stage6 = 9'd64;
parameter    ap_ST_fsm_pp0_stage7 = 9'd128;
parameter    ap_ST_fsm_pp0_stage8 = 9'd256;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_gmem_AWVALID;
input   m_axi_gmem_AWREADY;
output  [63:0] m_axi_gmem_AWADDR;
output  [0:0] m_axi_gmem_AWID;
output  [31:0] m_axi_gmem_AWLEN;
output  [2:0] m_axi_gmem_AWSIZE;
output  [1:0] m_axi_gmem_AWBURST;
output  [1:0] m_axi_gmem_AWLOCK;
output  [3:0] m_axi_gmem_AWCACHE;
output  [2:0] m_axi_gmem_AWPROT;
output  [3:0] m_axi_gmem_AWQOS;
output  [3:0] m_axi_gmem_AWREGION;
output  [0:0] m_axi_gmem_AWUSER;
output   m_axi_gmem_WVALID;
input   m_axi_gmem_WREADY;
output  [7:0] m_axi_gmem_WDATA;
output  [0:0] m_axi_gmem_WSTRB;
output   m_axi_gmem_WLAST;
output  [0:0] m_axi_gmem_WID;
output  [0:0] m_axi_gmem_WUSER;
output   m_axi_gmem_ARVALID;
input   m_axi_gmem_ARREADY;
output  [63:0] m_axi_gmem_ARADDR;
output  [0:0] m_axi_gmem_ARID;
output  [31:0] m_axi_gmem_ARLEN;
output  [2:0] m_axi_gmem_ARSIZE;
output  [1:0] m_axi_gmem_ARBURST;
output  [1:0] m_axi_gmem_ARLOCK;
output  [3:0] m_axi_gmem_ARCACHE;
output  [2:0] m_axi_gmem_ARPROT;
output  [3:0] m_axi_gmem_ARQOS;
output  [3:0] m_axi_gmem_ARREGION;
output  [0:0] m_axi_gmem_ARUSER;
input   m_axi_gmem_RVALID;
output   m_axi_gmem_RREADY;
input  [7:0] m_axi_gmem_RDATA;
input   m_axi_gmem_RLAST;
input  [0:0] m_axi_gmem_RID;
input  [10:0] m_axi_gmem_RFIFONUM;
input  [0:0] m_axi_gmem_RUSER;
input  [1:0] m_axi_gmem_RRESP;
input   m_axi_gmem_BVALID;
output   m_axi_gmem_BREADY;
input  [1:0] m_axi_gmem_BRESP;
input  [0:0] m_axi_gmem_BID;
input  [0:0] m_axi_gmem_BUSER;
input  [63:0] image_r;
output  [11:0] cnn_accel_ap_int_8_const_ap_uint_4_conv1_address0;
output   cnn_accel_ap_int_8_const_ap_uint_4_conv1_ce0;
output   cnn_accel_ap_int_8_const_ap_uint_4_conv1_we0;
output  [7:0] cnn_accel_ap_int_8_const_ap_uint_4_conv1_d0;
output  [11:0] cnn_accel_ap_int_8_const_ap_uint_4_conv1_1_address0;
output   cnn_accel_ap_int_8_const_ap_uint_4_conv1_1_ce0;
output   cnn_accel_ap_int_8_const_ap_uint_4_conv1_1_we0;
output  [7:0] cnn_accel_ap_int_8_const_ap_uint_4_conv1_1_d0;
output  [31:0] grp_fu_1181_p_din0;
output  [15:0] grp_fu_1181_p_din1;
input  [46:0] grp_fu_1181_p_dout0;
output   grp_fu_1181_p_ce;

reg ap_idle;
reg m_axi_gmem_ARVALID;
reg[63:0] m_axi_gmem_ARADDR;
reg m_axi_gmem_RREADY;
reg cnn_accel_ap_int_8_const_ap_uint_4_conv1_ce0;
reg cnn_accel_ap_int_8_const_ap_uint_4_conv1_we0;
reg cnn_accel_ap_int_8_const_ap_uint_4_conv1_1_ce0;
reg cnn_accel_ap_int_8_const_ap_uint_4_conv1_1_we0;

(* fsm_encoding = "none" *) reg   [8:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage8;
wire    ap_block_state9_pp0_stage8_iter0;
reg   [0:0] icmp_ln26_reg_1469;
reg    ap_block_state9_io;
reg   [0:0] icmp_ln26_reg_1469_pp0_iter1_reg;
reg   [0:0] and_ln35_2_reg_1639;
reg   [0:0] and_ln35_2_reg_1639_pp0_iter1_reg;
reg    ap_predicate_op304_read_state18;
reg    ap_block_state18_pp0_stage8_iter1;
wire    ap_block_state27_pp0_stage8_iter2;
reg    ap_block_pp0_stage8_subdone;
reg    ap_condition_exit_pp0_iter0_stage8;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [2:0] B_CONV1_V_address0;
reg    B_CONV1_V_ce0;
wire   [13:0] B_CONV1_V_q0;
wire   [2:0] W_CONV1_V_0_1_1_address0;
reg    W_CONV1_V_0_1_1_ce0;
wire   [7:0] W_CONV1_V_0_1_1_q0;
wire   [2:0] W_CONV1_V_0_0_0_address0;
reg    W_CONV1_V_0_0_0_ce0;
wire   [6:0] W_CONV1_V_0_0_0_q0;
wire   [2:0] W_CONV1_V_0_0_1_address0;
reg    W_CONV1_V_0_0_1_ce0;
wire   [7:0] W_CONV1_V_0_0_1_q0;
wire   [2:0] W_CONV1_V_0_0_2_address0;
reg    W_CONV1_V_0_0_2_ce0;
wire   [7:0] W_CONV1_V_0_0_2_q0;
wire   [2:0] W_CONV1_V_0_1_0_address0;
reg    W_CONV1_V_0_1_0_ce0;
wire   [7:0] W_CONV1_V_0_1_0_q0;
wire   [2:0] W_CONV1_V_0_1_2_address0;
reg    W_CONV1_V_0_1_2_ce0;
wire   [7:0] W_CONV1_V_0_1_2_q0;
wire   [2:0] W_CONV1_V_0_2_0_address0;
reg    W_CONV1_V_0_2_0_ce0;
wire   [7:0] W_CONV1_V_0_2_0_q0;
wire   [2:0] W_CONV1_V_0_2_1_address0;
reg    W_CONV1_V_0_2_1_ce0;
wire   [7:0] W_CONV1_V_0_2_1_q0;
wire   [2:0] W_CONV1_V_0_2_2_address0;
reg    W_CONV1_V_0_2_2_ce0;
wire  signed [7:0] W_CONV1_V_0_2_2_q0;
reg    gmem_blk_n_AR;
wire    ap_CS_fsm_pp0_stage4;
wire    ap_block_pp0_stage4;
reg   [0:0] and_ln35_reg_1591;
reg    gmem_blk_n_R;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_pp0_stage2;
wire    ap_CS_fsm_pp0_stage7;
wire    ap_block_pp0_stage7;
reg   [0:0] icmp_ln35_reg_1587;
wire    ap_CS_fsm_pp0_stage5;
wire    ap_block_pp0_stage5;
reg   [0:0] icmp_ln35_reg_1587_pp0_iter1_reg;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_pp0_stage1;
wire    ap_block_pp0_stage8;
reg   [0:0] cmp20_2_mid2_reg_1559;
wire    ap_block_pp0_stage0;
reg   [0:0] cmp20_2_mid2_reg_1559_pp0_iter1_reg;
wire    ap_CS_fsm_pp0_stage3;
wire    ap_block_pp0_stage3;
reg   [0:0] and_ln35_3_reg_1655;
reg   [0:0] and_ln35_3_reg_1655_pp0_iter1_reg;
wire    ap_CS_fsm_pp0_stage6;
wire    ap_block_pp0_stage6;
reg   [0:0] icmp_ln35_1_reg_1607;
reg   [0:0] icmp_ln35_1_reg_1607_pp0_iter1_reg;
reg   [0:0] cmp19_mid2_reg_1553;
reg   [0:0] cmp19_mid2_reg_1553_pp0_iter1_reg;
reg   [0:0] and_ln35_1_reg_1611;
reg   [0:0] and_ln35_1_reg_1611_pp0_iter1_reg;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state10_pp0_stage0_iter1;
reg    ap_predicate_op181_readreq_state10;
reg    ap_block_state10_io;
reg    ap_predicate_op318_read_state19;
reg    ap_block_state19_pp0_stage0_iter2;
wire    ap_block_state28_pp0_stage0_iter3;
reg    ap_block_pp0_stage0_11001;
reg   [4:0] y_2_reg_1461;
wire    ap_block_state2_pp0_stage1_iter0;
wire    ap_block_state11_pp0_stage1_iter1;
reg    ap_predicate_op207_readreq_state11;
reg    ap_block_state11_io;
reg    ap_predicate_op331_read_state20;
reg    ap_block_state20_pp0_stage1_iter2;
reg    ap_block_pp0_stage1_11001;
wire   [0:0] icmp_ln26_fu_566_p2;
reg   [0:0] icmp_ln26_reg_1469_pp0_iter2_reg;
reg   [4:0] ix_load_reg_1473;
wire   [0:0] exitcond_flatten196_fu_590_p2;
reg   [0:0] exitcond_flatten196_reg_1478;
wire   [4:0] select_ln26_fu_596_p3;
reg   [4:0] select_ln26_reg_1487;
wire   [3:0] select_ln26_1_fu_604_p3;
reg   [3:0] select_ln26_1_reg_1493;
wire   [0:0] xor_ln26_fu_646_p2;
reg   [0:0] xor_ln26_reg_1498;
wire   [0:0] and_ln26_2_fu_672_p2;
reg   [0:0] and_ln26_2_reg_1503;
wire   [4:0] indvars_iv_next91_dup_fu_678_p2;
reg   [4:0] indvars_iv_next91_dup_reg_1514;
wire   [9:0] add_ln41_fu_706_p2;
reg   [9:0] add_ln41_reg_1522;
wire   [6:0] trunc_ln41_1_fu_712_p1;
reg   [6:0] trunc_ln41_1_reg_1527;
wire   [0:0] trunc_ln41_mid2_fu_720_p3;
reg   [0:0] trunc_ln41_mid2_reg_1532;
reg   [0:0] trunc_ln41_mid2_reg_1532_pp0_iter1_reg;
reg   [0:0] trunc_ln41_mid2_reg_1532_pp0_iter2_reg;
wire   [10:0] add_ln36_fu_805_p2;
reg   [10:0] add_ln36_reg_1536;
wire    ap_block_state3_pp0_stage2_iter0;
reg    ap_predicate_op217_read_state12;
reg    ap_block_state12_pp0_stage2_iter1;
reg    ap_predicate_op224_readreq_state12;
reg    ap_block_state12_io;
wire    ap_block_state21_pp0_stage2_iter2;
reg    ap_block_pp0_stage2_11001;
wire   [10:0] add_ln36_2_fu_816_p2;
reg   [10:0] add_ln36_2_reg_1541;
wire   [4:0] x_mid2_fu_842_p3;
reg   [4:0] x_mid2_reg_1546;
wire   [0:0] cmp19_mid2_fu_854_p3;
wire   [0:0] cmp20_2_mid2_fu_904_p3;
reg   [0:0] cmp20_2_mid2_reg_1559_pp0_iter2_reg;
wire   [10:0] add_ln36_12_fu_911_p2;
reg   [10:0] add_ln36_12_reg_1565;
wire   [63:0] add_ln36_1_mid2_fu_922_p3;
reg   [63:0] add_ln36_1_mid2_reg_1570;
wire   [10:0] add_ln36_14_fu_929_p2;
reg   [10:0] add_ln36_14_reg_1577;
wire   [11:0] add_ln41_1_fu_964_p2;
reg   [11:0] add_ln41_1_reg_1582;
reg   [11:0] add_ln41_1_reg_1582_pp0_iter1_reg;
reg   [11:0] add_ln41_1_reg_1582_pp0_iter2_reg;
wire   [0:0] icmp_ln35_fu_1033_p2;
wire    ap_block_state4_pp0_stage3_iter0;
reg    ap_predicate_op228_read_state13;
reg    ap_block_state13_pp0_stage3_iter1;
reg    ap_predicate_op235_readreq_state13;
reg    ap_block_state13_io;
wire    ap_block_state22_pp0_stage3_iter2;
reg    ap_block_pp0_stage3_11001;
wire   [0:0] and_ln35_fu_1039_p2;
reg   [0:0] and_ln35_reg_1591_pp0_iter1_reg;
reg   [63:0] gmem_addr_reg_1595;
reg   [63:0] gmem_addr_1_reg_1601;
wire   [0:0] icmp_ln35_1_fu_1077_p2;
wire   [0:0] and_ln35_1_fu_1083_p2;
reg   [63:0] gmem_addr_2_reg_1615;
reg   [63:0] gmem_addr_3_reg_1621;
reg   [63:0] gmem_addr_4_reg_1627;
reg   [63:0] gmem_addr_5_reg_1633;
wire   [0:0] and_ln35_2_fu_1133_p2;
reg   [63:0] gmem_addr_6_reg_1643;
reg   [63:0] gmem_addr_7_reg_1649;
wire   [0:0] and_ln35_3_fu_1162_p2;
reg   [0:0] and_ln35_3_reg_1655_pp0_iter2_reg;
reg   [63:0] gmem_addr_8_reg_1659;
wire   [63:0] zext_ln26_fu_1184_p1;
reg   [63:0] zext_ln26_reg_1665;
reg  signed [13:0] B_CONV1_V_load_reg_1715;
reg  signed [7:0] W_CONV1_V_0_1_1_load_reg_1720;
reg   [6:0] W_CONV1_V_0_0_0_load_reg_1725;
reg  signed [7:0] W_CONV1_V_0_0_1_load_reg_1730;
reg  signed [7:0] W_CONV1_V_0_0_2_load_reg_1735;
reg  signed [7:0] W_CONV1_V_0_1_0_load_reg_1740;
reg  signed [7:0] W_CONV1_V_0_1_2_load_reg_1745;
reg  signed [7:0] W_CONV1_V_0_2_0_load_reg_1750;
reg  signed [7:0] W_CONV1_V_0_2_1_load_reg_1755;
reg  signed [7:0] pix_V_reg_1760;
reg  signed [7:0] pix_V_1_reg_1775;
wire    ap_block_state5_pp0_stage4_iter0;
reg    ap_predicate_op161_readreq_state5;
reg    ap_block_state5_io;
reg    ap_predicate_op240_read_state14;
reg    ap_block_state14_pp0_stage4_iter1;
wire    ap_block_state23_pp0_stage4_iter2;
reg    ap_block_pp0_stage4_11001;
reg  signed [7:0] pix_V_2_reg_1790;
wire  signed [15:0] sext_ln26_fu_1208_p1;
wire    ap_block_state6_pp0_stage5_iter0;
reg    ap_predicate_op163_readreq_state6;
reg    ap_block_state6_io;
reg    ap_predicate_op256_read_state15;
reg    ap_block_state15_pp0_stage5_iter1;
wire    ap_block_state24_pp0_stage5_iter2;
reg    ap_block_pp0_stage5_11001;
reg  signed [7:0] pix_V_3_reg_1811;
wire    ap_block_state7_pp0_stage6_iter0;
reg    ap_predicate_op166_readreq_state7;
reg    ap_block_state7_io;
reg    ap_block_state16_pp0_stage6_iter1;
wire    ap_block_state25_pp0_stage6_iter2;
reg    ap_block_pp0_stage6_11001;
reg  signed [7:0] pix_V_4_reg_1826;
wire    ap_block_state8_pp0_stage7_iter0;
reg    ap_predicate_op170_readreq_state8;
reg    ap_block_state8_io;
reg    ap_predicate_op289_read_state17;
reg    ap_block_state17_pp0_stage7_iter1;
wire    ap_block_state26_pp0_stage7_iter2;
reg    ap_block_pp0_stage7_11001;
wire  signed [16:0] sext_ln30_fu_1226_p1;
reg  signed [7:0] pix_V_5_reg_1847;
reg    ap_block_pp0_stage8_11001;
reg  signed [7:0] pix_V_6_reg_1862;
reg  signed [7:0] pix_V_7_reg_1882;
wire  signed [17:0] grp_fu_1374_p3;
reg  signed [7:0] pix_V_8_reg_1908;
wire  signed [17:0] grp_fu_1409_p3;
wire   [0:0] icmp_ln1039_fu_1262_p2;
reg   [0:0] icmp_ln1039_reg_1928;
wire   [46:0] zext_ln8_fu_1272_p1;
reg   [46:0] scaled_V_reg_1939;
wire   [7:0] select_ln1039_1_fu_1325_p3;
reg   [7:0] select_ln1039_1_reg_1944;
reg    ap_enable_reg_pp0_iter0_reg;
reg    ap_block_pp0_stage0_subdone;
reg   [15:0] ap_phi_mux_acc_V_1_phi_fu_439_p4;
wire  signed [15:0] grp_fu_1338_p3;
reg   [15:0] ap_phi_reg_pp0_iter1_acc_V_1_reg_436;
wire   [15:0] ap_phi_reg_pp0_iter0_acc_V_1_reg_436;
reg  signed [15:0] ap_phi_mux_acc_V_3_phi_fu_449_p4;
wire   [15:0] grp_fu_1347_p3;
reg   [15:0] ap_phi_reg_pp0_iter1_acc_V_3_reg_446;
wire   [15:0] ap_phi_reg_pp0_iter0_acc_V_3_reg_446;
reg  signed [16:0] ap_phi_mux_acc_V_5_phi_fu_459_p4;
wire  signed [16:0] grp_fu_1356_p3;
reg   [16:0] ap_phi_reg_pp0_iter1_acc_V_5_reg_456;
wire   [16:0] ap_phi_reg_pp0_iter0_acc_V_5_reg_456;
reg  signed [16:0] ap_phi_mux_acc_V_7_phi_fu_469_p4;
wire  signed [16:0] grp_fu_1365_p3;
reg   [16:0] ap_phi_reg_pp0_iter2_acc_V_7_reg_466;
wire   [16:0] ap_phi_reg_pp0_iter0_acc_V_7_reg_466;
reg   [16:0] ap_phi_reg_pp0_iter1_acc_V_7_reg_466;
reg  signed [17:0] ap_phi_mux_acc_V_10_phi_fu_479_p4;
wire  signed [17:0] grp_fu_1382_p3;
reg   [17:0] ap_phi_reg_pp0_iter2_acc_V_10_reg_476;
wire   [17:0] ap_phi_reg_pp0_iter0_acc_V_10_reg_476;
reg   [17:0] ap_phi_reg_pp0_iter1_acc_V_10_reg_476;
reg  signed [17:0] ap_phi_mux_acc_V_12_phi_fu_489_p4;
wire  signed [17:0] grp_fu_1391_p3;
reg   [17:0] ap_phi_reg_pp0_iter2_acc_V_12_reg_486;
wire   [17:0] ap_phi_reg_pp0_iter0_acc_V_12_reg_486;
reg   [17:0] ap_phi_reg_pp0_iter1_acc_V_12_reg_486;
reg  signed [17:0] ap_phi_mux_acc_V_14_phi_fu_500_p4;
wire  signed [17:0] grp_fu_1400_p3;
reg   [17:0] ap_phi_reg_pp0_iter2_acc_V_14_reg_497;
wire   [17:0] ap_phi_reg_pp0_iter0_acc_V_14_reg_497;
reg   [17:0] ap_phi_reg_pp0_iter1_acc_V_14_reg_497;
wire  signed [17:0] ap_phi_reg_pp0_iter0_acc_V_16_reg_508;
reg  signed [17:0] ap_phi_reg_pp0_iter1_acc_V_16_reg_508;
reg  signed [17:0] ap_phi_reg_pp0_iter2_acc_V_16_reg_508;
wire   [63:0] zext_ln41_4_fu_1333_p1;
wire   [63:0] add_ln36_3_fu_1044_p2;
wire   [63:0] add_ln36_4_fu_1056_p2;
wire   [63:0] add_ln36_5_fu_1088_p2;
wire   [63:0] add_ln36_6_fu_1100_p2;
wire   [63:0] add_ln36_7_fu_1111_p2;
wire   [63:0] add_ln36_8_fu_1122_p2;
wire   [63:0] add_ln36_9_fu_1138_p2;
wire   [63:0] add_ln36_10_fu_1150_p2;
wire   [63:0] add_ln36_11_fu_1167_p2;
reg   [4:0] ix_fu_146;
wire   [4:0] add_ln34_1_fu_1068_p2;
wire    ap_loop_init;
reg   [4:0] y_fu_150;
wire   [4:0] y_mid2_fu_955_p3;
reg   [9:0] indvar_flatten_fu_154;
wire   [9:0] indvar_flatten_next_fu_734_p3;
reg   [3:0] oc_fu_158;
reg   [12:0] indvar_flatten63_fu_162;
wire   [12:0] add_ln26_1_fu_572_p2;
wire   [3:0] add_ln26_fu_584_p2;
wire   [7:0] tmp_fu_612_p3;
wire   [4:0] tmp_1_fu_624_p3;
wire   [8:0] zext_ln41_fu_620_p1;
wire   [8:0] zext_ln41_1_fu_632_p1;
wire   [8:0] sub_ln41_fu_636_p2;
wire   [3:0] lshr_ln_fu_552_p4;
wire   [0:0] trunc_ln41_fu_562_p1;
wire   [0:0] icmp_ln28_fu_666_p2;
wire   [3:0] lshr_ln41_mid1_fu_684_p4;
wire   [3:0] select_ln26_5_fu_652_p3;
wire   [3:0] zext_ln41_mid2_fu_694_p3;
wire  signed [9:0] sext_ln26_9_fu_642_p1;
wire   [9:0] zext_ln41_2_fu_702_p1;
wire   [0:0] trunc_ln41_2_fu_716_p1;
wire   [0:0] and_ln26_1_fu_660_p2;
wire   [9:0] indvar_flatten_op_fu_728_p2;
wire   [9:0] p_shl_fu_762_p3;
wire   [6:0] p_shl1_fu_773_p3;
wire   [10:0] p_shl_cast_fu_769_p1;
wire   [10:0] p_shl1_cast_fu_780_p1;
wire  signed [10:0] empty_fu_784_p2;
wire   [4:0] indvars_iv_next91_fu_794_p2;
wire  signed [63:0] p_cast_fu_790_p1;
wire   [0:0] cmp19_fu_757_p2;
wire   [0:0] cmp20_2_fu_799_p2;
wire   [63:0] add_ln36_1_fu_811_p2;
wire   [0:0] empty_42_fu_838_p2;
wire   [0:0] cmp19_mid1_fu_849_p2;
wire   [0:0] and_ln26_fu_822_p2;
wire   [9:0] p_shl_mid1_fu_861_p3;
wire   [6:0] p_shl1_mid1_fu_872_p3;
wire   [10:0] p_shl_cast_mid1_fu_868_p1;
wire   [10:0] p_shl1_cast_mid1_fu_879_p1;
wire  signed [10:0] p_mid1_fu_883_p2;
wire   [4:0] indvars_iv_next91_mid1_fu_893_p2;
wire   [0:0] cmp20_2_mid1_fu_898_p2;
wire   [0:0] or_ln26_fu_827_p2;
wire  signed [63:0] p_cast_mid1_fu_889_p1;
wire   [63:0] add_ln36_13_fu_917_p2;
wire   [63:0] select_ln26_3_fu_832_p3;
wire   [11:0] p_shl2_fu_935_p3;
wire   [11:0] p_shl3_fu_942_p3;
wire   [11:0] sub_ln41_1_fu_949_p2;
wire   [11:0] zext_ln41_3_fu_960_p1;
wire   [10:0] select_ln26_2_fu_975_p3;
wire   [10:0] add_ln36_mid2_v_fu_987_p3;
wire  signed [63:0] add_ln36_mid2_v_cast_fu_993_p1;
wire   [10:0] select_ln26_4_fu_981_p3;
wire   [10:0] add_ln36_2_mid2_v_fu_1002_p3;
wire  signed [63:0] add_ln36_2_mid2_v_cast_fu_1008_p1;
wire   [5:0] zext_ln28_1_fu_1020_p1;
wire  signed [5:0] add_ln34_fu_1023_p2;
wire  signed [63:0] sext_ln35_fu_1029_p1;
wire   [63:0] add_ln36_mid2_fu_997_p2;
wire   [63:0] zext_ln28_fu_1017_p1;
wire   [63:0] zext_ln35_fu_1073_p1;
wire   [63:0] add_ln36_2_mid2_fu_1012_p2;
wire  signed [31:0] sext_ln8_fu_1268_p1;
wire   [46:0] scaled_V_1_fu_1282_p2;
wire   [15:0] tmp_2_fu_1287_p4;
wire   [0:0] icmp_ln1035_fu_1297_p2;
wire   [0:0] or_ln1039_fu_1320_p2;
wire   [7:0] select_ln1039_fu_1313_p3;
wire   [7:0] trunc_ln2_fu_1303_p4;
wire   [6:0] grp_fu_1338_p1;
reg    grp_fu_1276_ce;
reg    grp_fu_1338_ce;
reg    grp_fu_1347_ce;
reg    grp_fu_1356_ce;
reg    grp_fu_1365_ce;
reg    grp_fu_1374_ce;
reg    grp_fu_1382_ce;
reg    grp_fu_1391_ce;
reg    grp_fu_1400_ce;
reg    grp_fu_1409_ce;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_condition_exit_pp0_iter2_stage0;
reg    ap_idle_pp0_0to1;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg   [8:0] ap_NS_fsm;
reg    ap_idle_pp0_1to3;
reg    ap_block_pp0_stage1_subdone;
reg    ap_block_pp0_stage2_subdone;
reg    ap_block_pp0_stage3_subdone;
reg    ap_block_pp0_stage4_subdone;
reg    ap_block_pp0_stage5_subdone;
reg    ap_block_pp0_stage6_subdone;
reg    ap_block_pp0_stage7_subdone;
wire    ap_enable_pp0;
wire    ap_start_int;
wire   [14:0] grp_fu_1338_p10;
reg    ap_condition_873;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 9'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 ap_done_reg = 1'b0;
end

cnn_accel_conv1_layer_B_CONV1_V_ROM_AUTO_1R #(
    .DataWidth( 14 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
B_CONV1_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(B_CONV1_V_address0),
    .ce0(B_CONV1_V_ce0),
    .q0(B_CONV1_V_q0)
);

cnn_accel_conv1_layer_W_CONV1_V_0_1_1_ROM_AUTO_1R #(
    .DataWidth( 8 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
W_CONV1_V_0_1_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(W_CONV1_V_0_1_1_address0),
    .ce0(W_CONV1_V_0_1_1_ce0),
    .q0(W_CONV1_V_0_1_1_q0)
);

cnn_accel_conv1_layer_W_CONV1_V_0_0_0_ROM_AUTO_1R #(
    .DataWidth( 7 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
W_CONV1_V_0_0_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(W_CONV1_V_0_0_0_address0),
    .ce0(W_CONV1_V_0_0_0_ce0),
    .q0(W_CONV1_V_0_0_0_q0)
);

cnn_accel_conv1_layer_W_CONV1_V_0_0_1_ROM_AUTO_1R #(
    .DataWidth( 8 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
W_CONV1_V_0_0_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(W_CONV1_V_0_0_1_address0),
    .ce0(W_CONV1_V_0_0_1_ce0),
    .q0(W_CONV1_V_0_0_1_q0)
);

cnn_accel_conv1_layer_W_CONV1_V_0_0_2_ROM_AUTO_1R #(
    .DataWidth( 8 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
W_CONV1_V_0_0_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(W_CONV1_V_0_0_2_address0),
    .ce0(W_CONV1_V_0_0_2_ce0),
    .q0(W_CONV1_V_0_0_2_q0)
);

cnn_accel_conv1_layer_W_CONV1_V_0_1_0_ROM_AUTO_1R #(
    .DataWidth( 8 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
W_CONV1_V_0_1_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(W_CONV1_V_0_1_0_address0),
    .ce0(W_CONV1_V_0_1_0_ce0),
    .q0(W_CONV1_V_0_1_0_q0)
);

cnn_accel_conv1_layer_W_CONV1_V_0_1_2_ROM_AUTO_1R #(
    .DataWidth( 8 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
W_CONV1_V_0_1_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(W_CONV1_V_0_1_2_address0),
    .ce0(W_CONV1_V_0_1_2_ce0),
    .q0(W_CONV1_V_0_1_2_q0)
);

cnn_accel_conv1_layer_W_CONV1_V_0_2_0_ROM_AUTO_1R #(
    .DataWidth( 8 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
W_CONV1_V_0_2_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(W_CONV1_V_0_2_0_address0),
    .ce0(W_CONV1_V_0_2_0_ce0),
    .q0(W_CONV1_V_0_2_0_q0)
);

cnn_accel_conv1_layer_W_CONV1_V_0_2_1_ROM_AUTO_1R #(
    .DataWidth( 8 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
W_CONV1_V_0_2_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(W_CONV1_V_0_2_1_address0),
    .ce0(W_CONV1_V_0_2_1_ce0),
    .q0(W_CONV1_V_0_2_1_q0)
);

cnn_accel_conv1_layer_W_CONV1_V_0_2_2_ROM_AUTO_1R #(
    .DataWidth( 8 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
W_CONV1_V_0_2_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(W_CONV1_V_0_2_2_address0),
    .ce0(W_CONV1_V_0_2_2_ce0),
    .q0(W_CONV1_V_0_2_2_q0)
);

cnn_accel_mac_muladd_8s_7ns_14s_16_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 7 ),
    .din2_WIDTH( 14 ),
    .dout_WIDTH( 16 ))
mac_muladd_8s_7ns_14s_16_4_1_U2(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(pix_V_reg_1760),
    .din1(grp_fu_1338_p1),
    .din2(B_CONV1_V_load_reg_1715),
    .ce(grp_fu_1338_ce),
    .dout(grp_fu_1338_p3)
);

cnn_accel_mac_muladd_8s_8s_16ns_16_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
mac_muladd_8s_8s_16ns_16_4_1_U3(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(pix_V_1_reg_1775),
    .din1(W_CONV1_V_0_0_1_load_reg_1730),
    .din2(ap_phi_mux_acc_V_1_phi_fu_439_p4),
    .ce(grp_fu_1347_ce),
    .dout(grp_fu_1347_p3)
);

cnn_accel_mac_muladd_8s_8s_16s_17_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 17 ))
mac_muladd_8s_8s_16s_17_4_1_U4(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(pix_V_2_reg_1790),
    .din1(W_CONV1_V_0_0_2_load_reg_1735),
    .din2(ap_phi_mux_acc_V_3_phi_fu_449_p4),
    .ce(grp_fu_1356_ce),
    .dout(grp_fu_1356_p3)
);

cnn_accel_mac_muladd_8s_8s_17s_17_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 17 ),
    .dout_WIDTH( 17 ))
mac_muladd_8s_8s_17s_17_4_1_U5(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(pix_V_3_reg_1811),
    .din1(W_CONV1_V_0_1_0_load_reg_1740),
    .din2(ap_phi_mux_acc_V_5_phi_fu_459_p4),
    .ce(grp_fu_1365_ce),
    .dout(grp_fu_1365_p3)
);

cnn_accel_mac_muladd_8s_8s_17s_18_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 17 ),
    .dout_WIDTH( 18 ))
mac_muladd_8s_8s_17s_18_4_1_U6(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(pix_V_4_reg_1826),
    .din1(W_CONV1_V_0_1_1_load_reg_1720),
    .din2(ap_phi_mux_acc_V_7_phi_fu_469_p4),
    .ce(grp_fu_1374_ce),
    .dout(grp_fu_1374_p3)
);

cnn_accel_mac_muladd_8s_8s_18s_18_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 18 ),
    .dout_WIDTH( 18 ))
mac_muladd_8s_8s_18s_18_4_1_U7(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(pix_V_5_reg_1847),
    .din1(W_CONV1_V_0_1_2_load_reg_1745),
    .din2(grp_fu_1374_p3),
    .ce(grp_fu_1382_ce),
    .dout(grp_fu_1382_p3)
);

cnn_accel_mac_muladd_8s_8s_18s_18_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 18 ),
    .dout_WIDTH( 18 ))
mac_muladd_8s_8s_18s_18_4_1_U8(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(pix_V_6_reg_1862),
    .din1(W_CONV1_V_0_2_0_load_reg_1750),
    .din2(ap_phi_mux_acc_V_10_phi_fu_479_p4),
    .ce(grp_fu_1391_ce),
    .dout(grp_fu_1391_p3)
);

cnn_accel_mac_muladd_8s_8s_18s_18_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 18 ),
    .dout_WIDTH( 18 ))
mac_muladd_8s_8s_18s_18_4_1_U9(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(pix_V_7_reg_1882),
    .din1(W_CONV1_V_0_2_1_load_reg_1755),
    .din2(ap_phi_mux_acc_V_12_phi_fu_489_p4),
    .ce(grp_fu_1400_ce),
    .dout(grp_fu_1400_p3)
);

cnn_accel_mac_muladd_8s_8s_18s_18_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 18 ),
    .dout_WIDTH( 18 ))
mac_muladd_8s_8s_18s_18_4_1_U10(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(pix_V_8_reg_1908),
    .din1(W_CONV1_V_0_2_2_q0),
    .din2(ap_phi_mux_acc_V_14_phi_fu_500_p4),
    .ce(grp_fu_1409_ce),
    .dout(grp_fu_1409_p3)
);

cnn_accel_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage8),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage8)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage8) & (1'b0 == ap_block_pp0_stage8_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage8) & (1'b0 == ap_block_pp0_stage8_subdone))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter3 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage8) & (1'b0 == ap_block_pp0_stage8_subdone))) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter2_stage0) & (ap_idle_pp0_0to1 == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage8) & (1'b0 == ap_block_pp0_stage8_11001))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter2_stage0) & (ap_idle_pp0_0to1 == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage8) & (1'b0 == ap_block_pp0_stage8_11001))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5) & (1'b0 == ap_block_pp0_stage5_11001) & (icmp_ln26_reg_1469_pp0_iter1_reg == 1'd0) & (1'd0 == and_ln35_reg_1591_pp0_iter1_reg))) begin
        ap_phi_reg_pp0_iter1_acc_V_1_reg_436 <= sext_ln26_fu_1208_p1;
    end else if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage8) & (1'b0 == ap_block_pp0_stage8_11001))) begin
        ap_phi_reg_pp0_iter1_acc_V_1_reg_436 <= ap_phi_reg_pp0_iter0_acc_V_1_reg_436;
    end
end

always @ (posedge ap_clk) begin
    if (((cmp19_mid2_reg_1553_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6) & (1'b0 == ap_block_pp0_stage6_11001) & (icmp_ln26_reg_1469_pp0_iter1_reg == 1'd0))) begin
        ap_phi_reg_pp0_iter1_acc_V_3_reg_446 <= ap_phi_mux_acc_V_1_phi_fu_439_p4;
    end else if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage8) & (1'b0 == ap_block_pp0_stage8_11001))) begin
        ap_phi_reg_pp0_iter1_acc_V_3_reg_446 <= ap_phi_reg_pp0_iter0_acc_V_3_reg_446;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7) & (1'b0 == ap_block_pp0_stage7_11001) & (icmp_ln26_reg_1469_pp0_iter1_reg == 1'd0) & (1'd0 == and_ln35_1_reg_1611_pp0_iter1_reg))) begin
        ap_phi_reg_pp0_iter1_acc_V_5_reg_456 <= sext_ln30_fu_1226_p1;
    end else if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage8) & (1'b0 == ap_block_pp0_stage8_11001))) begin
        ap_phi_reg_pp0_iter1_acc_V_5_reg_456 <= ap_phi_reg_pp0_iter0_acc_V_5_reg_456;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln35_1_reg_1607_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln26_reg_1469_pp0_iter1_reg == 1'd0))) begin
        ap_phi_reg_pp0_iter2_acc_V_10_reg_476 <= grp_fu_1374_p3;
    end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage8) & (1'b0 == ap_block_pp0_stage8_11001))) begin
        ap_phi_reg_pp0_iter2_acc_V_10_reg_476 <= ap_phi_reg_pp0_iter1_acc_V_10_reg_476;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln26_reg_1469_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001) & (1'd0 == and_ln35_2_reg_1639_pp0_iter1_reg))) begin
        ap_phi_reg_pp0_iter2_acc_V_12_reg_486 <= ap_phi_mux_acc_V_10_phi_fu_479_p4;
    end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage8) & (1'b0 == ap_block_pp0_stage8_11001))) begin
        ap_phi_reg_pp0_iter2_acc_V_12_reg_486 <= ap_phi_reg_pp0_iter1_acc_V_12_reg_486;
    end
end

always @ (posedge ap_clk) begin
    if (((cmp20_2_mid2_reg_1559_pp0_iter2_reg == 1'd0) & (icmp_ln26_reg_1469_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001))) begin
        ap_phi_reg_pp0_iter2_acc_V_14_reg_497 <= ap_phi_mux_acc_V_12_phi_fu_489_p4;
    end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage8) & (1'b0 == ap_block_pp0_stage8_11001))) begin
        ap_phi_reg_pp0_iter2_acc_V_14_reg_497 <= ap_phi_reg_pp0_iter1_acc_V_14_reg_497;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln26_reg_1469_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (1'b0 == ap_block_pp0_stage4_11001) & (1'd0 == and_ln35_3_reg_1655_pp0_iter2_reg))) begin
        ap_phi_reg_pp0_iter2_acc_V_16_reg_508 <= ap_phi_mux_acc_V_14_phi_fu_500_p4;
    end else if (((icmp_ln26_reg_1469_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5) & (1'b0 == ap_block_pp0_stage5_11001) & (1'd1 == and_ln35_3_reg_1655_pp0_iter2_reg))) begin
        ap_phi_reg_pp0_iter2_acc_V_16_reg_508 <= grp_fu_1409_p3;
    end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage8) & (1'b0 == ap_block_pp0_stage8_11001))) begin
        ap_phi_reg_pp0_iter2_acc_V_16_reg_508 <= ap_phi_reg_pp0_iter1_acc_V_16_reg_508;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_873)) begin
        if (((icmp_ln35_reg_1587_pp0_iter1_reg == 1'd0) & (icmp_ln26_reg_1469_pp0_iter1_reg == 1'd0))) begin
            ap_phi_reg_pp0_iter2_acc_V_7_reg_466 <= ap_phi_mux_acc_V_5_phi_fu_459_p4;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_acc_V_7_reg_466 <= ap_phi_reg_pp0_iter1_acc_V_7_reg_466;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1))) begin
        indvar_flatten63_fu_162 <= 13'd0;
    end else if (((icmp_ln26_fu_566_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        indvar_flatten63_fu_162 <= add_ln26_1_fu_572_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1))) begin
        indvar_flatten_fu_154 <= 10'd0;
    end else if (((icmp_ln26_fu_566_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        indvar_flatten_fu_154 <= indvar_flatten_next_fu_734_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1))) begin
        ix_fu_146 <= 5'd0;
    end else if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001) & (icmp_ln26_reg_1469 == 1'd0))) begin
        ix_fu_146 <= add_ln34_1_fu_1068_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1))) begin
        oc_fu_158 <= 4'd0;
    end else if (((icmp_ln26_fu_566_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        oc_fu_158 <= select_ln26_1_fu_604_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1))) begin
        y_fu_150 <= 5'd0;
    end else if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001) & (icmp_ln26_reg_1469 == 1'd0))) begin
        y_fu_150 <= y_mid2_fu_955_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001) & (icmp_ln26_reg_1469_pp0_iter1_reg == 1'd0))) begin
        B_CONV1_V_load_reg_1715 <= B_CONV1_V_q0;
        W_CONV1_V_0_0_0_load_reg_1725 <= W_CONV1_V_0_0_0_q0;
        W_CONV1_V_0_0_1_load_reg_1730 <= W_CONV1_V_0_0_1_q0;
        W_CONV1_V_0_0_2_load_reg_1735 <= W_CONV1_V_0_0_2_q0;
        W_CONV1_V_0_1_0_load_reg_1740 <= W_CONV1_V_0_1_0_q0;
        W_CONV1_V_0_1_1_load_reg_1720 <= W_CONV1_V_0_1_1_q0;
        W_CONV1_V_0_1_2_load_reg_1745 <= W_CONV1_V_0_1_2_q0;
        W_CONV1_V_0_2_0_load_reg_1750 <= W_CONV1_V_0_2_0_q0;
        W_CONV1_V_0_2_1_load_reg_1755 <= W_CONV1_V_0_2_1_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001) & (1'd1 == and_ln26_2_reg_1503) & (icmp_ln26_reg_1469 == 1'd0))) begin
        add_ln36_12_reg_1565[10 : 2] <= add_ln36_12_fu_911_p2[10 : 2];
        add_ln36_14_reg_1577[10 : 2] <= add_ln36_14_fu_929_p2[10 : 2];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001) & (icmp_ln26_reg_1469 == 1'd0))) begin
        add_ln36_1_mid2_reg_1570 <= add_ln36_1_mid2_fu_922_p3;
        add_ln41_1_reg_1582 <= add_ln41_1_fu_964_p2;
        cmp19_mid2_reg_1553 <= cmp19_mid2_fu_854_p3;
        cmp20_2_mid2_reg_1559 <= cmp20_2_mid2_fu_904_p3;
        x_mid2_reg_1546 <= x_mid2_fu_842_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_flatten196_reg_1478 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001) & (1'd0 == and_ln26_2_reg_1503))) begin
        add_ln36_2_reg_1541[10 : 2] <= add_ln36_2_fu_816_p2[10 : 2];
        add_ln36_reg_1536[10 : 2] <= add_ln36_fu_805_p2[10 : 2];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001))) begin
        add_ln41_1_reg_1582_pp0_iter1_reg <= add_ln41_1_reg_1582;
        add_ln41_1_reg_1582_pp0_iter2_reg <= add_ln41_1_reg_1582_pp0_iter1_reg;
        cmp19_mid2_reg_1553_pp0_iter1_reg <= cmp19_mid2_reg_1553;
        cmp20_2_mid2_reg_1559_pp0_iter1_reg <= cmp20_2_mid2_reg_1559;
        cmp20_2_mid2_reg_1559_pp0_iter2_reg <= cmp20_2_mid2_reg_1559_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln26_fu_566_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        add_ln41_reg_1522 <= add_ln41_fu_706_p2;
        and_ln26_2_reg_1503 <= and_ln26_2_fu_672_p2;
        exitcond_flatten196_reg_1478 <= exitcond_flatten196_fu_590_p2;
        indvars_iv_next91_dup_reg_1514 <= indvars_iv_next91_dup_fu_678_p2;
        ix_load_reg_1473 <= ix_fu_146;
        select_ln26_1_reg_1493 <= select_ln26_1_fu_604_p3;
        select_ln26_reg_1487 <= select_ln26_fu_596_p3;
        trunc_ln41_1_reg_1527 <= trunc_ln41_1_fu_712_p1;
        trunc_ln41_mid2_reg_1532 <= trunc_ln41_mid2_fu_720_p3;
        xor_ln26_reg_1498 <= xor_ln26_fu_646_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001) & (icmp_ln26_reg_1469 == 1'd0))) begin
        and_ln35_1_reg_1611 <= and_ln35_1_fu_1083_p2;
        and_ln35_2_reg_1639 <= and_ln35_2_fu_1133_p2;
        and_ln35_3_reg_1655 <= and_ln35_3_fu_1162_p2;
        and_ln35_reg_1591 <= and_ln35_fu_1039_p2;
        gmem_addr_4_reg_1627 <= add_ln36_7_fu_1111_p2;
        icmp_ln35_1_reg_1607 <= icmp_ln35_1_fu_1077_p2;
        icmp_ln35_reg_1587 <= icmp_ln35_fu_1033_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001))) begin
        and_ln35_1_reg_1611_pp0_iter1_reg <= and_ln35_1_reg_1611;
        and_ln35_2_reg_1639_pp0_iter1_reg <= and_ln35_2_reg_1639;
        and_ln35_3_reg_1655_pp0_iter1_reg <= and_ln35_3_reg_1655;
        and_ln35_3_reg_1655_pp0_iter2_reg <= and_ln35_3_reg_1655_pp0_iter1_reg;
        and_ln35_reg_1591_pp0_iter1_reg <= and_ln35_reg_1591;
        icmp_ln35_1_reg_1607_pp0_iter1_reg <= icmp_ln35_1_reg_1607;
        icmp_ln35_reg_1587_pp0_iter1_reg <= icmp_ln35_reg_1587;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage8) & (1'b0 == ap_block_pp0_stage8_11001))) begin
        ap_phi_reg_pp0_iter1_acc_V_10_reg_476 <= ap_phi_reg_pp0_iter0_acc_V_10_reg_476;
        ap_phi_reg_pp0_iter1_acc_V_12_reg_486 <= ap_phi_reg_pp0_iter0_acc_V_12_reg_486;
        ap_phi_reg_pp0_iter1_acc_V_14_reg_497 <= ap_phi_reg_pp0_iter0_acc_V_14_reg_497;
        ap_phi_reg_pp0_iter1_acc_V_16_reg_508 <= ap_phi_reg_pp0_iter0_acc_V_16_reg_508;
        ap_phi_reg_pp0_iter1_acc_V_7_reg_466 <= ap_phi_reg_pp0_iter0_acc_V_7_reg_466;
    end
end

always @ (posedge ap_clk) begin
    if (((cmp19_mid2_reg_1553 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001) & (icmp_ln26_reg_1469 == 1'd0))) begin
        gmem_addr_1_reg_1601 <= add_ln36_4_fu_1056_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001) & (1'd1 == and_ln35_1_fu_1083_p2) & (icmp_ln26_reg_1469 == 1'd0))) begin
        gmem_addr_2_reg_1615 <= add_ln36_5_fu_1088_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln35_fu_1033_p2 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001) & (icmp_ln26_reg_1469 == 1'd0))) begin
        gmem_addr_3_reg_1621 <= add_ln36_6_fu_1100_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln35_1_fu_1077_p2 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001) & (icmp_ln26_reg_1469 == 1'd0))) begin
        gmem_addr_5_reg_1633 <= add_ln36_8_fu_1122_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001) & (1'd1 == and_ln35_2_fu_1133_p2) & (icmp_ln26_reg_1469 == 1'd0))) begin
        gmem_addr_6_reg_1643 <= add_ln36_9_fu_1138_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((cmp20_2_mid2_reg_1559 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001) & (icmp_ln26_reg_1469 == 1'd0))) begin
        gmem_addr_7_reg_1649 <= add_ln36_10_fu_1150_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001) & (1'd1 == and_ln35_3_fu_1162_p2) & (icmp_ln26_reg_1469 == 1'd0))) begin
        gmem_addr_8_reg_1659 <= add_ln36_11_fu_1167_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001) & (1'd1 == and_ln35_fu_1039_p2) & (icmp_ln26_reg_1469 == 1'd0))) begin
        gmem_addr_reg_1595 <= add_ln36_3_fu_1044_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage6) & (1'b0 == ap_block_pp0_stage6_11001))) begin
        icmp_ln1039_reg_1928 <= icmp_ln1039_fu_1262_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        icmp_ln26_reg_1469 <= icmp_ln26_fu_566_p2;
        icmp_ln26_reg_1469_pp0_iter1_reg <= icmp_ln26_reg_1469;
        icmp_ln26_reg_1469_pp0_iter2_reg <= icmp_ln26_reg_1469_pp0_iter1_reg;
        trunc_ln41_mid2_reg_1532_pp0_iter1_reg <= trunc_ln41_mid2_reg_1532;
        trunc_ln41_mid2_reg_1532_pp0_iter2_reg <= trunc_ln41_mid2_reg_1532_pp0_iter1_reg;
        y_2_reg_1461 <= y_fu_150;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_predicate_op228_read_state13 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001))) begin
        pix_V_1_reg_1775 <= m_axi_gmem_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_predicate_op240_read_state14 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (1'b0 == ap_block_pp0_stage4_11001))) begin
        pix_V_2_reg_1790 <= m_axi_gmem_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_predicate_op256_read_state15 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5) & (1'b0 == ap_block_pp0_stage5_11001))) begin
        pix_V_3_reg_1811 <= m_axi_gmem_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage6) & (1'b0 == ap_block_pp0_stage6_11001) & (icmp_ln26_reg_1469_pp0_iter1_reg == 1'd0))) begin
        pix_V_4_reg_1826 <= m_axi_gmem_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_predicate_op289_read_state17 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7) & (1'b0 == ap_block_pp0_stage7_11001))) begin
        pix_V_5_reg_1847 <= m_axi_gmem_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage8) & (1'b0 == ap_block_pp0_stage8_11001) & (ap_predicate_op304_read_state18 == 1'b1))) begin
        pix_V_6_reg_1862 <= m_axi_gmem_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_predicate_op318_read_state19 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        pix_V_7_reg_1882 <= m_axi_gmem_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_predicate_op331_read_state20 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        pix_V_8_reg_1908 <= m_axi_gmem_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_predicate_op217_read_state12 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001))) begin
        pix_V_reg_1760 <= m_axi_gmem_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage7) & (1'b0 == ap_block_pp0_stage7_11001))) begin
        scaled_V_reg_1939 <= grp_fu_1181_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage8) & (1'b0 == ap_block_pp0_stage8_11001))) begin
        select_ln1039_1_reg_1944 <= select_ln1039_1_fu_1325_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln26_reg_1469 == 1'd0))) begin
        zext_ln26_reg_1665[3 : 0] <= zext_ln26_fu_1184_p1[3 : 0];
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        B_CONV1_V_ce0 = 1'b1;
    end else begin
        B_CONV1_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        W_CONV1_V_0_0_0_ce0 = 1'b1;
    end else begin
        W_CONV1_V_0_0_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        W_CONV1_V_0_0_1_ce0 = 1'b1;
    end else begin
        W_CONV1_V_0_0_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        W_CONV1_V_0_0_2_ce0 = 1'b1;
    end else begin
        W_CONV1_V_0_0_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        W_CONV1_V_0_1_0_ce0 = 1'b1;
    end else begin
        W_CONV1_V_0_1_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        W_CONV1_V_0_1_1_ce0 = 1'b1;
    end else begin
        W_CONV1_V_0_1_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        W_CONV1_V_0_1_2_ce0 = 1'b1;
    end else begin
        W_CONV1_V_0_1_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        W_CONV1_V_0_2_0_ce0 = 1'b1;
    end else begin
        W_CONV1_V_0_2_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        W_CONV1_V_0_2_1_ce0 = 1'b1;
    end else begin
        W_CONV1_V_0_2_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        W_CONV1_V_0_2_2_ce0 = 1'b1;
    end else begin
        W_CONV1_V_0_2_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage8) & (1'b0 == ap_block_pp0_stage8_subdone) & (icmp_ln26_reg_1469 == 1'd1))) begin
        ap_condition_exit_pp0_iter0_stage8 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage8 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone) & (icmp_ln26_reg_1469_pp0_iter1_reg == 1'd1))) begin
        ap_condition_exit_pp0_iter2_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter2_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to1 = 1'b1;
    end else begin
        ap_idle_pp0_0to1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0_1to3 = 1'b1;
    end else begin
        ap_idle_pp0_1to3 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln26_reg_1469_pp0_iter2_reg == 1'd0) & (icmp_ln35_1_reg_1607_pp0_iter1_reg == 1'd1))) begin
        ap_phi_mux_acc_V_10_phi_fu_479_p4 = grp_fu_1382_p3;
    end else begin
        ap_phi_mux_acc_V_10_phi_fu_479_p4 = ap_phi_reg_pp0_iter2_acc_V_10_reg_476;
    end
end

always @ (*) begin
    if (((icmp_ln26_reg_1469_pp0_iter2_reg == 1'd0) & (1'd1 == and_ln35_2_reg_1639_pp0_iter1_reg))) begin
        ap_phi_mux_acc_V_12_phi_fu_489_p4 = grp_fu_1391_p3;
    end else begin
        ap_phi_mux_acc_V_12_phi_fu_489_p4 = ap_phi_reg_pp0_iter2_acc_V_12_reg_486;
    end
end

always @ (*) begin
    if (((cmp20_2_mid2_reg_1559_pp0_iter2_reg == 1'd1) & (icmp_ln26_reg_1469_pp0_iter2_reg == 1'd0))) begin
        ap_phi_mux_acc_V_14_phi_fu_500_p4 = grp_fu_1400_p3;
    end else begin
        ap_phi_mux_acc_V_14_phi_fu_500_p4 = ap_phi_reg_pp0_iter2_acc_V_14_reg_497;
    end
end

always @ (*) begin
    if (((1'd1 == and_ln35_reg_1591_pp0_iter1_reg) & (icmp_ln26_reg_1469_pp0_iter1_reg == 1'd0))) begin
        ap_phi_mux_acc_V_1_phi_fu_439_p4 = grp_fu_1338_p3;
    end else begin
        ap_phi_mux_acc_V_1_phi_fu_439_p4 = ap_phi_reg_pp0_iter1_acc_V_1_reg_436;
    end
end

always @ (*) begin
    if (((cmp19_mid2_reg_1553_pp0_iter1_reg == 1'd1) & (icmp_ln26_reg_1469_pp0_iter1_reg == 1'd0))) begin
        ap_phi_mux_acc_V_3_phi_fu_449_p4 = grp_fu_1347_p3;
    end else begin
        ap_phi_mux_acc_V_3_phi_fu_449_p4 = ap_phi_reg_pp0_iter1_acc_V_3_reg_446;
    end
end

always @ (*) begin
    if (((1'd1 == and_ln35_1_reg_1611_pp0_iter1_reg) & (icmp_ln26_reg_1469_pp0_iter1_reg == 1'd0))) begin
        ap_phi_mux_acc_V_5_phi_fu_459_p4 = grp_fu_1356_p3;
    end else begin
        ap_phi_mux_acc_V_5_phi_fu_459_p4 = ap_phi_reg_pp0_iter1_acc_V_5_reg_456;
    end
end

always @ (*) begin
    if (((icmp_ln35_reg_1587_pp0_iter1_reg == 1'd1) & (icmp_ln26_reg_1469_pp0_iter1_reg == 1'd0))) begin
        ap_phi_mux_acc_V_7_phi_fu_469_p4 = grp_fu_1365_p3;
    end else begin
        ap_phi_mux_acc_V_7_phi_fu_469_p4 = ap_phi_reg_pp0_iter2_acc_V_7_reg_466;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage8) & (1'b0 == ap_block_pp0_stage8_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        cnn_accel_ap_int_8_const_ap_uint_4_conv1_1_ce0 = 1'b1;
    end else begin
        cnn_accel_ap_int_8_const_ap_uint_4_conv1_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln41_mid2_reg_1532_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        cnn_accel_ap_int_8_const_ap_uint_4_conv1_1_we0 = 1'b1;
    end else begin
        cnn_accel_ap_int_8_const_ap_uint_4_conv1_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        cnn_accel_ap_int_8_const_ap_uint_4_conv1_ce0 = 1'b1;
    end else begin
        cnn_accel_ap_int_8_const_ap_uint_4_conv1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln41_mid2_reg_1532_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        cnn_accel_ap_int_8_const_ap_uint_4_conv1_we0 = 1'b1;
    end else begin
        cnn_accel_ap_int_8_const_ap_uint_4_conv1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((((cmp19_mid2_reg_1553 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5) & (1'b0 == ap_block_pp0_stage5) & (icmp_ln26_reg_1469 == 1'd0)) | ((icmp_ln35_1_reg_1607 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0) & (icmp_ln26_reg_1469 == 1'd0)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3) & (1'd1 == and_ln35_3_reg_1655) & (icmp_ln26_reg_1469_pp0_iter1_reg == 1'd0)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (cmp20_2_mid2_reg_1559 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2) & (icmp_ln26_reg_1469_pp0_iter1_reg == 1'd0)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1) & (1'd1 == and_ln35_2_reg_1639) & (icmp_ln26_reg_1469 == 1'd0)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage8) & (1'b0 == ap_block_pp0_stage8) & (icmp_ln26_reg_1469 == 1'd0)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6) & (1'b0 == ap_block_pp0_stage6) & (1'd1 == and_ln35_1_reg_1611) & (icmp_ln26_reg_1469 == 1'd0)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln35_reg_1587 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage7) & (1'b0 == ap_block_pp0_stage7) & (icmp_ln26_reg_1469 == 1'd0)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (1'b0 == ap_block_pp0_stage4) & (1'd1 == and_ln35_reg_1591) & (icmp_ln26_reg_1469 == 1'd0)))) begin
        gmem_blk_n_AR = m_axi_gmem_ARREADY;
    end else begin
        gmem_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if ((((cmp19_mid2_reg_1553_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3) & (icmp_ln26_reg_1469_pp0_iter1_reg == 1'd0)) | ((icmp_ln35_1_reg_1607_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7) & (1'b0 == ap_block_pp0_stage7) & (icmp_ln26_reg_1469_pp0_iter1_reg == 1'd0)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (cmp20_2_mid2_reg_1559_pp0_iter1_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0) & (icmp_ln26_reg_1469_pp0_iter1_reg == 1'd0)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1) & (1'd1 == and_ln35_3_reg_1655_pp0_iter1_reg) & (icmp_ln26_reg_1469_pp0_iter1_reg == 1'd0)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage8) & (1'b0 == ap_block_pp0_stage8) & (ap_predicate_op304_read_state18 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6) & (1'b0 == ap_block_pp0_stage6) & (icmp_ln26_reg_1469_pp0_iter1_reg == 1'd0)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln35_reg_1587_pp0_iter1_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage5) & (1'b0 == ap_block_pp0_stage5) & (icmp_ln26_reg_1469_pp0_iter1_reg == 1'd0)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2) & (1'd1 == and_ln35_reg_1591) & (icmp_ln26_reg_1469_pp0_iter1_reg == 1'd0)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (1'b0 == ap_block_pp0_stage4) & (1'd1 == and_ln35_1_reg_1611_pp0_iter1_reg) & (icmp_ln26_reg_1469_pp0_iter1_reg == 1'd0)))) begin
        gmem_blk_n_R = m_axi_gmem_RVALID;
    end else begin
        gmem_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage6) & (1'b0 == ap_block_pp0_stage6_11001)) | ((1'b1 == ap_CS_fsm_pp0_stage7) & (1'b0 == ap_block_pp0_stage7_11001)))) begin
        grp_fu_1276_ce = 1'b1;
    end else begin
        grp_fu_1276_ce = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage6) & (1'b0 == ap_block_pp0_stage6_11001)) | ((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001)) | ((1'b1 == ap_CS_fsm_pp0_stage5) & (1'b0 == ap_block_pp0_stage5_11001)) | ((1'b1 == ap_CS_fsm_pp0_stage4) & (1'b0 == ap_block_pp0_stage4_11001)))) begin
        grp_fu_1338_ce = 1'b1;
    end else begin
        grp_fu_1338_ce = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage6) & (1'b0 == ap_block_pp0_stage6_11001)) | ((1'b1 == ap_CS_fsm_pp0_stage5) & (1'b0 == ap_block_pp0_stage5_11001)) | ((1'b1 == ap_CS_fsm_pp0_stage7) & (1'b0 == ap_block_pp0_stage7_11001)) | ((1'b1 == ap_CS_fsm_pp0_stage4) & (1'b0 == ap_block_pp0_stage4_11001)))) begin
        grp_fu_1347_ce = 1'b1;
    end else begin
        grp_fu_1347_ce = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage8) & (1'b0 == ap_block_pp0_stage8_11001)) | ((1'b1 == ap_CS_fsm_pp0_stage6) & (1'b0 == ap_block_pp0_stage6_11001)) | ((1'b1 == ap_CS_fsm_pp0_stage5) & (1'b0 == ap_block_pp0_stage5_11001)) | ((1'b1 == ap_CS_fsm_pp0_stage7) & (1'b0 == ap_block_pp0_stage7_11001)))) begin
        grp_fu_1356_ce = 1'b1;
    end else begin
        grp_fu_1356_ce = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage8) & (1'b0 == ap_block_pp0_stage8_11001)) | ((1'b1 == ap_CS_fsm_pp0_stage6) & (1'b0 == ap_block_pp0_stage6_11001)) | ((1'b1 == ap_CS_fsm_pp0_stage7) & (1'b0 == ap_block_pp0_stage7_11001)) | ((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        grp_fu_1365_ce = 1'b1;
    end else begin
        grp_fu_1365_ce = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage8) & (1'b0 == ap_block_pp0_stage8_11001)) | ((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)) | ((1'b1 == ap_CS_fsm_pp0_stage7) & (1'b0 == ap_block_pp0_stage7_11001)) | ((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        grp_fu_1374_ce = 1'b1;
    end else begin
        grp_fu_1374_ce = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage8) & (1'b0 == ap_block_pp0_stage8_11001)) | ((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)) | ((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001)) | ((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        grp_fu_1382_ce = 1'b1;
    end else begin
        grp_fu_1382_ce = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001)) | ((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)) | ((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001)) | ((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        grp_fu_1391_ce = 1'b1;
    end else begin
        grp_fu_1391_ce = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001)) | ((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)) | ((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001)) | ((1'b1 == ap_CS_fsm_pp0_stage4) & (1'b0 == ap_block_pp0_stage4_11001)))) begin
        grp_fu_1400_ce = 1'b1;
    end else begin
        grp_fu_1400_ce = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001)) | ((1'b1 == ap_CS_fsm_pp0_stage5) & (1'b0 == ap_block_pp0_stage5_11001)) | ((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001)) | ((1'b1 == ap_CS_fsm_pp0_stage4) & (1'b0 == ap_block_pp0_stage4_11001)))) begin
        grp_fu_1409_ce = 1'b1;
    end else begin
        grp_fu_1409_ce = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_op235_readreq_state13 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001))) begin
        m_axi_gmem_ARADDR = gmem_addr_8_reg_1659;
    end else if (((ap_predicate_op224_readreq_state12 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001))) begin
        m_axi_gmem_ARADDR = gmem_addr_7_reg_1649;
    end else if (((ap_predicate_op207_readreq_state11 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        m_axi_gmem_ARADDR = gmem_addr_6_reg_1643;
    end else if (((ap_predicate_op181_readreq_state10 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        m_axi_gmem_ARADDR = gmem_addr_5_reg_1633;
    end else if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage8) & (1'b0 == ap_block_pp0_stage8_11001) & (icmp_ln26_reg_1469 == 1'd0))) begin
        m_axi_gmem_ARADDR = gmem_addr_4_reg_1627;
    end else if (((ap_predicate_op170_readreq_state8 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7) & (1'b0 == ap_block_pp0_stage7_11001))) begin
        m_axi_gmem_ARADDR = gmem_addr_3_reg_1621;
    end else if (((ap_predicate_op166_readreq_state7 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6) & (1'b0 == ap_block_pp0_stage6_11001))) begin
        m_axi_gmem_ARADDR = gmem_addr_2_reg_1615;
    end else if (((ap_predicate_op163_readreq_state6 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5) & (1'b0 == ap_block_pp0_stage5_11001))) begin
        m_axi_gmem_ARADDR = gmem_addr_1_reg_1601;
    end else if (((ap_predicate_op161_readreq_state5 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (1'b0 == ap_block_pp0_stage4_11001))) begin
        m_axi_gmem_ARADDR = gmem_addr_reg_1595;
    end else begin
        m_axi_gmem_ARADDR = 'bx;
    end
end

always @ (*) begin
    if ((((ap_predicate_op170_readreq_state8 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7) & (1'b0 == ap_block_pp0_stage7_11001)) | ((ap_predicate_op166_readreq_state7 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6) & (1'b0 == ap_block_pp0_stage6_11001)) | ((ap_predicate_op163_readreq_state6 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5) & (1'b0 == ap_block_pp0_stage5_11001)) | ((ap_predicate_op161_readreq_state5 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (1'b0 == ap_block_pp0_stage4_11001)) | ((ap_predicate_op235_readreq_state13 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001)) | ((ap_predicate_op224_readreq_state12 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001)) | ((ap_predicate_op207_readreq_state11 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)) | ((ap_predicate_op181_readreq_state10 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage8) & (1'b0 == ap_block_pp0_stage8_11001) & (icmp_ln26_reg_1469 == 1'd0)))) begin
        m_axi_gmem_ARVALID = 1'b1;
    end else begin
        m_axi_gmem_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_predicate_op289_read_state17 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7) & (1'b0 == ap_block_pp0_stage7_11001)) | ((ap_predicate_op256_read_state15 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5) & (1'b0 == ap_block_pp0_stage5_11001)) | ((ap_predicate_op240_read_state14 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (1'b0 == ap_block_pp0_stage4_11001)) | ((ap_predicate_op228_read_state13 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001)) | ((ap_predicate_op217_read_state12 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001)) | ((ap_predicate_op331_read_state20 == 1'b1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)) | ((ap_predicate_op318_read_state19 == 1'b1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage8) & (1'b0 == ap_block_pp0_stage8_11001) & (ap_predicate_op304_read_state18 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6) & (1'b0 == ap_block_pp0_stage6_11001) & (icmp_ln26_reg_1469_pp0_iter1_reg == 1'd0)))) begin
        m_axi_gmem_RREADY = 1'b1;
    end else begin
        m_axi_gmem_RREADY = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if (((1'b1 == ap_condition_exit_pp0_iter2_stage0) & (ap_idle_pp0_0to1 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((~((ap_start_int == 1'b0) & (ap_idle_pp0_1to3 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        ap_ST_fsm_pp0_stage3 : begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end
        end
        ap_ST_fsm_pp0_stage4 : begin
            if ((1'b0 == ap_block_pp0_stage4_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end
        end
        ap_ST_fsm_pp0_stage5 : begin
            if ((1'b0 == ap_block_pp0_stage5_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage5;
            end
        end
        ap_ST_fsm_pp0_stage6 : begin
            if ((1'b0 == ap_block_pp0_stage6_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage6;
            end
        end
        ap_ST_fsm_pp0_stage7 : begin
            if ((1'b0 == ap_block_pp0_stage7_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage7;
            end
        end
        ap_ST_fsm_pp0_stage8 : begin
            if ((1'b0 == ap_block_pp0_stage8_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage8;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign B_CONV1_V_address0 = zext_ln26_fu_1184_p1;

assign W_CONV1_V_0_0_0_address0 = zext_ln26_fu_1184_p1;

assign W_CONV1_V_0_0_1_address0 = zext_ln26_fu_1184_p1;

assign W_CONV1_V_0_0_2_address0 = zext_ln26_fu_1184_p1;

assign W_CONV1_V_0_1_0_address0 = zext_ln26_fu_1184_p1;

assign W_CONV1_V_0_1_1_address0 = zext_ln26_fu_1184_p1;

assign W_CONV1_V_0_1_2_address0 = zext_ln26_fu_1184_p1;

assign W_CONV1_V_0_2_0_address0 = zext_ln26_fu_1184_p1;

assign W_CONV1_V_0_2_1_address0 = zext_ln26_fu_1184_p1;

assign W_CONV1_V_0_2_2_address0 = zext_ln26_reg_1665;

assign add_ln26_1_fu_572_p2 = (indvar_flatten63_fu_162 + 13'd1);

assign add_ln26_fu_584_p2 = (oc_fu_158 + 4'd1);

assign add_ln34_1_fu_1068_p2 = (x_mid2_reg_1546 + 5'd1);

assign add_ln34_fu_1023_p2 = ($signed(zext_ln28_1_fu_1020_p1) + $signed(6'd63));

assign add_ln36_10_fu_1150_p2 = (zext_ln28_fu_1017_p1 + add_ln36_2_mid2_fu_1012_p2);

assign add_ln36_11_fu_1167_p2 = (zext_ln35_fu_1073_p1 + add_ln36_2_mid2_fu_1012_p2);

assign add_ln36_12_fu_911_p2 = ($signed(p_mid1_fu_883_p2) + $signed(11'd2020));

assign add_ln36_13_fu_917_p2 = ($signed(p_cast_mid1_fu_889_p1) + $signed(image_r));

assign add_ln36_14_fu_929_p2 = ($signed(p_mid1_fu_883_p2) + $signed(11'd28));

assign add_ln36_1_fu_811_p2 = ($signed(p_cast_fu_790_p1) + $signed(image_r));

assign add_ln36_1_mid2_fu_922_p3 = ((and_ln26_2_reg_1503[0:0] == 1'b1) ? add_ln36_13_fu_917_p2 : select_ln26_3_fu_832_p3);

assign add_ln36_2_fu_816_p2 = ($signed(empty_fu_784_p2) + $signed(11'd28));

assign add_ln36_2_mid2_fu_1012_p2 = ($signed(add_ln36_2_mid2_v_cast_fu_1008_p1) + $signed(image_r));

assign add_ln36_2_mid2_v_cast_fu_1008_p1 = $signed(add_ln36_2_mid2_v_fu_1002_p3);

assign add_ln36_2_mid2_v_fu_1002_p3 = ((and_ln26_2_reg_1503[0:0] == 1'b1) ? add_ln36_14_reg_1577 : select_ln26_4_fu_981_p3);

assign add_ln36_3_fu_1044_p2 = ($signed(sext_ln35_fu_1029_p1) + $signed(add_ln36_mid2_fu_997_p2));

assign add_ln36_4_fu_1056_p2 = (zext_ln28_fu_1017_p1 + add_ln36_mid2_fu_997_p2);

assign add_ln36_5_fu_1088_p2 = (zext_ln35_fu_1073_p1 + add_ln36_mid2_fu_997_p2);

assign add_ln36_6_fu_1100_p2 = ($signed(sext_ln35_fu_1029_p1) + $signed(add_ln36_1_mid2_reg_1570));

assign add_ln36_7_fu_1111_p2 = (zext_ln28_fu_1017_p1 + add_ln36_1_mid2_reg_1570);

assign add_ln36_8_fu_1122_p2 = (zext_ln35_fu_1073_p1 + add_ln36_1_mid2_reg_1570);

assign add_ln36_9_fu_1138_p2 = ($signed(sext_ln35_fu_1029_p1) + $signed(add_ln36_2_mid2_fu_1012_p2));

assign add_ln36_fu_805_p2 = ($signed(empty_fu_784_p2) + $signed(11'd2020));

assign add_ln36_mid2_fu_997_p2 = ($signed(add_ln36_mid2_v_cast_fu_993_p1) + $signed(image_r));

assign add_ln36_mid2_v_cast_fu_993_p1 = $signed(add_ln36_mid2_v_fu_987_p3);

assign add_ln36_mid2_v_fu_987_p3 = ((and_ln26_2_reg_1503[0:0] == 1'b1) ? add_ln36_12_reg_1565 : select_ln26_2_fu_975_p3);

assign add_ln41_1_fu_964_p2 = (sub_ln41_1_fu_949_p2 + zext_ln41_3_fu_960_p1);

assign add_ln41_fu_706_p2 = ($signed(sext_ln26_9_fu_642_p1) + $signed(zext_ln41_2_fu_702_p1));

assign and_ln26_1_fu_660_p2 = (xor_ln26_fu_646_p2 & trunc_ln41_fu_562_p1);

assign and_ln26_2_fu_672_p2 = (xor_ln26_fu_646_p2 & icmp_ln28_fu_666_p2);

assign and_ln26_fu_822_p2 = (xor_ln26_reg_1498 & cmp19_fu_757_p2);

assign and_ln35_1_fu_1083_p2 = (icmp_ln35_1_fu_1077_p2 & cmp19_mid2_reg_1553);

assign and_ln35_2_fu_1133_p2 = (icmp_ln35_fu_1033_p2 & cmp20_2_mid2_reg_1559);

assign and_ln35_3_fu_1162_p2 = (icmp_ln35_1_fu_1077_p2 & cmp20_2_mid2_reg_1559);

assign and_ln35_fu_1039_p2 = (icmp_ln35_fu_1033_p2 & cmp19_mid2_reg_1553);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp0_stage3 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_pp0_stage4 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_pp0_stage5 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_pp0_stage6 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_pp0_stage7 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_pp0_stage8 = ap_CS_fsm[32'd8];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state10_io)) | ((m_axi_gmem_RVALID == 1'b0) & (ap_predicate_op318_read_state19 == 1'b1) & (ap_enable_reg_pp0_iter2 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state10_io)) | ((m_axi_gmem_RVALID == 1'b0) & (ap_predicate_op318_read_state19 == 1'b1) & (ap_enable_reg_pp0_iter2 == 1'b1)));
end

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_11001 = (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state11_io)) | ((m_axi_gmem_RVALID == 1'b0) & (ap_predicate_op331_read_state20 == 1'b1) & (ap_enable_reg_pp0_iter2 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage1_subdone = (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state11_io)) | ((m_axi_gmem_RVALID == 1'b0) & (ap_predicate_op331_read_state20 == 1'b1) & (ap_enable_reg_pp0_iter2 == 1'b1)));
end

assign ap_block_pp0_stage2 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage2_11001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & ((1'b1 == ap_block_state12_io) | ((m_axi_gmem_RVALID == 1'b0) & (ap_predicate_op217_read_state12 == 1'b1))));
end

always @ (*) begin
    ap_block_pp0_stage2_subdone = ((ap_enable_reg_pp0_iter1 == 1'b1) & ((1'b1 == ap_block_state12_io) | ((m_axi_gmem_RVALID == 1'b0) & (ap_predicate_op217_read_state12 == 1'b1))));
end

assign ap_block_pp0_stage3 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage3_11001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & ((1'b1 == ap_block_state13_io) | ((m_axi_gmem_RVALID == 1'b0) & (ap_predicate_op228_read_state13 == 1'b1))));
end

always @ (*) begin
    ap_block_pp0_stage3_subdone = ((ap_enable_reg_pp0_iter1 == 1'b1) & ((1'b1 == ap_block_state13_io) | ((m_axi_gmem_RVALID == 1'b0) & (ap_predicate_op228_read_state13 == 1'b1))));
end

assign ap_block_pp0_stage4 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage4_11001 = (((m_axi_gmem_RVALID == 1'b0) & (ap_predicate_op240_read_state14 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state5_io)));
end

always @ (*) begin
    ap_block_pp0_stage4_subdone = (((m_axi_gmem_RVALID == 1'b0) & (ap_predicate_op240_read_state14 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state5_io)));
end

assign ap_block_pp0_stage5 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage5_11001 = (((m_axi_gmem_RVALID == 1'b0) & (ap_predicate_op256_read_state15 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state6_io)));
end

always @ (*) begin
    ap_block_pp0_stage5_subdone = (((m_axi_gmem_RVALID == 1'b0) & (ap_predicate_op256_read_state15 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state6_io)));
end

assign ap_block_pp0_stage6 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage6_11001 = (((m_axi_gmem_RVALID == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln26_reg_1469_pp0_iter1_reg == 1'd0)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state7_io)));
end

always @ (*) begin
    ap_block_pp0_stage6_subdone = (((m_axi_gmem_RVALID == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln26_reg_1469_pp0_iter1_reg == 1'd0)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state7_io)));
end

assign ap_block_pp0_stage7 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage7_11001 = (((m_axi_gmem_RVALID == 1'b0) & (ap_predicate_op289_read_state17 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state8_io)));
end

always @ (*) begin
    ap_block_pp0_stage7_subdone = (((m_axi_gmem_RVALID == 1'b0) & (ap_predicate_op289_read_state17 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state8_io)));
end

assign ap_block_pp0_stage8 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage8_11001 = (((m_axi_gmem_RVALID == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (ap_predicate_op304_read_state18 == 1'b1)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state9_io)));
end

always @ (*) begin
    ap_block_pp0_stage8_subdone = (((m_axi_gmem_RVALID == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (ap_predicate_op304_read_state18 == 1'b1)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state9_io)));
end

always @ (*) begin
    ap_block_state10_io = ((m_axi_gmem_ARREADY == 1'b0) & (ap_predicate_op181_readreq_state10 == 1'b1));
end

assign ap_block_state10_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state11_io = ((m_axi_gmem_ARREADY == 1'b0) & (ap_predicate_op207_readreq_state11 == 1'b1));
end

assign ap_block_state11_pp0_stage1_iter1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state12_io = ((m_axi_gmem_ARREADY == 1'b0) & (ap_predicate_op224_readreq_state12 == 1'b1));
end

always @ (*) begin
    ap_block_state12_pp0_stage2_iter1 = ((m_axi_gmem_RVALID == 1'b0) & (ap_predicate_op217_read_state12 == 1'b1));
end

always @ (*) begin
    ap_block_state13_io = ((m_axi_gmem_ARREADY == 1'b0) & (ap_predicate_op235_readreq_state13 == 1'b1));
end

always @ (*) begin
    ap_block_state13_pp0_stage3_iter1 = ((m_axi_gmem_RVALID == 1'b0) & (ap_predicate_op228_read_state13 == 1'b1));
end

always @ (*) begin
    ap_block_state14_pp0_stage4_iter1 = ((m_axi_gmem_RVALID == 1'b0) & (ap_predicate_op240_read_state14 == 1'b1));
end

always @ (*) begin
    ap_block_state15_pp0_stage5_iter1 = ((m_axi_gmem_RVALID == 1'b0) & (ap_predicate_op256_read_state15 == 1'b1));
end

always @ (*) begin
    ap_block_state16_pp0_stage6_iter1 = ((m_axi_gmem_RVALID == 1'b0) & (icmp_ln26_reg_1469_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_block_state17_pp0_stage7_iter1 = ((m_axi_gmem_RVALID == 1'b0) & (ap_predicate_op289_read_state17 == 1'b1));
end

always @ (*) begin
    ap_block_state18_pp0_stage8_iter1 = ((m_axi_gmem_RVALID == 1'b0) & (ap_predicate_op304_read_state18 == 1'b1));
end

always @ (*) begin
    ap_block_state19_pp0_stage0_iter2 = ((m_axi_gmem_RVALID == 1'b0) & (ap_predicate_op318_read_state19 == 1'b1));
end

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state20_pp0_stage1_iter2 = ((m_axi_gmem_RVALID == 1'b0) & (ap_predicate_op331_read_state20 == 1'b1));
end

assign ap_block_state21_pp0_stage2_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state22_pp0_stage3_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state23_pp0_stage4_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state24_pp0_stage5_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state25_pp0_stage6_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state26_pp0_stage7_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state27_pp0_stage8_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state28_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage1_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage2_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage3_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state5_io = ((m_axi_gmem_ARREADY == 1'b0) & (ap_predicate_op161_readreq_state5 == 1'b1));
end

assign ap_block_state5_pp0_stage4_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state6_io = ((m_axi_gmem_ARREADY == 1'b0) & (ap_predicate_op163_readreq_state6 == 1'b1));
end

assign ap_block_state6_pp0_stage5_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state7_io = ((m_axi_gmem_ARREADY == 1'b0) & (ap_predicate_op166_readreq_state7 == 1'b1));
end

assign ap_block_state7_pp0_stage6_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state8_io = ((ap_predicate_op170_readreq_state8 == 1'b1) & (m_axi_gmem_ARREADY == 1'b0));
end

assign ap_block_state8_pp0_stage7_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state9_io = ((m_axi_gmem_ARREADY == 1'b0) & (icmp_ln26_reg_1469 == 1'd0));
end

assign ap_block_state9_pp0_stage8_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_873 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage8) & (1'b0 == ap_block_pp0_stage8_11001));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage8;

assign ap_phi_reg_pp0_iter0_acc_V_10_reg_476 = 'bx;

assign ap_phi_reg_pp0_iter0_acc_V_12_reg_486 = 'bx;

assign ap_phi_reg_pp0_iter0_acc_V_14_reg_497 = 'bx;

assign ap_phi_reg_pp0_iter0_acc_V_16_reg_508 = 'bx;

assign ap_phi_reg_pp0_iter0_acc_V_1_reg_436 = 'bx;

assign ap_phi_reg_pp0_iter0_acc_V_3_reg_446 = 'bx;

assign ap_phi_reg_pp0_iter0_acc_V_5_reg_456 = 'bx;

assign ap_phi_reg_pp0_iter0_acc_V_7_reg_466 = 'bx;

always @ (*) begin
    ap_predicate_op161_readreq_state5 = ((1'd1 == and_ln35_reg_1591) & (icmp_ln26_reg_1469 == 1'd0));
end

always @ (*) begin
    ap_predicate_op163_readreq_state6 = ((cmp19_mid2_reg_1553 == 1'd1) & (icmp_ln26_reg_1469 == 1'd0));
end

always @ (*) begin
    ap_predicate_op166_readreq_state7 = ((1'd1 == and_ln35_1_reg_1611) & (icmp_ln26_reg_1469 == 1'd0));
end

always @ (*) begin
    ap_predicate_op170_readreq_state8 = ((icmp_ln35_reg_1587 == 1'd1) & (icmp_ln26_reg_1469 == 1'd0));
end

always @ (*) begin
    ap_predicate_op181_readreq_state10 = ((icmp_ln35_1_reg_1607 == 1'd1) & (icmp_ln26_reg_1469 == 1'd0));
end

always @ (*) begin
    ap_predicate_op207_readreq_state11 = ((1'd1 == and_ln35_2_reg_1639) & (icmp_ln26_reg_1469 == 1'd0));
end

always @ (*) begin
    ap_predicate_op217_read_state12 = ((1'd1 == and_ln35_reg_1591) & (icmp_ln26_reg_1469_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op224_readreq_state12 = ((cmp20_2_mid2_reg_1559 == 1'd1) & (icmp_ln26_reg_1469_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op228_read_state13 = ((cmp19_mid2_reg_1553_pp0_iter1_reg == 1'd1) & (icmp_ln26_reg_1469_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op235_readreq_state13 = ((1'd1 == and_ln35_3_reg_1655) & (icmp_ln26_reg_1469_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op240_read_state14 = ((1'd1 == and_ln35_1_reg_1611_pp0_iter1_reg) & (icmp_ln26_reg_1469_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op256_read_state15 = ((icmp_ln35_reg_1587_pp0_iter1_reg == 1'd1) & (icmp_ln26_reg_1469_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op289_read_state17 = ((icmp_ln35_1_reg_1607_pp0_iter1_reg == 1'd1) & (icmp_ln26_reg_1469_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op304_read_state18 = ((1'd1 == and_ln35_2_reg_1639_pp0_iter1_reg) & (icmp_ln26_reg_1469_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op318_read_state19 = ((cmp20_2_mid2_reg_1559_pp0_iter1_reg == 1'd1) & (icmp_ln26_reg_1469_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op331_read_state20 = ((1'd1 == and_ln35_3_reg_1655_pp0_iter1_reg) & (icmp_ln26_reg_1469_pp0_iter1_reg == 1'd0));
end

assign cmp19_fu_757_p2 = ((y_2_reg_1461 != 5'd0) ? 1'b1 : 1'b0);

assign cmp19_mid1_fu_849_p2 = ((indvars_iv_next91_dup_reg_1514 != 5'd0) ? 1'b1 : 1'b0);

assign cmp19_mid2_fu_854_p3 = ((and_ln26_2_reg_1503[0:0] == 1'b1) ? cmp19_mid1_fu_849_p2 : and_ln26_fu_822_p2);

assign cmp20_2_fu_799_p2 = ((indvars_iv_next91_fu_794_p2 < 5'd28) ? 1'b1 : 1'b0);

assign cmp20_2_mid1_fu_898_p2 = ((indvars_iv_next91_mid1_fu_893_p2 < 5'd28) ? 1'b1 : 1'b0);

assign cmp20_2_mid2_fu_904_p3 = ((and_ln26_2_reg_1503[0:0] == 1'b1) ? cmp20_2_mid1_fu_898_p2 : or_ln26_fu_827_p2);

assign cnn_accel_ap_int_8_const_ap_uint_4_conv1_1_address0 = zext_ln41_4_fu_1333_p1;

assign cnn_accel_ap_int_8_const_ap_uint_4_conv1_1_d0 = select_ln1039_1_reg_1944;

assign cnn_accel_ap_int_8_const_ap_uint_4_conv1_address0 = zext_ln41_4_fu_1333_p1;

assign cnn_accel_ap_int_8_const_ap_uint_4_conv1_d0 = select_ln1039_1_reg_1944;

assign empty_42_fu_838_p2 = (exitcond_flatten196_reg_1478 | and_ln26_2_reg_1503);

assign empty_fu_784_p2 = (p_shl_cast_fu_769_p1 - p_shl1_cast_fu_780_p1);

assign exitcond_flatten196_fu_590_p2 = ((indvar_flatten_fu_154 == 10'd784) ? 1'b1 : 1'b0);

assign grp_fu_1181_p_ce = grp_fu_1276_ce;

assign grp_fu_1181_p_din0 = zext_ln8_fu_1272_p1;

assign grp_fu_1181_p_din1 = 47'd29779;

assign grp_fu_1338_p1 = grp_fu_1338_p10;

assign grp_fu_1338_p10 = W_CONV1_V_0_0_0_load_reg_1725;

assign icmp_ln1035_fu_1297_p2 = ((tmp_2_fu_1287_p4 != 16'd0) ? 1'b1 : 1'b0);

assign icmp_ln1039_fu_1262_p2 = (($signed(ap_phi_reg_pp0_iter2_acc_V_16_reg_508) < $signed(18'd1)) ? 1'b1 : 1'b0);

assign icmp_ln26_fu_566_p2 = ((indvar_flatten63_fu_162 == 13'd6272) ? 1'b1 : 1'b0);

assign icmp_ln28_fu_666_p2 = ((ix_fu_146 == 5'd28) ? 1'b1 : 1'b0);

assign icmp_ln35_1_fu_1077_p2 = ((add_ln34_1_fu_1068_p2 < 5'd28) ? 1'b1 : 1'b0);

assign icmp_ln35_fu_1033_p2 = ((add_ln34_fu_1023_p2 < 6'd28) ? 1'b1 : 1'b0);

assign indvar_flatten_next_fu_734_p3 = ((exitcond_flatten196_fu_590_p2[0:0] == 1'b1) ? 10'd1 : indvar_flatten_op_fu_728_p2);

assign indvar_flatten_op_fu_728_p2 = (indvar_flatten_fu_154 + 10'd1);

assign indvars_iv_next91_dup_fu_678_p2 = (select_ln26_fu_596_p3 + 5'd1);

assign indvars_iv_next91_fu_794_p2 = (y_2_reg_1461 + 5'd1);

assign indvars_iv_next91_mid1_fu_893_p2 = (select_ln26_reg_1487 + 5'd2);

assign lshr_ln41_mid1_fu_684_p4 = {{indvars_iv_next91_dup_fu_678_p2[4:1]}};

assign lshr_ln_fu_552_p4 = {{y_fu_150[4:1]}};

assign m_axi_gmem_ARBURST = 2'd0;

assign m_axi_gmem_ARCACHE = 4'd0;

assign m_axi_gmem_ARID = 1'd0;

assign m_axi_gmem_ARLEN = 32'd1;

assign m_axi_gmem_ARLOCK = 2'd0;

assign m_axi_gmem_ARPROT = 3'd0;

assign m_axi_gmem_ARQOS = 4'd0;

assign m_axi_gmem_ARREGION = 4'd0;

assign m_axi_gmem_ARSIZE = 3'd0;

assign m_axi_gmem_ARUSER = 1'd0;

assign m_axi_gmem_AWADDR = 64'd0;

assign m_axi_gmem_AWBURST = 2'd0;

assign m_axi_gmem_AWCACHE = 4'd0;

assign m_axi_gmem_AWID = 1'd0;

assign m_axi_gmem_AWLEN = 32'd0;

assign m_axi_gmem_AWLOCK = 2'd0;

assign m_axi_gmem_AWPROT = 3'd0;

assign m_axi_gmem_AWQOS = 4'd0;

assign m_axi_gmem_AWREGION = 4'd0;

assign m_axi_gmem_AWSIZE = 3'd0;

assign m_axi_gmem_AWUSER = 1'd0;

assign m_axi_gmem_AWVALID = 1'b0;

assign m_axi_gmem_BREADY = 1'b0;

assign m_axi_gmem_WDATA = 8'd0;

assign m_axi_gmem_WID = 1'd0;

assign m_axi_gmem_WLAST = 1'b0;

assign m_axi_gmem_WSTRB = 1'd0;

assign m_axi_gmem_WUSER = 1'd0;

assign m_axi_gmem_WVALID = 1'b0;

assign or_ln1039_fu_1320_p2 = (icmp_ln1039_reg_1928 | icmp_ln1035_fu_1297_p2);

assign or_ln26_fu_827_p2 = (exitcond_flatten196_reg_1478 | cmp20_2_fu_799_p2);

assign p_cast_fu_790_p1 = empty_fu_784_p2;

assign p_cast_mid1_fu_889_p1 = p_mid1_fu_883_p2;

assign p_mid1_fu_883_p2 = (p_shl_cast_mid1_fu_868_p1 - p_shl1_cast_mid1_fu_879_p1);

assign p_shl1_cast_fu_780_p1 = p_shl1_fu_773_p3;

assign p_shl1_cast_mid1_fu_879_p1 = p_shl1_mid1_fu_872_p3;

assign p_shl1_fu_773_p3 = {{y_2_reg_1461}, {2'd0}};

assign p_shl1_mid1_fu_872_p3 = {{indvars_iv_next91_dup_reg_1514}, {2'd0}};

assign p_shl2_fu_935_p3 = {{trunc_ln41_1_reg_1527}, {5'd0}};

assign p_shl3_fu_942_p3 = {{add_ln41_reg_1522}, {2'd0}};

assign p_shl_cast_fu_769_p1 = p_shl_fu_762_p3;

assign p_shl_cast_mid1_fu_868_p1 = p_shl_mid1_fu_861_p3;

assign p_shl_fu_762_p3 = {{y_2_reg_1461}, {5'd0}};

assign p_shl_mid1_fu_861_p3 = {{indvars_iv_next91_dup_reg_1514}, {5'd0}};

assign scaled_V_1_fu_1282_p2 = (scaled_V_reg_1939 + 47'd8388608);

assign select_ln1039_1_fu_1325_p3 = ((or_ln1039_fu_1320_p2[0:0] == 1'b1) ? select_ln1039_fu_1313_p3 : trunc_ln2_fu_1303_p4);

assign select_ln1039_fu_1313_p3 = ((icmp_ln1039_reg_1928[0:0] == 1'b1) ? 8'd0 : 8'd127);

assign select_ln26_1_fu_604_p3 = ((exitcond_flatten196_fu_590_p2[0:0] == 1'b1) ? add_ln26_fu_584_p2 : oc_fu_158);

assign select_ln26_2_fu_975_p3 = ((exitcond_flatten196_reg_1478[0:0] == 1'b1) ? 11'd2020 : add_ln36_reg_1536);

assign select_ln26_3_fu_832_p3 = ((exitcond_flatten196_reg_1478[0:0] == 1'b1) ? image_r : add_ln36_1_fu_811_p2);

assign select_ln26_4_fu_981_p3 = ((exitcond_flatten196_reg_1478[0:0] == 1'b1) ? 11'd28 : add_ln36_2_reg_1541);

assign select_ln26_5_fu_652_p3 = ((exitcond_flatten196_fu_590_p2[0:0] == 1'b1) ? 4'd0 : lshr_ln_fu_552_p4);

assign select_ln26_fu_596_p3 = ((exitcond_flatten196_fu_590_p2[0:0] == 1'b1) ? 5'd0 : y_fu_150);

assign sext_ln26_9_fu_642_p1 = $signed(sub_ln41_fu_636_p2);

assign sext_ln26_fu_1208_p1 = B_CONV1_V_load_reg_1715;

assign sext_ln30_fu_1226_p1 = ap_phi_mux_acc_V_3_phi_fu_449_p4;

assign sext_ln35_fu_1029_p1 = add_ln34_fu_1023_p2;

assign sext_ln8_fu_1268_p1 = ap_phi_reg_pp0_iter2_acc_V_16_reg_508;

assign sub_ln41_1_fu_949_p2 = (p_shl2_fu_935_p3 - p_shl3_fu_942_p3);

assign sub_ln41_fu_636_p2 = (zext_ln41_fu_620_p1 - zext_ln41_1_fu_632_p1);

assign tmp_1_fu_624_p3 = {{select_ln26_1_fu_604_p3}, {1'd0}};

assign tmp_2_fu_1287_p4 = {{scaled_V_1_fu_1282_p2[46:31]}};

assign tmp_fu_612_p3 = {{select_ln26_1_fu_604_p3}, {4'd0}};

assign trunc_ln2_fu_1303_p4 = {{scaled_V_1_fu_1282_p2[31:24]}};

assign trunc_ln41_1_fu_712_p1 = add_ln41_fu_706_p2[6:0];

assign trunc_ln41_2_fu_716_p1 = indvars_iv_next91_dup_fu_678_p2[0:0];

assign trunc_ln41_fu_562_p1 = y_fu_150[0:0];

assign trunc_ln41_mid2_fu_720_p3 = ((and_ln26_2_fu_672_p2[0:0] == 1'b1) ? trunc_ln41_2_fu_716_p1 : and_ln26_1_fu_660_p2);

assign x_mid2_fu_842_p3 = ((empty_42_fu_838_p2[0:0] == 1'b1) ? 5'd0 : ix_load_reg_1473);

assign xor_ln26_fu_646_p2 = (exitcond_flatten196_fu_590_p2 ^ 1'd1);

assign y_mid2_fu_955_p3 = ((and_ln26_2_reg_1503[0:0] == 1'b1) ? indvars_iv_next91_dup_reg_1514 : select_ln26_reg_1487);

assign zext_ln26_fu_1184_p1 = select_ln26_1_reg_1493;

assign zext_ln28_1_fu_1020_p1 = x_mid2_reg_1546;

assign zext_ln28_fu_1017_p1 = x_mid2_reg_1546;

assign zext_ln35_fu_1073_p1 = add_ln34_1_fu_1068_p2;

assign zext_ln41_1_fu_632_p1 = tmp_1_fu_624_p3;

assign zext_ln41_2_fu_702_p1 = zext_ln41_mid2_fu_694_p3;

assign zext_ln41_3_fu_960_p1 = x_mid2_fu_842_p3;

assign zext_ln41_4_fu_1333_p1 = add_ln41_1_reg_1582_pp0_iter2_reg;

assign zext_ln41_fu_620_p1 = tmp_fu_612_p3;

assign zext_ln41_mid2_fu_694_p3 = ((and_ln26_2_fu_672_p2[0:0] == 1'b1) ? lshr_ln41_mid1_fu_684_p4 : select_ln26_5_fu_652_p3);

assign zext_ln8_fu_1272_p1 = $unsigned(sext_ln8_fu_1268_p1);

always @ (posedge ap_clk) begin
    add_ln36_reg_1536[1:0] <= 2'b00;
    add_ln36_2_reg_1541[1:0] <= 2'b00;
    add_ln36_12_reg_1565[1:0] <= 2'b00;
    add_ln36_14_reg_1577[1:0] <= 2'b00;
    zext_ln26_reg_1665[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
end

endmodule //cnn_accel_conv1_layer
