// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module cnn_accel_cnn_accel_Pipeline_VITIS_LOOP_78_3_VITIS_LOOP_79_4_VITIS_LOOP_80_5 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        sext_ln74,
        select_ln75_3,
        zext_ln186,
        p_mid143,
        notlhs_mid147,
        notrhs_mid149,
        zext_ln76_1,
        acc_V_18_out,
        acc_V_18_out_ap_vld,
        pool1_V_address0,
        pool1_V_ce0,
        pool1_V_q0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [11:0] sext_ln74;
input  [3:0] select_ln75_3;
input  [7:0] zext_ln186;
input  [4:0] p_mid143;
input  [0:0] notlhs_mid147;
input  [0:0] notrhs_mid149;
input  [3:0] zext_ln76_1;
output  [31:0] acc_V_18_out;
output   acc_V_18_out_ap_vld;
output  [10:0] pool1_V_address0;
output   pool1_V_ce0;
input  [7:0] pool1_V_q0;

reg ap_idle;
reg acc_V_18_out_ap_vld;
reg pool1_V_ce0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
wire    ap_block_state7_pp0_stage0_iter6;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln78_fu_237_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [10:0] W_CONV2_V_address0;
reg    W_CONV2_V_ce0;
wire  signed [7:0] W_CONV2_V_q0;
wire    ap_block_pp0_stage0_11001;
wire   [4:0] zext_ln76_1_cast_fu_189_p1;
reg   [4:0] zext_ln76_1_cast_reg_759;
wire   [8:0] zext_ln186_cast_fu_197_p1;
reg   [8:0] zext_ln186_cast_reg_764;
reg   [1:0] ky_1_reg_769;
reg   [0:0] icmp_ln78_reg_774;
reg   [0:0] icmp_ln78_reg_774_pp0_iter1_reg;
reg   [0:0] icmp_ln78_reg_774_pp0_iter2_reg;
reg   [0:0] icmp_ln78_reg_774_pp0_iter3_reg;
reg   [0:0] icmp_ln78_reg_774_pp0_iter4_reg;
wire   [0:0] icmp_ln79_fu_264_p2;
reg   [0:0] icmp_ln79_reg_778;
wire   [3:0] select_ln78_1_fu_278_p3;
reg   [3:0] select_ln78_1_reg_785;
wire   [0:0] and_ln78_fu_298_p2;
reg   [0:0] and_ln78_reg_792;
wire   [1:0] add_ln79_fu_304_p2;
reg   [1:0] add_ln79_reg_799;
wire   [1:0] select_ln79_fu_316_p3;
reg   [1:0] select_ln79_reg_804;
reg   [1:0] select_ln79_reg_804_pp0_iter1_reg;
wire   [1:0] select_ln79_1_fu_324_p3;
reg   [1:0] select_ln79_1_reg_810;
wire   [10:0] trunc_ln186_fu_496_p1;
reg   [10:0] trunc_ln186_reg_815;
wire   [8:0] trunc_ln186_1_fu_500_p1;
reg   [8:0] trunc_ln186_1_reg_820;
wire   [9:0] add_ln85_fu_533_p2;
reg   [9:0] add_ln85_reg_825;
wire   [6:0] trunc_ln85_fu_539_p1;
reg   [6:0] trunc_ln85_reg_830;
wire  signed [4:0] add_ln83_1_fu_578_p2;
reg  signed [4:0] add_ln83_1_reg_835;
wire   [0:0] and_ln84_fu_595_p2;
reg   [0:0] and_ln84_reg_840;
reg   [0:0] and_ln84_reg_840_pp0_iter2_reg;
reg   [0:0] and_ln84_reg_840_pp0_iter3_reg;
reg   [0:0] and_ln84_reg_840_pp0_iter4_reg;
reg   [0:0] and_ln84_reg_840_pp0_iter5_reg;
reg   [31:0] acc_V_load_1_reg_865;
reg    ap_condition_exit_pp0_iter1_stage0;
wire   [63:0] zext_ln186_6_fu_642_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln85_2_fu_656_p1;
reg   [31:0] acc_V_fu_90;
wire   [31:0] acc_V_19_fu_672_p3;
wire  signed [31:0] sext_ln74_cast_fu_193_p1;
reg  signed [31:0] ap_sig_allocacmp_acc_V_load_1;
wire    ap_loop_init;
reg   [1:0] kx_fu_94;
wire   [1:0] add_ln80_fu_332_p2;
reg   [1:0] ap_sig_allocacmp_kx_load;
reg   [1:0] ky_fu_98;
reg   [1:0] ap_sig_allocacmp_ky_1;
reg   [3:0] indvar_flatten23_fu_102;
wire   [3:0] select_ln79_5_fu_344_p3;
reg   [3:0] ap_sig_allocacmp_indvar_flatten23_load;
reg   [3:0] ic_fu_106;
reg   [3:0] ap_sig_allocacmp_ic_load;
reg   [6:0] indvar_flatten53_fu_110;
wire   [6:0] add_ln78_1_fu_243_p2;
reg   [6:0] ap_sig_allocacmp_indvar_flatten53_load;
wire    ap_block_pp0_stage0_01001;
wire   [3:0] add_ln78_fu_258_p2;
wire   [0:0] icmp_ln80_fu_292_p2;
wire   [0:0] xor_ln78_fu_286_p2;
wire   [1:0] select_ln78_fu_270_p3;
wire   [0:0] or_ln79_fu_310_p2;
wire   [3:0] add_ln79_1_fu_338_p2;
wire   [3:0] zext_ln79_fu_377_p1;
wire   [3:0] empty_fu_380_p2;
wire   [4:0] p_cast_fu_385_p1;
wire   [4:0] empty_43_fu_389_p2;
wire   [8:0] zext_ln186_1_fu_407_p1;
wire   [8:0] add_ln186_fu_410_p2;
wire   [10:0] tmp_fu_419_p3;
wire   [61:0] zext_ln186_3_fu_427_p1;
wire   [61:0] zext_ln186_2_fu_415_p1;
wire   [7:0] tmp_s_fu_437_p3;
wire   [4:0] tmp_1_fu_448_p3;
wire   [8:0] zext_ln85_fu_444_p1;
wire   [8:0] zext_ln85_1_fu_455_p1;
wire   [8:0] sub_ln85_fu_459_p2;
wire   [0:0] notlhs_fu_395_p2;
wire   [0:0] notrhs_fu_401_p2;
wire   [61:0] sub_ln186_fu_431_p2;
wire   [61:0] zext_ln186_4_fu_487_p1;
wire   [61:0] add_ln186_1_fu_490_p2;
wire   [3:0] zext_ln79_1_fu_504_p1;
wire   [3:0] p_mid1_fu_507_p2;
wire   [4:0] p_cast_mid1_fu_512_p1;
wire   [4:0] p_mid121_fu_516_p2;
wire   [4:0] select_ln78_2_fu_469_p3;
wire   [4:0] select_ln79_2_fu_522_p3;
wire  signed [9:0] sext_ln78_fu_465_p1;
wire  signed [9:0] sext_ln85_fu_529_p1;
wire   [0:0] notlhs_mid1_fu_543_p2;
wire   [0:0] select_ln78_3_fu_475_p3;
wire   [0:0] notrhs_mid1_fu_556_p2;
wire   [0:0] select_ln78_4_fu_481_p3;
wire   [1:0] add_ln83_fu_569_p2;
wire  signed [4:0] sext_ln83_fu_574_p1;
wire   [0:0] select_ln79_3_fu_549_p3;
wire   [0:0] icmp_ln84_fu_583_p2;
wire   [0:0] and_ln84_1_fu_589_p2;
wire   [0:0] select_ln79_4_fu_562_p3;
wire   [10:0] p_shl_fu_601_p3;
wire   [10:0] p_shl1_fu_613_p3;
wire   [10:0] p_shl2_fu_620_p3;
wire   [10:0] sub_ln186_1_fu_608_p2;
wire   [10:0] zext_ln186_5_fu_633_p1;
wire   [10:0] add_ln186_2_fu_636_p2;
wire   [10:0] sub_ln85_1_fu_627_p2;
wire  signed [10:0] sext_ln85_1_fu_647_p1;
wire   [10:0] add_ln85_1_fu_650_p2;
wire  signed [31:0] grp_fu_686_p3;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_done_reg = 1'b0;
end

cnn_accel_cnn_accel_Pipeline_VITIS_LOOP_78_3_VITIS_LOOP_79_4_VITIS_LOOP_80_5_W_CONV2_V_bkb #(
    .DataWidth( 8 ),
    .AddressRange( 1152 ),
    .AddressWidth( 11 ))
W_CONV2_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(W_CONV2_V_address0),
    .ce0(W_CONV2_V_ce0),
    .q0(W_CONV2_V_q0)
);

cnn_accel_mac_muladd_8s_8s_32s_32_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mac_muladd_8s_8s_32s_32_4_1_U34(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(W_CONV2_V_q0),
    .din1(pool1_V_q0),
    .din2(ap_sig_allocacmp_acc_V_load_1),
    .ce(1'b1),
    .dout(grp_fu_686_p3)
);

cnn_accel_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter5_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            acc_V_fu_90 <= sext_ln74_cast_fu_193_p1;
        end else if ((ap_enable_reg_pp0_iter6 == 1'b1)) begin
            acc_V_fu_90 <= acc_V_19_fu_672_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln78_fu_237_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            ic_fu_106 <= select_ln78_1_fu_278_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            ic_fu_106 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln78_fu_237_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten23_fu_102 <= select_ln79_5_fu_344_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten23_fu_102 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln78_fu_237_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten53_fu_110 <= add_ln78_1_fu_243_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten53_fu_110 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln78_fu_237_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            kx_fu_94 <= add_ln80_fu_332_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            kx_fu_94 <= 2'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln78_fu_237_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            ky_fu_98 <= select_ln79_1_fu_324_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            ky_fu_98 <= 2'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        acc_V_load_1_reg_865 <= ap_sig_allocacmp_acc_V_load_1;
        and_ln84_reg_840_pp0_iter2_reg <= and_ln84_reg_840;
        and_ln84_reg_840_pp0_iter3_reg <= and_ln84_reg_840_pp0_iter2_reg;
        and_ln84_reg_840_pp0_iter4_reg <= and_ln84_reg_840_pp0_iter3_reg;
        and_ln84_reg_840_pp0_iter5_reg <= and_ln84_reg_840_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        icmp_ln78_reg_774_pp0_iter2_reg <= icmp_ln78_reg_774_pp0_iter1_reg;
        icmp_ln78_reg_774_pp0_iter3_reg <= icmp_ln78_reg_774_pp0_iter2_reg;
        icmp_ln78_reg_774_pp0_iter4_reg <= icmp_ln78_reg_774_pp0_iter3_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln78_fu_237_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln79_reg_799 <= add_ln79_fu_304_p2;
        and_ln78_reg_792 <= and_ln78_fu_298_p2;
        icmp_ln79_reg_778 <= icmp_ln79_fu_264_p2;
        select_ln78_1_reg_785 <= select_ln78_1_fu_278_p3;
        select_ln79_1_reg_810 <= select_ln79_1_fu_324_p3;
        select_ln79_reg_804 <= select_ln79_fu_316_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln78_reg_774 == 1'd0))) begin
        add_ln83_1_reg_835 <= add_ln83_1_fu_578_p2;
        add_ln85_reg_825 <= add_ln85_fu_533_p2;
        and_ln84_reg_840 <= and_ln84_fu_595_p2;
        trunc_ln186_1_reg_820 <= trunc_ln186_1_fu_500_p1;
        trunc_ln186_reg_815 <= trunc_ln186_fu_496_p1;
        trunc_ln85_reg_830 <= trunc_ln85_fu_539_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        icmp_ln78_reg_774 <= icmp_ln78_fu_237_p2;
        icmp_ln78_reg_774_pp0_iter1_reg <= icmp_ln78_reg_774;
        ky_1_reg_769 <= ap_sig_allocacmp_ky_1;
        select_ln79_reg_804_pp0_iter1_reg <= select_ln79_reg_804;
        zext_ln186_cast_reg_764[7 : 0] <= zext_ln186_cast_fu_197_p1[7 : 0];
        zext_ln76_1_cast_reg_759[3 : 0] <= zext_ln76_1_cast_fu_189_p1[3 : 0];
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        W_CONV2_V_ce0 = 1'b1;
    end else begin
        W_CONV2_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln78_reg_774_pp0_iter4_reg == 1'd1))) begin
        acc_V_18_out_ap_vld = 1'b1;
    end else begin
        acc_V_18_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln78_fu_237_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln78_reg_774 == 1'd1))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter5_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter6 == 1'b1))) begin
        ap_sig_allocacmp_acc_V_load_1 = acc_V_19_fu_672_p3;
    end else begin
        ap_sig_allocacmp_acc_V_load_1 = acc_V_fu_90;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_ic_load = 4'd0;
    end else begin
        ap_sig_allocacmp_ic_load = ic_fu_106;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten23_load = 4'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten23_load = indvar_flatten23_fu_102;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten53_load = 7'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten53_load = indvar_flatten53_fu_110;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_kx_load = 2'd0;
    end else begin
        ap_sig_allocacmp_kx_load = kx_fu_94;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_ky_1 = 2'd0;
    end else begin
        ap_sig_allocacmp_ky_1 = ky_fu_98;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        pool1_V_ce0 = 1'b1;
    end else begin
        pool1_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign W_CONV2_V_address0 = zext_ln186_6_fu_642_p1;

assign acc_V_18_out = acc_V_fu_90;

assign acc_V_19_fu_672_p3 = ((and_ln84_reg_840_pp0_iter5_reg[0:0] == 1'b1) ? grp_fu_686_p3 : acc_V_load_1_reg_865);

assign add_ln186_1_fu_490_p2 = (sub_ln186_fu_431_p2 + zext_ln186_4_fu_487_p1);

assign add_ln186_2_fu_636_p2 = (sub_ln186_1_fu_608_p2 + zext_ln186_5_fu_633_p1);

assign add_ln186_fu_410_p2 = (zext_ln186_cast_reg_764 + zext_ln186_1_fu_407_p1);

assign add_ln78_1_fu_243_p2 = (ap_sig_allocacmp_indvar_flatten53_load + 7'd1);

assign add_ln78_fu_258_p2 = (ap_sig_allocacmp_ic_load + 4'd1);

assign add_ln79_1_fu_338_p2 = (ap_sig_allocacmp_indvar_flatten23_load + 4'd1);

assign add_ln79_fu_304_p2 = (select_ln78_fu_270_p3 + 2'd1);

assign add_ln80_fu_332_p2 = (select_ln79_fu_316_p3 + 2'd1);

assign add_ln83_1_fu_578_p2 = ($signed(sext_ln83_fu_574_p1) + $signed(zext_ln76_1_cast_reg_759));

assign add_ln83_fu_569_p2 = ($signed(select_ln79_reg_804) + $signed(2'd3));

assign add_ln85_1_fu_650_p2 = ($signed(sub_ln85_1_fu_627_p2) + $signed(sext_ln85_1_fu_647_p1));

assign add_ln85_fu_533_p2 = ($signed(sext_ln78_fu_465_p1) + $signed(sext_ln85_fu_529_p1));

assign and_ln78_fu_298_p2 = (xor_ln78_fu_286_p2 & icmp_ln80_fu_292_p2);

assign and_ln84_1_fu_589_p2 = (select_ln79_3_fu_549_p3 & icmp_ln84_fu_583_p2);

assign and_ln84_fu_595_p2 = (select_ln79_4_fu_562_p3 & and_ln84_1_fu_589_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign empty_43_fu_389_p2 = ($signed(p_cast_fu_385_p1) + $signed(5'd31));

assign empty_fu_380_p2 = (zext_ln79_fu_377_p1 + select_ln75_3);

assign icmp_ln78_fu_237_p2 = ((ap_sig_allocacmp_indvar_flatten53_load == 7'd72) ? 1'b1 : 1'b0);

assign icmp_ln79_fu_264_p2 = ((ap_sig_allocacmp_indvar_flatten23_load == 4'd9) ? 1'b1 : 1'b0);

assign icmp_ln80_fu_292_p2 = ((ap_sig_allocacmp_kx_load == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln84_fu_583_p2 = ((add_ln83_1_fu_578_p2 < 5'd14) ? 1'b1 : 1'b0);

assign notlhs_fu_395_p2 = ((empty_fu_380_p2 != 4'd0) ? 1'b1 : 1'b0);

assign notlhs_mid1_fu_543_p2 = ((p_mid1_fu_507_p2 != 4'd0) ? 1'b1 : 1'b0);

assign notrhs_fu_401_p2 = (($signed(empty_43_fu_389_p2) < $signed(5'd14)) ? 1'b1 : 1'b0);

assign notrhs_mid1_fu_556_p2 = (($signed(p_mid121_fu_516_p2) < $signed(5'd14)) ? 1'b1 : 1'b0);

assign or_ln79_fu_310_p2 = (icmp_ln79_fu_264_p2 | and_ln78_fu_298_p2);

assign p_cast_fu_385_p1 = empty_fu_380_p2;

assign p_cast_mid1_fu_512_p1 = p_mid1_fu_507_p2;

assign p_mid121_fu_516_p2 = ($signed(p_cast_mid1_fu_512_p1) + $signed(5'd31));

assign p_mid1_fu_507_p2 = (zext_ln79_1_fu_504_p1 + select_ln75_3);

assign p_shl1_fu_613_p3 = {{trunc_ln85_reg_830}, {4'd0}};

assign p_shl2_fu_620_p3 = {{add_ln85_reg_825}, {1'd0}};

assign p_shl_fu_601_p3 = {{trunc_ln186_1_reg_820}, {2'd0}};

assign pool1_V_address0 = zext_ln85_2_fu_656_p1;

assign select_ln78_1_fu_278_p3 = ((icmp_ln79_fu_264_p2[0:0] == 1'b1) ? add_ln78_fu_258_p2 : ap_sig_allocacmp_ic_load);

assign select_ln78_2_fu_469_p3 = ((icmp_ln79_reg_778[0:0] == 1'b1) ? p_mid143 : empty_43_fu_389_p2);

assign select_ln78_3_fu_475_p3 = ((icmp_ln79_reg_778[0:0] == 1'b1) ? notlhs_mid147 : notlhs_fu_395_p2);

assign select_ln78_4_fu_481_p3 = ((icmp_ln79_reg_778[0:0] == 1'b1) ? notrhs_mid149 : notrhs_fu_401_p2);

assign select_ln78_fu_270_p3 = ((icmp_ln79_fu_264_p2[0:0] == 1'b1) ? 2'd0 : ap_sig_allocacmp_ky_1);

assign select_ln79_1_fu_324_p3 = ((and_ln78_fu_298_p2[0:0] == 1'b1) ? add_ln79_fu_304_p2 : select_ln78_fu_270_p3);

assign select_ln79_2_fu_522_p3 = ((and_ln78_reg_792[0:0] == 1'b1) ? p_mid121_fu_516_p2 : select_ln78_2_fu_469_p3);

assign select_ln79_3_fu_549_p3 = ((and_ln78_reg_792[0:0] == 1'b1) ? notlhs_mid1_fu_543_p2 : select_ln78_3_fu_475_p3);

assign select_ln79_4_fu_562_p3 = ((and_ln78_reg_792[0:0] == 1'b1) ? notrhs_mid1_fu_556_p2 : select_ln78_4_fu_481_p3);

assign select_ln79_5_fu_344_p3 = ((icmp_ln79_fu_264_p2[0:0] == 1'b1) ? 4'd1 : add_ln79_1_fu_338_p2);

assign select_ln79_fu_316_p3 = ((or_ln79_fu_310_p2[0:0] == 1'b1) ? 2'd0 : ap_sig_allocacmp_kx_load);

assign sext_ln74_cast_fu_193_p1 = $signed(sext_ln74);

assign sext_ln78_fu_465_p1 = $signed(sub_ln85_fu_459_p2);

assign sext_ln83_fu_574_p1 = $signed(add_ln83_fu_569_p2);

assign sext_ln85_1_fu_647_p1 = add_ln83_1_reg_835;

assign sext_ln85_fu_529_p1 = $signed(select_ln79_2_fu_522_p3);

assign sub_ln186_1_fu_608_p2 = (p_shl_fu_601_p3 - trunc_ln186_reg_815);

assign sub_ln186_fu_431_p2 = (zext_ln186_3_fu_427_p1 - zext_ln186_2_fu_415_p1);

assign sub_ln85_1_fu_627_p2 = (p_shl1_fu_613_p3 - p_shl2_fu_620_p3);

assign sub_ln85_fu_459_p2 = (zext_ln85_fu_444_p1 - zext_ln85_1_fu_455_p1);

assign tmp_1_fu_448_p3 = {{select_ln78_1_reg_785}, {1'd0}};

assign tmp_fu_419_p3 = {{add_ln186_fu_410_p2}, {2'd0}};

assign tmp_s_fu_437_p3 = {{select_ln78_1_reg_785}, {4'd0}};

assign trunc_ln186_1_fu_500_p1 = add_ln186_1_fu_490_p2[8:0];

assign trunc_ln186_fu_496_p1 = add_ln186_1_fu_490_p2[10:0];

assign trunc_ln85_fu_539_p1 = add_ln85_fu_533_p2[6:0];

assign xor_ln78_fu_286_p2 = (icmp_ln79_fu_264_p2 ^ 1'd1);

assign zext_ln186_1_fu_407_p1 = select_ln78_1_reg_785;

assign zext_ln186_2_fu_415_p1 = add_ln186_fu_410_p2;

assign zext_ln186_3_fu_427_p1 = tmp_fu_419_p3;

assign zext_ln186_4_fu_487_p1 = select_ln79_1_reg_810;

assign zext_ln186_5_fu_633_p1 = select_ln79_reg_804_pp0_iter1_reg;

assign zext_ln186_6_fu_642_p1 = add_ln186_2_fu_636_p2;

assign zext_ln186_cast_fu_197_p1 = zext_ln186;

assign zext_ln76_1_cast_fu_189_p1 = zext_ln76_1;

assign zext_ln79_1_fu_504_p1 = add_ln79_reg_799;

assign zext_ln79_fu_377_p1 = ky_1_reg_769;

assign zext_ln85_1_fu_455_p1 = tmp_1_fu_448_p3;

assign zext_ln85_2_fu_656_p1 = add_ln85_1_fu_650_p2;

assign zext_ln85_fu_444_p1 = tmp_s_fu_437_p3;

always @ (posedge ap_clk) begin
    zext_ln76_1_cast_reg_759[4] <= 1'b0;
    zext_ln186_cast_reg_764[8] <= 1'b0;
end

endmodule //cnn_accel_cnn_accel_Pipeline_VITIS_LOOP_78_3_VITIS_LOOP_79_4_VITIS_LOOP_80_5
