// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module cnn_accel_cnn_accel_Pipeline_pool2_loop_VITIS_LOOP_102_1_VITIS_LOOP_103_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        cnn_accel_ap_int_8_const_ap_uint_4_conv2_address0,
        cnn_accel_ap_int_8_const_ap_uint_4_conv2_ce0,
        cnn_accel_ap_int_8_const_ap_uint_4_conv2_q0,
        cnn_accel_ap_int_8_const_ap_uint_4_conv2_address1,
        cnn_accel_ap_int_8_const_ap_uint_4_conv2_ce1,
        cnn_accel_ap_int_8_const_ap_uint_4_conv2_q1,
        cnn_accel_ap_int_8_const_ap_uint_4_conv2_2_address0,
        cnn_accel_ap_int_8_const_ap_uint_4_conv2_2_ce0,
        cnn_accel_ap_int_8_const_ap_uint_4_conv2_2_q0,
        cnn_accel_ap_int_8_const_ap_uint_4_conv2_2_address1,
        cnn_accel_ap_int_8_const_ap_uint_4_conv2_2_ce1,
        cnn_accel_ap_int_8_const_ap_uint_4_conv2_2_q1,
        pool2_V_address0,
        pool2_V_ce0,
        pool2_V_we0,
        pool2_V_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [10:0] cnn_accel_ap_int_8_const_ap_uint_4_conv2_address0;
output   cnn_accel_ap_int_8_const_ap_uint_4_conv2_ce0;
input  [7:0] cnn_accel_ap_int_8_const_ap_uint_4_conv2_q0;
output  [10:0] cnn_accel_ap_int_8_const_ap_uint_4_conv2_address1;
output   cnn_accel_ap_int_8_const_ap_uint_4_conv2_ce1;
input  [7:0] cnn_accel_ap_int_8_const_ap_uint_4_conv2_q1;
output  [10:0] cnn_accel_ap_int_8_const_ap_uint_4_conv2_2_address0;
output   cnn_accel_ap_int_8_const_ap_uint_4_conv2_2_ce0;
input  [7:0] cnn_accel_ap_int_8_const_ap_uint_4_conv2_2_q0;
output  [10:0] cnn_accel_ap_int_8_const_ap_uint_4_conv2_2_address1;
output   cnn_accel_ap_int_8_const_ap_uint_4_conv2_2_ce1;
input  [7:0] cnn_accel_ap_int_8_const_ap_uint_4_conv2_2_q1;
output  [9:0] pool2_V_address0;
output   pool2_V_ce0;
output   pool2_V_we0;
output  [7:0] pool2_V_d0;

reg ap_idle;
reg cnn_accel_ap_int_8_const_ap_uint_4_conv2_ce0;
reg cnn_accel_ap_int_8_const_ap_uint_4_conv2_ce1;
reg cnn_accel_ap_int_8_const_ap_uint_4_conv2_2_ce0;
reg cnn_accel_ap_int_8_const_ap_uint_4_conv2_2_ce1;
reg pool2_V_ce0;
reg pool2_V_we0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln101_fu_179_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire   [2:0] select_ln102_fu_287_p3;
reg   [2:0] select_ln102_reg_524;
wire   [9:0] add_ln105_fu_307_p2;
reg   [9:0] add_ln105_reg_530;
wire   [6:0] trunc_ln105_fu_313_p1;
reg   [6:0] trunc_ln105_reg_537;
wire   [9:0] add_ln112_fu_395_p2;
reg   [9:0] add_ln112_reg_542;
reg   [9:0] add_ln112_reg_542_pp0_iter2_reg;
reg   [9:0] add_ln112_reg_542_pp0_iter3_reg;
wire   [63:0] zext_ln105_4_fu_418_p1;
reg   [63:0] zext_ln105_4_reg_547;
wire   [63:0] zext_ln106_1_fu_439_p1;
reg   [63:0] zext_ln106_1_reg_557;
wire   [7:0] m_V_1_fu_450_p3;
reg   [7:0] m_V_1_reg_577;
reg   [7:0] v3_V_reg_583;
wire   [7:0] m_V_3_fu_463_p3;
reg   [7:0] m_V_3_reg_589;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln112_1_fu_470_p1;
reg   [2:0] x_fu_68;
wire   [2:0] add_ln103_fu_317_p2;
wire    ap_loop_init;
reg   [2:0] ap_sig_allocacmp_x_load;
reg   [2:0] y_2_fu_72;
wire   [2:0] select_ln102_1_fu_295_p3;
reg   [2:0] ap_sig_allocacmp_y_2_load;
reg   [5:0] indvar_flatten86_fu_76;
wire   [5:0] select_ln102_2_fu_329_p3;
reg   [5:0] ap_sig_allocacmp_indvar_flatten86_load;
reg   [4:0] c_fu_80;
wire   [4:0] select_ln101_1_fu_223_p3;
reg   [4:0] ap_sig_allocacmp_c_load;
reg   [9:0] indvar_flatten100_fu_84;
wire   [9:0] add_ln101_1_fu_185_p2;
reg   [9:0] ap_sig_allocacmp_indvar_flatten100_load;
wire   [0:0] icmp_ln102_fu_209_p2;
wire   [4:0] add_ln101_fu_203_p2;
wire   [7:0] tmp_s_fu_235_p3;
wire   [8:0] zext_ln105_1_fu_243_p1;
wire   [8:0] zext_ln105_fu_231_p1;
wire   [8:0] sub_ln105_fu_247_p2;
wire   [0:0] icmp_ln103_fu_263_p2;
wire   [0:0] xor_ln101_fu_257_p2;
wire   [2:0] select_ln101_fu_215_p3;
wire   [0:0] and_ln101_fu_269_p2;
wire   [0:0] or_ln102_fu_281_p2;
wire   [2:0] add_ln102_fu_275_p2;
wire  signed [9:0] sext_ln102_fu_253_p1;
wire   [9:0] zext_ln105_2_fu_303_p1;
wire   [5:0] add_ln102_1_fu_323_p2;
wire   [10:0] p_shl9_fu_362_p3;
wire   [10:0] p_shl_fu_369_p3;
wire   [9:0] shl_ln112_fu_382_p2;
wire   [9:0] sub_ln112_fu_387_p2;
wire   [9:0] zext_ln112_fu_392_p1;
wire   [3:0] shl_ln1_fu_401_p3;
wire   [10:0] sub_ln105_1_fu_376_p2;
wire   [10:0] zext_ln105_3_fu_408_p1;
wire   [10:0] add_ln105_1_fu_412_p2;
wire   [3:0] or_ln106_fu_423_p2;
wire   [10:0] zext_ln106_fu_429_p1;
wire   [10:0] add_ln106_fu_433_p2;
wire   [0:0] icmp_ln1035_fu_444_p2;
wire   [0:0] icmp_ln1035_1_fu_458_p2;
wire   [0:0] icmp_ln1035_2_fu_474_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_done_reg = 1'b0;
end

cnn_accel_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln101_fu_179_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            c_fu_80 <= select_ln101_1_fu_223_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            c_fu_80 <= 5'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln101_fu_179_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten100_fu_84 <= add_ln101_1_fu_185_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten100_fu_84 <= 10'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln101_fu_179_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten86_fu_76 <= select_ln102_2_fu_329_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten86_fu_76 <= 6'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln101_fu_179_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            x_fu_68 <= add_ln103_fu_317_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            x_fu_68 <= 3'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln101_fu_179_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            y_2_fu_72 <= select_ln102_1_fu_295_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            y_2_fu_72 <= 3'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln101_fu_179_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln105_reg_530 <= add_ln105_fu_307_p2;
        select_ln102_reg_524 <= select_ln102_fu_287_p3;
        trunc_ln105_reg_537 <= trunc_ln105_fu_313_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln112_reg_542 <= add_ln112_fu_395_p2;
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        zext_ln105_4_reg_547[10 : 1] <= zext_ln105_4_fu_418_p1[10 : 1];
        zext_ln106_1_reg_557[10 : 1] <= zext_ln106_1_fu_439_p1[10 : 1];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        add_ln112_reg_542_pp0_iter2_reg <= add_ln112_reg_542;
        add_ln112_reg_542_pp0_iter3_reg <= add_ln112_reg_542_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        m_V_1_reg_577 <= m_V_1_fu_450_p3;
        m_V_3_reg_589 <= m_V_3_fu_463_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        v3_V_reg_583 <= cnn_accel_ap_int_8_const_ap_uint_4_conv2_2_q0;
    end
end

always @ (*) begin
    if (((icmp_ln101_fu_179_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_c_load = 5'd0;
    end else begin
        ap_sig_allocacmp_c_load = c_fu_80;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten100_load = 10'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten100_load = indvar_flatten100_fu_84;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten86_load = 6'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten86_load = indvar_flatten86_fu_76;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_x_load = 3'd0;
    end else begin
        ap_sig_allocacmp_x_load = x_fu_68;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_y_2_load = 3'd0;
    end else begin
        ap_sig_allocacmp_y_2_load = y_2_fu_72;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        cnn_accel_ap_int_8_const_ap_uint_4_conv2_2_ce0 = 1'b1;
    end else begin
        cnn_accel_ap_int_8_const_ap_uint_4_conv2_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        cnn_accel_ap_int_8_const_ap_uint_4_conv2_2_ce1 = 1'b1;
    end else begin
        cnn_accel_ap_int_8_const_ap_uint_4_conv2_2_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        cnn_accel_ap_int_8_const_ap_uint_4_conv2_ce0 = 1'b1;
    end else begin
        cnn_accel_ap_int_8_const_ap_uint_4_conv2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        cnn_accel_ap_int_8_const_ap_uint_4_conv2_ce1 = 1'b1;
    end else begin
        cnn_accel_ap_int_8_const_ap_uint_4_conv2_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        pool2_V_ce0 = 1'b1;
    end else begin
        pool2_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        pool2_V_we0 = 1'b1;
    end else begin
        pool2_V_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln101_1_fu_185_p2 = (ap_sig_allocacmp_indvar_flatten100_load + 10'd1);

assign add_ln101_fu_203_p2 = (ap_sig_allocacmp_c_load + 5'd1);

assign add_ln102_1_fu_323_p2 = (ap_sig_allocacmp_indvar_flatten86_load + 6'd1);

assign add_ln102_fu_275_p2 = (select_ln101_fu_215_p3 + 3'd1);

assign add_ln103_fu_317_p2 = (select_ln102_fu_287_p3 + 3'd1);

assign add_ln105_1_fu_412_p2 = (sub_ln105_1_fu_376_p2 + zext_ln105_3_fu_408_p1);

assign add_ln105_fu_307_p2 = ($signed(sext_ln102_fu_253_p1) + $signed(zext_ln105_2_fu_303_p1));

assign add_ln106_fu_433_p2 = (sub_ln105_1_fu_376_p2 + zext_ln106_fu_429_p1);

assign add_ln112_fu_395_p2 = (sub_ln112_fu_387_p2 + zext_ln112_fu_392_p1);

assign and_ln101_fu_269_p2 = (xor_ln101_fu_257_p2 & icmp_ln103_fu_263_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign cnn_accel_ap_int_8_const_ap_uint_4_conv2_2_address0 = zext_ln106_1_reg_557;

assign cnn_accel_ap_int_8_const_ap_uint_4_conv2_2_address1 = zext_ln105_4_reg_547;

assign cnn_accel_ap_int_8_const_ap_uint_4_conv2_address0 = zext_ln106_1_fu_439_p1;

assign cnn_accel_ap_int_8_const_ap_uint_4_conv2_address1 = zext_ln105_4_fu_418_p1;

assign icmp_ln101_fu_179_p2 = ((ap_sig_allocacmp_indvar_flatten100_load == 10'd784) ? 1'b1 : 1'b0);

assign icmp_ln102_fu_209_p2 = ((ap_sig_allocacmp_indvar_flatten86_load == 6'd49) ? 1'b1 : 1'b0);

assign icmp_ln1035_1_fu_458_p2 = (($signed(cnn_accel_ap_int_8_const_ap_uint_4_conv2_2_q1) > $signed(m_V_1_reg_577)) ? 1'b1 : 1'b0);

assign icmp_ln1035_2_fu_474_p2 = (($signed(v3_V_reg_583) > $signed(m_V_3_reg_589)) ? 1'b1 : 1'b0);

assign icmp_ln1035_fu_444_p2 = (($signed(cnn_accel_ap_int_8_const_ap_uint_4_conv2_q0) > $signed(cnn_accel_ap_int_8_const_ap_uint_4_conv2_q1)) ? 1'b1 : 1'b0);

assign icmp_ln103_fu_263_p2 = ((ap_sig_allocacmp_x_load == 3'd7) ? 1'b1 : 1'b0);

assign m_V_1_fu_450_p3 = ((icmp_ln1035_fu_444_p2[0:0] == 1'b1) ? cnn_accel_ap_int_8_const_ap_uint_4_conv2_q0 : cnn_accel_ap_int_8_const_ap_uint_4_conv2_q1);

assign m_V_3_fu_463_p3 = ((icmp_ln1035_1_fu_458_p2[0:0] == 1'b1) ? cnn_accel_ap_int_8_const_ap_uint_4_conv2_2_q1 : m_V_1_reg_577);

assign or_ln102_fu_281_p2 = (icmp_ln102_fu_209_p2 | and_ln101_fu_269_p2);

assign or_ln106_fu_423_p2 = (shl_ln1_fu_401_p3 | 4'd1);

assign p_shl9_fu_362_p3 = {{trunc_ln105_reg_537}, {4'd0}};

assign p_shl_fu_369_p3 = {{add_ln105_reg_530}, {1'd0}};

assign pool2_V_address0 = zext_ln112_1_fu_470_p1;

assign pool2_V_d0 = ((icmp_ln1035_2_fu_474_p2[0:0] == 1'b1) ? v3_V_reg_583 : m_V_3_reg_589);

assign select_ln101_1_fu_223_p3 = ((icmp_ln102_fu_209_p2[0:0] == 1'b1) ? add_ln101_fu_203_p2 : ap_sig_allocacmp_c_load);

assign select_ln101_fu_215_p3 = ((icmp_ln102_fu_209_p2[0:0] == 1'b1) ? 3'd0 : ap_sig_allocacmp_y_2_load);

assign select_ln102_1_fu_295_p3 = ((and_ln101_fu_269_p2[0:0] == 1'b1) ? add_ln102_fu_275_p2 : select_ln101_fu_215_p3);

assign select_ln102_2_fu_329_p3 = ((icmp_ln102_fu_209_p2[0:0] == 1'b1) ? 6'd1 : add_ln102_1_fu_323_p2);

assign select_ln102_fu_287_p3 = ((or_ln102_fu_281_p2[0:0] == 1'b1) ? 3'd0 : ap_sig_allocacmp_x_load);

assign sext_ln102_fu_253_p1 = $signed(sub_ln105_fu_247_p2);

assign shl_ln112_fu_382_p2 = add_ln105_reg_530 << 10'd3;

assign shl_ln1_fu_401_p3 = {{select_ln102_reg_524}, {1'd0}};

assign sub_ln105_1_fu_376_p2 = (p_shl9_fu_362_p3 - p_shl_fu_369_p3);

assign sub_ln105_fu_247_p2 = (zext_ln105_1_fu_243_p1 - zext_ln105_fu_231_p1);

assign sub_ln112_fu_387_p2 = (shl_ln112_fu_382_p2 - add_ln105_reg_530);

assign tmp_s_fu_235_p3 = {{select_ln101_1_fu_223_p3}, {3'd0}};

assign trunc_ln105_fu_313_p1 = add_ln105_fu_307_p2[6:0];

assign xor_ln101_fu_257_p2 = (icmp_ln102_fu_209_p2 ^ 1'd1);

assign zext_ln105_1_fu_243_p1 = tmp_s_fu_235_p3;

assign zext_ln105_2_fu_303_p1 = select_ln102_1_fu_295_p3;

assign zext_ln105_3_fu_408_p1 = shl_ln1_fu_401_p3;

assign zext_ln105_4_fu_418_p1 = add_ln105_1_fu_412_p2;

assign zext_ln105_fu_231_p1 = select_ln101_1_fu_223_p3;

assign zext_ln106_1_fu_439_p1 = add_ln106_fu_433_p2;

assign zext_ln106_fu_429_p1 = or_ln106_fu_423_p2;

assign zext_ln112_1_fu_470_p1 = add_ln112_reg_542_pp0_iter3_reg;

assign zext_ln112_fu_392_p1 = select_ln102_reg_524;

always @ (posedge ap_clk) begin
    zext_ln105_4_reg_547[0] <= 1'b0;
    zext_ln105_4_reg_547[63:11] <= 53'b00000000000000000000000000000000000000000000000000000;
    zext_ln106_1_reg_557[0] <= 1'b1;
    zext_ln106_1_reg_557[63:11] <= 53'b00000000000000000000000000000000000000000000000000000;
end

endmodule //cnn_accel_cnn_accel_Pipeline_pool2_loop_VITIS_LOOP_102_1_VITIS_LOOP_103_2
