// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module cnn_accel_cnn_accel_Pipeline_VITIS_LOOP_128_1_VITIS_LOOP_129_2_VITIS_LOOP_130_3 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        sext_ln126,
        phi_mul,
        acc_V_21_out,
        acc_V_21_out_ap_vld,
        pool2_V_address0,
        pool2_V_ce0,
        pool2_V_q0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [8:0] sext_ln126;
input  [14:0] phi_mul;
output  [24:0] acc_V_21_out;
output   acc_V_21_out_ap_vld;
output  [9:0] pool2_V_address0;
output   pool2_V_ce0;
input  [7:0] pool2_V_q0;

reg ap_idle;
reg acc_V_21_out_ap_vld;
reg pool2_V_ce0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
wire    ap_block_state7_pp0_stage0_iter6;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln128_fu_203_p2;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [14:0] W_FC1_V_address0;
reg    W_FC1_V_ce0;
wire  signed [7:0] W_FC1_V_q0;
wire    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln128_reg_595;
reg   [0:0] icmp_ln128_reg_595_pp0_iter2_reg;
reg   [0:0] icmp_ln128_reg_595_pp0_iter3_reg;
reg   [0:0] icmp_ln128_reg_595_pp0_iter4_reg;
wire   [9:0] add_ln128_1_fu_239_p2;
reg   [9:0] add_ln128_1_reg_599;
wire   [0:0] icmp_ln129_fu_245_p2;
reg   [0:0] icmp_ln129_reg_604;
wire   [0:0] and_ln128_fu_313_p2;
reg   [0:0] and_ln128_reg_609;
wire   [9:0] add_ln129_1_fu_333_p2;
reg   [9:0] add_ln129_1_reg_614;
wire   [2:0] select_ln129_1_fu_345_p3;
reg   [2:0] select_ln129_1_reg_619;
wire   [9:0] add_ln132_fu_365_p2;
reg   [9:0] add_ln132_reg_624;
wire   [63:0] zext_ln132_4_fu_468_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln186_8_fu_482_p1;
reg   [24:0] acc_V_fu_70;
wire  signed [24:0] grp_fu_517_p3;
wire  signed [24:0] sext_ln126_cast_fu_151_p1;
reg  signed [24:0] ap_sig_allocacmp_acc_V_load_2;
wire    ap_loop_init;
reg   [2:0] x_fu_74;
wire   [2:0] add_ln130_fu_379_p2;
reg   [9:0] idx_1_fu_78;
wire   [9:0] add_ln133_fu_487_p2;
reg   [2:0] y_fu_82;
wire   [2:0] select_ln129_2_fu_353_p3;
reg   [9:0] idx_fu_86;
wire   [9:0] select_ln129_3_fu_371_p3;
reg   [5:0] indvar_flatten107_fu_90;
wire   [5:0] select_ln129_4_fu_391_p3;
reg   [4:0] c_fu_94;
wire   [4:0] select_ln128_3_fu_267_p3;
reg   [9:0] indvars_iv161_fu_98;
wire   [9:0] select_ln128_4_fu_319_p3;
reg   [9:0] indvar_flatten125_fu_102;
wire   [9:0] add_ln128_2_fu_209_p2;
wire    ap_block_pp0_stage0_01001;
wire   [4:0] add_ln128_fu_233_p2;
wire   [7:0] tmp_s_fu_279_p3;
wire   [8:0] zext_ln132_1_fu_287_p1;
wire   [8:0] zext_ln132_fu_275_p1;
wire   [8:0] sub_ln132_fu_291_p2;
wire   [0:0] icmp_ln130_fu_307_p2;
wire   [0:0] xor_ln128_fu_301_p2;
wire   [2:0] select_ln128_1_fu_259_p3;
wire   [9:0] select_ln128_fu_251_p3;
wire   [0:0] or_ln129_fu_339_p2;
wire   [2:0] add_ln129_fu_327_p2;
wire  signed [9:0] sext_ln129_fu_297_p1;
wire   [9:0] zext_ln132_2_fu_361_p1;
wire   [5:0] add_ln129_2_fu_385_p2;
wire   [9:0] select_ln128_2_fu_437_p3;
wire   [9:0] shl_ln132_fu_449_p2;
wire   [9:0] sub_ln132_1_fu_454_p2;
wire   [9:0] zext_ln132_3_fu_459_p1;
wire   [9:0] add_ln132_1_fu_462_p2;
wire   [9:0] select_ln129_fu_443_p3;
wire   [14:0] zext_ln186_fu_473_p1;
wire   [14:0] add_ln186_fu_477_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_done_reg = 1'b0;
end

cnn_accel_cnn_accel_Pipeline_VITIS_LOOP_128_1_VITIS_LOOP_129_2_VITIS_LOOP_130_3_W_FC1_Vcud #(
    .DataWidth( 8 ),
    .AddressRange( 25088 ),
    .AddressWidth( 15 ))
W_FC1_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(W_FC1_V_address0),
    .ce0(W_FC1_V_ce0),
    .q0(W_FC1_V_q0)
);

cnn_accel_mac_muladd_8s_8s_25s_25_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 25 ),
    .dout_WIDTH( 25 ))
mac_muladd_8s_8s_25s_25_4_1_U49(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(W_FC1_V_q0),
    .din1(pool2_V_q0),
    .din2(ap_sig_allocacmp_acc_V_load_2),
    .ce(1'b1),
    .dout(grp_fu_517_p3)
);

cnn_accel_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter1_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter5_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            acc_V_fu_70 <= sext_ln126_cast_fu_151_p1;
        end else if ((ap_enable_reg_pp0_iter6 == 1'b1)) begin
            acc_V_fu_70 <= grp_fu_517_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            c_fu_94 <= 5'd0;
        end else if (((icmp_ln128_fu_203_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            c_fu_94 <= select_ln128_3_fu_267_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            idx_1_fu_78 <= 10'd0;
        end else if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
            idx_1_fu_78 <= add_ln133_fu_487_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            idx_fu_86 <= 10'd0;
        end else if (((icmp_ln128_fu_203_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            idx_fu_86 <= select_ln129_3_fu_371_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten107_fu_90 <= 6'd0;
        end else if (((icmp_ln128_fu_203_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            indvar_flatten107_fu_90 <= select_ln129_4_fu_391_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten125_fu_102 <= 10'd0;
        end else if (((icmp_ln128_fu_203_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            indvar_flatten125_fu_102 <= add_ln128_2_fu_209_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvars_iv161_fu_98 <= 10'd0;
        end else if (((icmp_ln128_fu_203_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            indvars_iv161_fu_98 <= select_ln128_4_fu_319_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            x_fu_74 <= 3'd0;
        end else if (((icmp_ln128_fu_203_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            x_fu_74 <= add_ln130_fu_379_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            y_fu_82 <= 3'd0;
        end else if (((icmp_ln128_fu_203_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            y_fu_82 <= select_ln129_2_fu_353_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln128_fu_203_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln128_1_reg_599 <= add_ln128_1_fu_239_p2;
        add_ln129_1_reg_614 <= add_ln129_1_fu_333_p2;
        add_ln132_reg_624 <= add_ln132_fu_365_p2;
        and_ln128_reg_609 <= and_ln128_fu_313_p2;
        icmp_ln129_reg_604 <= icmp_ln129_fu_245_p2;
        select_ln129_1_reg_619 <= select_ln129_1_fu_345_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
        icmp_ln128_reg_595 <= icmp_ln128_fu_203_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        icmp_ln128_reg_595_pp0_iter2_reg <= icmp_ln128_reg_595;
        icmp_ln128_reg_595_pp0_iter3_reg <= icmp_ln128_reg_595_pp0_iter2_reg;
        icmp_ln128_reg_595_pp0_iter4_reg <= icmp_ln128_reg_595_pp0_iter3_reg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        W_FC1_V_ce0 = 1'b1;
    end else begin
        W_FC1_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln128_reg_595_pp0_iter4_reg == 1'd1))) begin
        acc_V_21_out_ap_vld = 1'b1;
    end else begin
        acc_V_21_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln128_fu_203_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter5_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter6 == 1'b1))) begin
        ap_sig_allocacmp_acc_V_load_2 = grp_fu_517_p3;
    end else begin
        ap_sig_allocacmp_acc_V_load_2 = acc_V_fu_70;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        pool2_V_ce0 = 1'b1;
    end else begin
        pool2_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign W_FC1_V_address0 = zext_ln186_8_fu_482_p1;

assign acc_V_21_out = acc_V_fu_70;

assign add_ln128_1_fu_239_p2 = (indvars_iv161_fu_98 + 10'd49);

assign add_ln128_2_fu_209_p2 = (indvar_flatten125_fu_102 + 10'd1);

assign add_ln128_fu_233_p2 = (c_fu_94 + 5'd1);

assign add_ln129_1_fu_333_p2 = (select_ln128_fu_251_p3 + 10'd7);

assign add_ln129_2_fu_385_p2 = (indvar_flatten107_fu_90 + 6'd1);

assign add_ln129_fu_327_p2 = (select_ln128_1_fu_259_p3 + 3'd1);

assign add_ln130_fu_379_p2 = (select_ln129_1_fu_345_p3 + 3'd1);

assign add_ln132_1_fu_462_p2 = (sub_ln132_1_fu_454_p2 + zext_ln132_3_fu_459_p1);

assign add_ln132_fu_365_p2 = ($signed(sext_ln129_fu_297_p1) + $signed(zext_ln132_2_fu_361_p1));

assign add_ln133_fu_487_p2 = (select_ln129_fu_443_p3 + 10'd1);

assign add_ln186_fu_477_p2 = (phi_mul + zext_ln186_fu_473_p1);

assign and_ln128_fu_313_p2 = (xor_ln128_fu_301_p2 & icmp_ln130_fu_307_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter1_stage0;

assign icmp_ln128_fu_203_p2 = ((indvar_flatten125_fu_102 == 10'd784) ? 1'b1 : 1'b0);

assign icmp_ln129_fu_245_p2 = ((indvar_flatten107_fu_90 == 6'd49) ? 1'b1 : 1'b0);

assign icmp_ln130_fu_307_p2 = ((x_fu_74 == 3'd7) ? 1'b1 : 1'b0);

assign or_ln129_fu_339_p2 = (icmp_ln129_fu_245_p2 | and_ln128_fu_313_p2);

assign pool2_V_address0 = zext_ln132_4_fu_468_p1;

assign select_ln128_1_fu_259_p3 = ((icmp_ln129_fu_245_p2[0:0] == 1'b1) ? 3'd0 : y_fu_82);

assign select_ln128_2_fu_437_p3 = ((icmp_ln129_reg_604[0:0] == 1'b1) ? add_ln128_1_reg_599 : idx_1_fu_78);

assign select_ln128_3_fu_267_p3 = ((icmp_ln129_fu_245_p2[0:0] == 1'b1) ? add_ln128_fu_233_p2 : c_fu_94);

assign select_ln128_4_fu_319_p3 = ((icmp_ln129_fu_245_p2[0:0] == 1'b1) ? add_ln128_1_fu_239_p2 : indvars_iv161_fu_98);

assign select_ln128_fu_251_p3 = ((icmp_ln129_fu_245_p2[0:0] == 1'b1) ? add_ln128_1_fu_239_p2 : idx_fu_86);

assign select_ln129_1_fu_345_p3 = ((or_ln129_fu_339_p2[0:0] == 1'b1) ? 3'd0 : x_fu_74);

assign select_ln129_2_fu_353_p3 = ((and_ln128_fu_313_p2[0:0] == 1'b1) ? add_ln129_fu_327_p2 : select_ln128_1_fu_259_p3);

assign select_ln129_3_fu_371_p3 = ((and_ln128_fu_313_p2[0:0] == 1'b1) ? add_ln129_1_fu_333_p2 : select_ln128_fu_251_p3);

assign select_ln129_4_fu_391_p3 = ((icmp_ln129_fu_245_p2[0:0] == 1'b1) ? 6'd1 : add_ln129_2_fu_385_p2);

assign select_ln129_fu_443_p3 = ((and_ln128_reg_609[0:0] == 1'b1) ? add_ln129_1_reg_614 : select_ln128_2_fu_437_p3);

assign sext_ln126_cast_fu_151_p1 = $signed(sext_ln126);

assign sext_ln129_fu_297_p1 = $signed(sub_ln132_fu_291_p2);

assign shl_ln132_fu_449_p2 = add_ln132_reg_624 << 10'd3;

assign sub_ln132_1_fu_454_p2 = (shl_ln132_fu_449_p2 - add_ln132_reg_624);

assign sub_ln132_fu_291_p2 = (zext_ln132_1_fu_287_p1 - zext_ln132_fu_275_p1);

assign tmp_s_fu_279_p3 = {{select_ln128_3_fu_267_p3}, {3'd0}};

assign xor_ln128_fu_301_p2 = (icmp_ln129_fu_245_p2 ^ 1'd1);

assign zext_ln132_1_fu_287_p1 = tmp_s_fu_279_p3;

assign zext_ln132_2_fu_361_p1 = select_ln129_2_fu_353_p3;

assign zext_ln132_3_fu_459_p1 = select_ln129_1_reg_619;

assign zext_ln132_4_fu_468_p1 = add_ln132_1_fu_462_p2;

assign zext_ln132_fu_275_p1 = select_ln128_3_fu_267_p3;

assign zext_ln186_8_fu_482_p1 = add_ln186_fu_477_p2;

assign zext_ln186_fu_473_p1 = select_ln129_fu_443_p3;

endmodule //cnn_accel_cnn_accel_Pipeline_VITIS_LOOP_128_1_VITIS_LOOP_129_2_VITIS_LOOP_130_3
