// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module cnn_accel_fc1_layer (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        cnn_accel_ap_int_8_const_ap_uint_4_pool2_address0,
        cnn_accel_ap_int_8_const_ap_uint_4_pool2_ce0,
        cnn_accel_ap_int_8_const_ap_uint_4_pool2_q0,
        cnn_accel_ap_int_8_const_ap_uint_4_pool2_address1,
        cnn_accel_ap_int_8_const_ap_uint_4_pool2_ce1,
        cnn_accel_ap_int_8_const_ap_uint_4_pool2_q1,
        cnn_accel_ap_int_8_const_ap_uint_4_pool2_3_address0,
        cnn_accel_ap_int_8_const_ap_uint_4_pool2_3_ce0,
        cnn_accel_ap_int_8_const_ap_uint_4_pool2_3_q0,
        cnn_accel_ap_int_8_const_ap_uint_4_pool2_3_address1,
        cnn_accel_ap_int_8_const_ap_uint_4_pool2_3_ce1,
        cnn_accel_ap_int_8_const_ap_uint_4_pool2_3_q1,
        cnn_accel_ap_int_8_const_ap_uint_4_pool2_4_address0,
        cnn_accel_ap_int_8_const_ap_uint_4_pool2_4_ce0,
        cnn_accel_ap_int_8_const_ap_uint_4_pool2_4_q0,
        cnn_accel_ap_int_8_const_ap_uint_4_pool2_4_address1,
        cnn_accel_ap_int_8_const_ap_uint_4_pool2_4_ce1,
        cnn_accel_ap_int_8_const_ap_uint_4_pool2_4_q1,
        cnn_accel_ap_int_8_const_ap_uint_4_pool2_5_address0,
        cnn_accel_ap_int_8_const_ap_uint_4_pool2_5_ce0,
        cnn_accel_ap_int_8_const_ap_uint_4_pool2_5_q0,
        cnn_accel_ap_int_8_const_ap_uint_4_fc1,
        cnn_accel_ap_int_8_const_ap_uint_4_fc1_ap_vld,
        cnn_accel_ap_int_8_const_ap_uint_4_fc1_6,
        cnn_accel_ap_int_8_const_ap_uint_4_fc1_6_ap_vld,
        cnn_accel_ap_int_8_const_ap_uint_4_fc1_7,
        cnn_accel_ap_int_8_const_ap_uint_4_fc1_7_ap_vld,
        cnn_accel_ap_int_8_const_ap_uint_4_fc1_8,
        cnn_accel_ap_int_8_const_ap_uint_4_fc1_8_ap_vld,
        cnn_accel_ap_int_8_const_ap_uint_4_fc1_9,
        cnn_accel_ap_int_8_const_ap_uint_4_fc1_9_ap_vld,
        cnn_accel_ap_int_8_const_ap_uint_4_fc1_10,
        cnn_accel_ap_int_8_const_ap_uint_4_fc1_10_ap_vld,
        cnn_accel_ap_int_8_const_ap_uint_4_fc1_11,
        cnn_accel_ap_int_8_const_ap_uint_4_fc1_11_ap_vld,
        cnn_accel_ap_int_8_const_ap_uint_4_fc1_12,
        cnn_accel_ap_int_8_const_ap_uint_4_fc1_12_ap_vld,
        cnn_accel_ap_int_8_const_ap_uint_4_fc1_13,
        cnn_accel_ap_int_8_const_ap_uint_4_fc1_13_ap_vld,
        cnn_accel_ap_int_8_const_ap_uint_4_fc1_14,
        cnn_accel_ap_int_8_const_ap_uint_4_fc1_14_ap_vld,
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_10,
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_10_ap_vld,
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_11,
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_11_ap_vld,
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_12,
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_12_ap_vld,
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_13,
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_13_ap_vld,
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_14,
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_14_ap_vld,
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_15,
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_15_ap_vld,
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_16,
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_16_ap_vld,
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_17,
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_17_ap_vld,
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_18,
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_18_ap_vld,
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_19,
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_19_ap_vld,
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_20,
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_20_ap_vld,
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_21,
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_21_ap_vld,
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_22,
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_22_ap_vld,
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_23,
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_23_ap_vld,
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_24,
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_24_ap_vld,
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_25,
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_25_ap_vld,
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_26,
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_26_ap_vld,
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_27,
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_27_ap_vld,
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_28,
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_28_ap_vld,
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_29,
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_29_ap_vld,
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_30,
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_30_ap_vld,
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_31,
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_31_ap_vld,
        grp_fu_1102_p_din0,
        grp_fu_1102_p_din1,
        grp_fu_1102_p_dout0,
        grp_fu_1102_p_ce
);

parameter    ap_ST_fsm_state1 = 7'd1;
parameter    ap_ST_fsm_state2 = 7'd2;
parameter    ap_ST_fsm_state3 = 7'd4;
parameter    ap_ST_fsm_state4 = 7'd8;
parameter    ap_ST_fsm_state5 = 7'd16;
parameter    ap_ST_fsm_state6 = 7'd32;
parameter    ap_ST_fsm_state7 = 7'd64;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [7:0] cnn_accel_ap_int_8_const_ap_uint_4_pool2_address0;
output   cnn_accel_ap_int_8_const_ap_uint_4_pool2_ce0;
input  [7:0] cnn_accel_ap_int_8_const_ap_uint_4_pool2_q0;
output  [7:0] cnn_accel_ap_int_8_const_ap_uint_4_pool2_address1;
output   cnn_accel_ap_int_8_const_ap_uint_4_pool2_ce1;
input  [7:0] cnn_accel_ap_int_8_const_ap_uint_4_pool2_q1;
output  [7:0] cnn_accel_ap_int_8_const_ap_uint_4_pool2_3_address0;
output   cnn_accel_ap_int_8_const_ap_uint_4_pool2_3_ce0;
input  [7:0] cnn_accel_ap_int_8_const_ap_uint_4_pool2_3_q0;
output  [7:0] cnn_accel_ap_int_8_const_ap_uint_4_pool2_3_address1;
output   cnn_accel_ap_int_8_const_ap_uint_4_pool2_3_ce1;
input  [7:0] cnn_accel_ap_int_8_const_ap_uint_4_pool2_3_q1;
output  [7:0] cnn_accel_ap_int_8_const_ap_uint_4_pool2_4_address0;
output   cnn_accel_ap_int_8_const_ap_uint_4_pool2_4_ce0;
input  [7:0] cnn_accel_ap_int_8_const_ap_uint_4_pool2_4_q0;
output  [7:0] cnn_accel_ap_int_8_const_ap_uint_4_pool2_4_address1;
output   cnn_accel_ap_int_8_const_ap_uint_4_pool2_4_ce1;
input  [7:0] cnn_accel_ap_int_8_const_ap_uint_4_pool2_4_q1;
output  [7:0] cnn_accel_ap_int_8_const_ap_uint_4_pool2_5_address0;
output   cnn_accel_ap_int_8_const_ap_uint_4_pool2_5_ce0;
input  [7:0] cnn_accel_ap_int_8_const_ap_uint_4_pool2_5_q0;
output  [7:0] cnn_accel_ap_int_8_const_ap_uint_4_fc1;
output   cnn_accel_ap_int_8_const_ap_uint_4_fc1_ap_vld;
output  [7:0] cnn_accel_ap_int_8_const_ap_uint_4_fc1_6;
output   cnn_accel_ap_int_8_const_ap_uint_4_fc1_6_ap_vld;
output  [7:0] cnn_accel_ap_int_8_const_ap_uint_4_fc1_7;
output   cnn_accel_ap_int_8_const_ap_uint_4_fc1_7_ap_vld;
output  [7:0] cnn_accel_ap_int_8_const_ap_uint_4_fc1_8;
output   cnn_accel_ap_int_8_const_ap_uint_4_fc1_8_ap_vld;
output  [7:0] cnn_accel_ap_int_8_const_ap_uint_4_fc1_9;
output   cnn_accel_ap_int_8_const_ap_uint_4_fc1_9_ap_vld;
output  [7:0] cnn_accel_ap_int_8_const_ap_uint_4_fc1_10;
output   cnn_accel_ap_int_8_const_ap_uint_4_fc1_10_ap_vld;
output  [7:0] cnn_accel_ap_int_8_const_ap_uint_4_fc1_11;
output   cnn_accel_ap_int_8_const_ap_uint_4_fc1_11_ap_vld;
output  [7:0] cnn_accel_ap_int_8_const_ap_uint_4_fc1_12;
output   cnn_accel_ap_int_8_const_ap_uint_4_fc1_12_ap_vld;
output  [7:0] cnn_accel_ap_int_8_const_ap_uint_4_fc1_13;
output   cnn_accel_ap_int_8_const_ap_uint_4_fc1_13_ap_vld;
output  [7:0] cnn_accel_ap_int_8_const_ap_uint_4_fc1_14;
output   cnn_accel_ap_int_8_const_ap_uint_4_fc1_14_ap_vld;
output  [7:0] p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_10;
output   p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_10_ap_vld;
output  [7:0] p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_11;
output   p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_11_ap_vld;
output  [7:0] p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_12;
output   p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_12_ap_vld;
output  [7:0] p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_13;
output   p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_13_ap_vld;
output  [7:0] p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_14;
output   p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_14_ap_vld;
output  [7:0] p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_15;
output   p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_15_ap_vld;
output  [7:0] p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_16;
output   p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_16_ap_vld;
output  [7:0] p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_17;
output   p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_17_ap_vld;
output  [7:0] p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_18;
output   p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_18_ap_vld;
output  [7:0] p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_19;
output   p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_19_ap_vld;
output  [7:0] p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_20;
output   p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_20_ap_vld;
output  [7:0] p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_21;
output   p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_21_ap_vld;
output  [7:0] p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_22;
output   p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_22_ap_vld;
output  [7:0] p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_23;
output   p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_23_ap_vld;
output  [7:0] p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_24;
output   p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_24_ap_vld;
output  [7:0] p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_25;
output   p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_25_ap_vld;
output  [7:0] p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_26;
output   p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_26_ap_vld;
output  [7:0] p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_27;
output   p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_27_ap_vld;
output  [7:0] p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_28;
output   p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_28_ap_vld;
output  [7:0] p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_29;
output   p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_29_ap_vld;
output  [7:0] p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_30;
output   p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_30_ap_vld;
output  [7:0] p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_31;
output   p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_31_ap_vld;
output  [31:0] grp_fu_1102_p_din0;
output  [15:0] grp_fu_1102_p_din1;
input  [46:0] grp_fu_1102_p_dout0;
output   grp_fu_1102_p_ce;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg cnn_accel_ap_int_8_const_ap_uint_4_fc1_ap_vld;
reg cnn_accel_ap_int_8_const_ap_uint_4_fc1_6_ap_vld;
reg cnn_accel_ap_int_8_const_ap_uint_4_fc1_7_ap_vld;
reg cnn_accel_ap_int_8_const_ap_uint_4_fc1_8_ap_vld;
reg cnn_accel_ap_int_8_const_ap_uint_4_fc1_9_ap_vld;
reg cnn_accel_ap_int_8_const_ap_uint_4_fc1_10_ap_vld;
reg cnn_accel_ap_int_8_const_ap_uint_4_fc1_11_ap_vld;
reg cnn_accel_ap_int_8_const_ap_uint_4_fc1_12_ap_vld;
reg cnn_accel_ap_int_8_const_ap_uint_4_fc1_13_ap_vld;
reg cnn_accel_ap_int_8_const_ap_uint_4_fc1_14_ap_vld;
reg p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_10_ap_vld;
reg p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_11_ap_vld;
reg p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_12_ap_vld;
reg p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_13_ap_vld;
reg p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_14_ap_vld;
reg p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_15_ap_vld;
reg p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_16_ap_vld;
reg p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_17_ap_vld;
reg p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_18_ap_vld;
reg p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_19_ap_vld;
reg p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_20_ap_vld;
reg p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_21_ap_vld;
reg p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_22_ap_vld;
reg p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_23_ap_vld;
reg p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_24_ap_vld;
reg p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_25_ap_vld;
reg p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_26_ap_vld;
reg p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_27_ap_vld;
reg p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_28_ap_vld;
reg p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_29_ap_vld;
reg p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_30_ap_vld;
reg p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_31_ap_vld;

(* fsm_encoding = "none" *) reg   [6:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [4:0] B_FC1_V_address0;
reg    B_FC1_V_ce0;
wire   [8:0] B_FC1_V_q0;
wire   [12:0] add_ln137_1_fu_257_p2;
reg   [12:0] add_ln137_1_reg_581;
wire    ap_CS_fsm_state2;
wire   [5:0] add_ln137_fu_269_p2;
reg   [5:0] add_ln137_reg_589;
wire   [0:0] icmp_ln137_fu_263_p2;
wire   [4:0] trunc_ln149_fu_280_p1;
reg   [4:0] trunc_ln149_reg_599;
reg   [8:0] acc_V_reg_603;
wire    ap_CS_fsm_state3;
wire   [0:0] icmp_ln1039_fu_287_p2;
reg   [0:0] icmp_ln1039_reg_608;
wire    ap_CS_fsm_state5;
wire   [46:0] zext_ln8_fu_297_p1;
reg   [46:0] scaled_V_reg_619;
wire    ap_CS_fsm_state6;
wire    grp_fc1_layer_Pipeline_VITIS_LOOP_139_1_VITIS_LOOP_140_2_fu_217_ap_start;
wire    grp_fc1_layer_Pipeline_VITIS_LOOP_139_1_VITIS_LOOP_140_2_fu_217_ap_done;
wire    grp_fc1_layer_Pipeline_VITIS_LOOP_139_1_VITIS_LOOP_140_2_fu_217_ap_idle;
wire    grp_fc1_layer_Pipeline_VITIS_LOOP_139_1_VITIS_LOOP_140_2_fu_217_ap_ready;
wire   [24:0] grp_fc1_layer_Pipeline_VITIS_LOOP_139_1_VITIS_LOOP_140_2_fu_217_acc_V_2_out;
wire    grp_fc1_layer_Pipeline_VITIS_LOOP_139_1_VITIS_LOOP_140_2_fu_217_acc_V_2_out_ap_vld;
wire   [7:0] grp_fc1_layer_Pipeline_VITIS_LOOP_139_1_VITIS_LOOP_140_2_fu_217_cnn_accel_ap_int_8_const_ap_uint_4_pool2_address0;
wire    grp_fc1_layer_Pipeline_VITIS_LOOP_139_1_VITIS_LOOP_140_2_fu_217_cnn_accel_ap_int_8_const_ap_uint_4_pool2_ce0;
wire   [7:0] grp_fc1_layer_Pipeline_VITIS_LOOP_139_1_VITIS_LOOP_140_2_fu_217_cnn_accel_ap_int_8_const_ap_uint_4_pool2_address1;
wire    grp_fc1_layer_Pipeline_VITIS_LOOP_139_1_VITIS_LOOP_140_2_fu_217_cnn_accel_ap_int_8_const_ap_uint_4_pool2_ce1;
wire   [7:0] grp_fc1_layer_Pipeline_VITIS_LOOP_139_1_VITIS_LOOP_140_2_fu_217_cnn_accel_ap_int_8_const_ap_uint_4_pool2_3_address0;
wire    grp_fc1_layer_Pipeline_VITIS_LOOP_139_1_VITIS_LOOP_140_2_fu_217_cnn_accel_ap_int_8_const_ap_uint_4_pool2_3_ce0;
wire   [7:0] grp_fc1_layer_Pipeline_VITIS_LOOP_139_1_VITIS_LOOP_140_2_fu_217_cnn_accel_ap_int_8_const_ap_uint_4_pool2_3_address1;
wire    grp_fc1_layer_Pipeline_VITIS_LOOP_139_1_VITIS_LOOP_140_2_fu_217_cnn_accel_ap_int_8_const_ap_uint_4_pool2_3_ce1;
wire   [7:0] grp_fc1_layer_Pipeline_VITIS_LOOP_139_1_VITIS_LOOP_140_2_fu_217_cnn_accel_ap_int_8_const_ap_uint_4_pool2_4_address0;
wire    grp_fc1_layer_Pipeline_VITIS_LOOP_139_1_VITIS_LOOP_140_2_fu_217_cnn_accel_ap_int_8_const_ap_uint_4_pool2_4_ce0;
wire   [7:0] grp_fc1_layer_Pipeline_VITIS_LOOP_139_1_VITIS_LOOP_140_2_fu_217_cnn_accel_ap_int_8_const_ap_uint_4_pool2_4_address1;
wire    grp_fc1_layer_Pipeline_VITIS_LOOP_139_1_VITIS_LOOP_140_2_fu_217_cnn_accel_ap_int_8_const_ap_uint_4_pool2_4_ce1;
wire   [7:0] grp_fc1_layer_Pipeline_VITIS_LOOP_139_1_VITIS_LOOP_140_2_fu_217_cnn_accel_ap_int_8_const_ap_uint_4_pool2_5_address0;
wire    grp_fc1_layer_Pipeline_VITIS_LOOP_139_1_VITIS_LOOP_140_2_fu_217_cnn_accel_ap_int_8_const_ap_uint_4_pool2_5_ce0;
reg    grp_fc1_layer_Pipeline_VITIS_LOOP_139_1_VITIS_LOOP_140_2_fu_217_ap_start_reg;
wire    ap_CS_fsm_state4;
wire   [63:0] zext_ln137_fu_275_p1;
wire   [7:0] select_ln1039_1_fu_350_p3;
wire    ap_CS_fsm_state7;
reg   [12:0] phi_mul_fu_192;
reg   [5:0] o_fu_196;
wire  signed [24:0] icmp_ln1039_fu_287_p0;
wire  signed [24:0] sext_ln8_fu_293_p0;
wire  signed [31:0] sext_ln8_fu_293_p1;
wire   [46:0] scaled_V_1_fu_307_p2;
wire   [15:0] tmp_fu_312_p4;
wire   [0:0] icmp_ln1035_fu_322_p2;
wire   [0:0] or_ln1039_fu_345_p2;
wire   [7:0] select_ln1039_fu_338_p3;
wire   [7:0] trunc_ln1_fu_328_p4;
reg   [6:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 7'd1;
#0 grp_fc1_layer_Pipeline_VITIS_LOOP_139_1_VITIS_LOOP_140_2_fu_217_ap_start_reg = 1'b0;
end

cnn_accel_fc1_layer_B_FC1_V_ROM_AUTO_1R #(
    .DataWidth( 9 ),
    .AddressRange( 32 ),
    .AddressWidth( 5 ))
B_FC1_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(B_FC1_V_address0),
    .ce0(B_FC1_V_ce0),
    .q0(B_FC1_V_q0)
);

cnn_accel_fc1_layer_Pipeline_VITIS_LOOP_139_1_VITIS_LOOP_140_2 grp_fc1_layer_Pipeline_VITIS_LOOP_139_1_VITIS_LOOP_140_2_fu_217(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_fc1_layer_Pipeline_VITIS_LOOP_139_1_VITIS_LOOP_140_2_fu_217_ap_start),
    .ap_done(grp_fc1_layer_Pipeline_VITIS_LOOP_139_1_VITIS_LOOP_140_2_fu_217_ap_done),
    .ap_idle(grp_fc1_layer_Pipeline_VITIS_LOOP_139_1_VITIS_LOOP_140_2_fu_217_ap_idle),
    .ap_ready(grp_fc1_layer_Pipeline_VITIS_LOOP_139_1_VITIS_LOOP_140_2_fu_217_ap_ready),
    .sext_ln138(acc_V_reg_603),
    .phi_mul(phi_mul_fu_192),
    .acc_V_2_out(grp_fc1_layer_Pipeline_VITIS_LOOP_139_1_VITIS_LOOP_140_2_fu_217_acc_V_2_out),
    .acc_V_2_out_ap_vld(grp_fc1_layer_Pipeline_VITIS_LOOP_139_1_VITIS_LOOP_140_2_fu_217_acc_V_2_out_ap_vld),
    .cnn_accel_ap_int_8_const_ap_uint_4_pool2_address0(grp_fc1_layer_Pipeline_VITIS_LOOP_139_1_VITIS_LOOP_140_2_fu_217_cnn_accel_ap_int_8_const_ap_uint_4_pool2_address0),
    .cnn_accel_ap_int_8_const_ap_uint_4_pool2_ce0(grp_fc1_layer_Pipeline_VITIS_LOOP_139_1_VITIS_LOOP_140_2_fu_217_cnn_accel_ap_int_8_const_ap_uint_4_pool2_ce0),
    .cnn_accel_ap_int_8_const_ap_uint_4_pool2_q0(cnn_accel_ap_int_8_const_ap_uint_4_pool2_q0),
    .cnn_accel_ap_int_8_const_ap_uint_4_pool2_address1(grp_fc1_layer_Pipeline_VITIS_LOOP_139_1_VITIS_LOOP_140_2_fu_217_cnn_accel_ap_int_8_const_ap_uint_4_pool2_address1),
    .cnn_accel_ap_int_8_const_ap_uint_4_pool2_ce1(grp_fc1_layer_Pipeline_VITIS_LOOP_139_1_VITIS_LOOP_140_2_fu_217_cnn_accel_ap_int_8_const_ap_uint_4_pool2_ce1),
    .cnn_accel_ap_int_8_const_ap_uint_4_pool2_q1(cnn_accel_ap_int_8_const_ap_uint_4_pool2_q1),
    .cnn_accel_ap_int_8_const_ap_uint_4_pool2_3_address0(grp_fc1_layer_Pipeline_VITIS_LOOP_139_1_VITIS_LOOP_140_2_fu_217_cnn_accel_ap_int_8_const_ap_uint_4_pool2_3_address0),
    .cnn_accel_ap_int_8_const_ap_uint_4_pool2_3_ce0(grp_fc1_layer_Pipeline_VITIS_LOOP_139_1_VITIS_LOOP_140_2_fu_217_cnn_accel_ap_int_8_const_ap_uint_4_pool2_3_ce0),
    .cnn_accel_ap_int_8_const_ap_uint_4_pool2_3_q0(cnn_accel_ap_int_8_const_ap_uint_4_pool2_3_q0),
    .cnn_accel_ap_int_8_const_ap_uint_4_pool2_3_address1(grp_fc1_layer_Pipeline_VITIS_LOOP_139_1_VITIS_LOOP_140_2_fu_217_cnn_accel_ap_int_8_const_ap_uint_4_pool2_3_address1),
    .cnn_accel_ap_int_8_const_ap_uint_4_pool2_3_ce1(grp_fc1_layer_Pipeline_VITIS_LOOP_139_1_VITIS_LOOP_140_2_fu_217_cnn_accel_ap_int_8_const_ap_uint_4_pool2_3_ce1),
    .cnn_accel_ap_int_8_const_ap_uint_4_pool2_3_q1(cnn_accel_ap_int_8_const_ap_uint_4_pool2_3_q1),
    .cnn_accel_ap_int_8_const_ap_uint_4_pool2_4_address0(grp_fc1_layer_Pipeline_VITIS_LOOP_139_1_VITIS_LOOP_140_2_fu_217_cnn_accel_ap_int_8_const_ap_uint_4_pool2_4_address0),
    .cnn_accel_ap_int_8_const_ap_uint_4_pool2_4_ce0(grp_fc1_layer_Pipeline_VITIS_LOOP_139_1_VITIS_LOOP_140_2_fu_217_cnn_accel_ap_int_8_const_ap_uint_4_pool2_4_ce0),
    .cnn_accel_ap_int_8_const_ap_uint_4_pool2_4_q0(cnn_accel_ap_int_8_const_ap_uint_4_pool2_4_q0),
    .cnn_accel_ap_int_8_const_ap_uint_4_pool2_4_address1(grp_fc1_layer_Pipeline_VITIS_LOOP_139_1_VITIS_LOOP_140_2_fu_217_cnn_accel_ap_int_8_const_ap_uint_4_pool2_4_address1),
    .cnn_accel_ap_int_8_const_ap_uint_4_pool2_4_ce1(grp_fc1_layer_Pipeline_VITIS_LOOP_139_1_VITIS_LOOP_140_2_fu_217_cnn_accel_ap_int_8_const_ap_uint_4_pool2_4_ce1),
    .cnn_accel_ap_int_8_const_ap_uint_4_pool2_4_q1(cnn_accel_ap_int_8_const_ap_uint_4_pool2_4_q1),
    .cnn_accel_ap_int_8_const_ap_uint_4_pool2_5_address0(grp_fc1_layer_Pipeline_VITIS_LOOP_139_1_VITIS_LOOP_140_2_fu_217_cnn_accel_ap_int_8_const_ap_uint_4_pool2_5_address0),
    .cnn_accel_ap_int_8_const_ap_uint_4_pool2_5_ce0(grp_fc1_layer_Pipeline_VITIS_LOOP_139_1_VITIS_LOOP_140_2_fu_217_cnn_accel_ap_int_8_const_ap_uint_4_pool2_5_ce0),
    .cnn_accel_ap_int_8_const_ap_uint_4_pool2_5_q0(cnn_accel_ap_int_8_const_ap_uint_4_pool2_5_q0)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_fc1_layer_Pipeline_VITIS_LOOP_139_1_VITIS_LOOP_140_2_fu_217_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_fc1_layer_Pipeline_VITIS_LOOP_139_1_VITIS_LOOP_140_2_fu_217_ap_start_reg <= 1'b1;
        end else if ((grp_fc1_layer_Pipeline_VITIS_LOOP_139_1_VITIS_LOOP_140_2_fu_217_ap_ready == 1'b1)) begin
            grp_fc1_layer_Pipeline_VITIS_LOOP_139_1_VITIS_LOOP_140_2_fu_217_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        o_fu_196 <= 6'd0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        o_fu_196 <= add_ln137_reg_589;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        phi_mul_fu_192 <= 13'd0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        phi_mul_fu_192 <= add_ln137_1_reg_581;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        acc_V_reg_603 <= B_FC1_V_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        add_ln137_1_reg_581 <= add_ln137_1_fu_257_p2;
        add_ln137_reg_589 <= add_ln137_fu_269_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        icmp_ln1039_reg_608 <= icmp_ln1039_fu_287_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        scaled_V_reg_619 <= grp_fu_1102_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln137_fu_263_p2 == 1'd0))) begin
        trunc_ln149_reg_599 <= trunc_ln149_fu_280_p1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        B_FC1_V_ce0 = 1'b1;
    end else begin
        B_FC1_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_fc1_layer_Pipeline_VITIS_LOOP_139_1_VITIS_LOOP_140_2_fu_217_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)) | ((1'b1 == ap_CS_fsm_state2) & (icmp_ln137_fu_263_p2 == 1'd1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln137_fu_263_p2 == 1'd1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) & (trunc_ln149_reg_599 == 5'd5))) begin
        cnn_accel_ap_int_8_const_ap_uint_4_fc1_10_ap_vld = 1'b1;
    end else begin
        cnn_accel_ap_int_8_const_ap_uint_4_fc1_10_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) & (trunc_ln149_reg_599 == 5'd6))) begin
        cnn_accel_ap_int_8_const_ap_uint_4_fc1_11_ap_vld = 1'b1;
    end else begin
        cnn_accel_ap_int_8_const_ap_uint_4_fc1_11_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) & (trunc_ln149_reg_599 == 5'd7))) begin
        cnn_accel_ap_int_8_const_ap_uint_4_fc1_12_ap_vld = 1'b1;
    end else begin
        cnn_accel_ap_int_8_const_ap_uint_4_fc1_12_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) & (trunc_ln149_reg_599 == 5'd8))) begin
        cnn_accel_ap_int_8_const_ap_uint_4_fc1_13_ap_vld = 1'b1;
    end else begin
        cnn_accel_ap_int_8_const_ap_uint_4_fc1_13_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) & (trunc_ln149_reg_599 == 5'd9))) begin
        cnn_accel_ap_int_8_const_ap_uint_4_fc1_14_ap_vld = 1'b1;
    end else begin
        cnn_accel_ap_int_8_const_ap_uint_4_fc1_14_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) & (trunc_ln149_reg_599 == 5'd1))) begin
        cnn_accel_ap_int_8_const_ap_uint_4_fc1_6_ap_vld = 1'b1;
    end else begin
        cnn_accel_ap_int_8_const_ap_uint_4_fc1_6_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) & (trunc_ln149_reg_599 == 5'd2))) begin
        cnn_accel_ap_int_8_const_ap_uint_4_fc1_7_ap_vld = 1'b1;
    end else begin
        cnn_accel_ap_int_8_const_ap_uint_4_fc1_7_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) & (trunc_ln149_reg_599 == 5'd3))) begin
        cnn_accel_ap_int_8_const_ap_uint_4_fc1_8_ap_vld = 1'b1;
    end else begin
        cnn_accel_ap_int_8_const_ap_uint_4_fc1_8_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) & (trunc_ln149_reg_599 == 5'd4))) begin
        cnn_accel_ap_int_8_const_ap_uint_4_fc1_9_ap_vld = 1'b1;
    end else begin
        cnn_accel_ap_int_8_const_ap_uint_4_fc1_9_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) & (trunc_ln149_reg_599 == 5'd0))) begin
        cnn_accel_ap_int_8_const_ap_uint_4_fc1_ap_vld = 1'b1;
    end else begin
        cnn_accel_ap_int_8_const_ap_uint_4_fc1_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) & (trunc_ln149_reg_599 == 5'd10))) begin
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_10_ap_vld = 1'b1;
    end else begin
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_10_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) & (trunc_ln149_reg_599 == 5'd11))) begin
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_11_ap_vld = 1'b1;
    end else begin
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_11_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) & (trunc_ln149_reg_599 == 5'd12))) begin
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_12_ap_vld = 1'b1;
    end else begin
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_12_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) & (trunc_ln149_reg_599 == 5'd13))) begin
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_13_ap_vld = 1'b1;
    end else begin
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_13_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) & (trunc_ln149_reg_599 == 5'd14))) begin
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_14_ap_vld = 1'b1;
    end else begin
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_14_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) & (trunc_ln149_reg_599 == 5'd15))) begin
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_15_ap_vld = 1'b1;
    end else begin
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_15_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) & (trunc_ln149_reg_599 == 5'd16))) begin
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_16_ap_vld = 1'b1;
    end else begin
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_16_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) & (trunc_ln149_reg_599 == 5'd17))) begin
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_17_ap_vld = 1'b1;
    end else begin
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_17_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) & (trunc_ln149_reg_599 == 5'd18))) begin
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_18_ap_vld = 1'b1;
    end else begin
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_18_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) & (trunc_ln149_reg_599 == 5'd19))) begin
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_19_ap_vld = 1'b1;
    end else begin
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_19_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) & (trunc_ln149_reg_599 == 5'd20))) begin
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_20_ap_vld = 1'b1;
    end else begin
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_20_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) & (trunc_ln149_reg_599 == 5'd21))) begin
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_21_ap_vld = 1'b1;
    end else begin
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_21_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) & (trunc_ln149_reg_599 == 5'd22))) begin
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_22_ap_vld = 1'b1;
    end else begin
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_22_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) & (trunc_ln149_reg_599 == 5'd23))) begin
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_23_ap_vld = 1'b1;
    end else begin
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_23_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) & (trunc_ln149_reg_599 == 5'd24))) begin
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_24_ap_vld = 1'b1;
    end else begin
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_24_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) & (trunc_ln149_reg_599 == 5'd25))) begin
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_25_ap_vld = 1'b1;
    end else begin
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_25_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) & (trunc_ln149_reg_599 == 5'd26))) begin
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_26_ap_vld = 1'b1;
    end else begin
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_26_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) & (trunc_ln149_reg_599 == 5'd27))) begin
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_27_ap_vld = 1'b1;
    end else begin
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_27_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) & (trunc_ln149_reg_599 == 5'd28))) begin
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_28_ap_vld = 1'b1;
    end else begin
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_28_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) & (trunc_ln149_reg_599 == 5'd29))) begin
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_29_ap_vld = 1'b1;
    end else begin
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_29_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) & (trunc_ln149_reg_599 == 5'd30))) begin
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_30_ap_vld = 1'b1;
    end else begin
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_30_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) & (trunc_ln149_reg_599 == 5'd31))) begin
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_31_ap_vld = 1'b1;
    end else begin
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_31_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln137_fu_263_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & (grp_fc1_layer_Pipeline_VITIS_LOOP_139_1_VITIS_LOOP_140_2_fu_217_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign B_FC1_V_address0 = zext_ln137_fu_275_p1;

assign add_ln137_1_fu_257_p2 = (phi_mul_fu_192 + 13'd196);

assign add_ln137_fu_269_p2 = (o_fu_196 + 6'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign cnn_accel_ap_int_8_const_ap_uint_4_fc1 = select_ln1039_1_fu_350_p3;

assign cnn_accel_ap_int_8_const_ap_uint_4_fc1_10 = select_ln1039_1_fu_350_p3;

assign cnn_accel_ap_int_8_const_ap_uint_4_fc1_11 = select_ln1039_1_fu_350_p3;

assign cnn_accel_ap_int_8_const_ap_uint_4_fc1_12 = select_ln1039_1_fu_350_p3;

assign cnn_accel_ap_int_8_const_ap_uint_4_fc1_13 = select_ln1039_1_fu_350_p3;

assign cnn_accel_ap_int_8_const_ap_uint_4_fc1_14 = select_ln1039_1_fu_350_p3;

assign cnn_accel_ap_int_8_const_ap_uint_4_fc1_6 = select_ln1039_1_fu_350_p3;

assign cnn_accel_ap_int_8_const_ap_uint_4_fc1_7 = select_ln1039_1_fu_350_p3;

assign cnn_accel_ap_int_8_const_ap_uint_4_fc1_8 = select_ln1039_1_fu_350_p3;

assign cnn_accel_ap_int_8_const_ap_uint_4_fc1_9 = select_ln1039_1_fu_350_p3;

assign cnn_accel_ap_int_8_const_ap_uint_4_pool2_3_address0 = grp_fc1_layer_Pipeline_VITIS_LOOP_139_1_VITIS_LOOP_140_2_fu_217_cnn_accel_ap_int_8_const_ap_uint_4_pool2_3_address0;

assign cnn_accel_ap_int_8_const_ap_uint_4_pool2_3_address1 = grp_fc1_layer_Pipeline_VITIS_LOOP_139_1_VITIS_LOOP_140_2_fu_217_cnn_accel_ap_int_8_const_ap_uint_4_pool2_3_address1;

assign cnn_accel_ap_int_8_const_ap_uint_4_pool2_3_ce0 = grp_fc1_layer_Pipeline_VITIS_LOOP_139_1_VITIS_LOOP_140_2_fu_217_cnn_accel_ap_int_8_const_ap_uint_4_pool2_3_ce0;

assign cnn_accel_ap_int_8_const_ap_uint_4_pool2_3_ce1 = grp_fc1_layer_Pipeline_VITIS_LOOP_139_1_VITIS_LOOP_140_2_fu_217_cnn_accel_ap_int_8_const_ap_uint_4_pool2_3_ce1;

assign cnn_accel_ap_int_8_const_ap_uint_4_pool2_4_address0 = grp_fc1_layer_Pipeline_VITIS_LOOP_139_1_VITIS_LOOP_140_2_fu_217_cnn_accel_ap_int_8_const_ap_uint_4_pool2_4_address0;

assign cnn_accel_ap_int_8_const_ap_uint_4_pool2_4_address1 = grp_fc1_layer_Pipeline_VITIS_LOOP_139_1_VITIS_LOOP_140_2_fu_217_cnn_accel_ap_int_8_const_ap_uint_4_pool2_4_address1;

assign cnn_accel_ap_int_8_const_ap_uint_4_pool2_4_ce0 = grp_fc1_layer_Pipeline_VITIS_LOOP_139_1_VITIS_LOOP_140_2_fu_217_cnn_accel_ap_int_8_const_ap_uint_4_pool2_4_ce0;

assign cnn_accel_ap_int_8_const_ap_uint_4_pool2_4_ce1 = grp_fc1_layer_Pipeline_VITIS_LOOP_139_1_VITIS_LOOP_140_2_fu_217_cnn_accel_ap_int_8_const_ap_uint_4_pool2_4_ce1;

assign cnn_accel_ap_int_8_const_ap_uint_4_pool2_5_address0 = grp_fc1_layer_Pipeline_VITIS_LOOP_139_1_VITIS_LOOP_140_2_fu_217_cnn_accel_ap_int_8_const_ap_uint_4_pool2_5_address0;

assign cnn_accel_ap_int_8_const_ap_uint_4_pool2_5_ce0 = grp_fc1_layer_Pipeline_VITIS_LOOP_139_1_VITIS_LOOP_140_2_fu_217_cnn_accel_ap_int_8_const_ap_uint_4_pool2_5_ce0;

assign cnn_accel_ap_int_8_const_ap_uint_4_pool2_address0 = grp_fc1_layer_Pipeline_VITIS_LOOP_139_1_VITIS_LOOP_140_2_fu_217_cnn_accel_ap_int_8_const_ap_uint_4_pool2_address0;

assign cnn_accel_ap_int_8_const_ap_uint_4_pool2_address1 = grp_fc1_layer_Pipeline_VITIS_LOOP_139_1_VITIS_LOOP_140_2_fu_217_cnn_accel_ap_int_8_const_ap_uint_4_pool2_address1;

assign cnn_accel_ap_int_8_const_ap_uint_4_pool2_ce0 = grp_fc1_layer_Pipeline_VITIS_LOOP_139_1_VITIS_LOOP_140_2_fu_217_cnn_accel_ap_int_8_const_ap_uint_4_pool2_ce0;

assign cnn_accel_ap_int_8_const_ap_uint_4_pool2_ce1 = grp_fc1_layer_Pipeline_VITIS_LOOP_139_1_VITIS_LOOP_140_2_fu_217_cnn_accel_ap_int_8_const_ap_uint_4_pool2_ce1;

assign grp_fc1_layer_Pipeline_VITIS_LOOP_139_1_VITIS_LOOP_140_2_fu_217_ap_start = grp_fc1_layer_Pipeline_VITIS_LOOP_139_1_VITIS_LOOP_140_2_fu_217_ap_start_reg;

assign grp_fu_1102_p_ce = 1'b1;

assign grp_fu_1102_p_din0 = zext_ln8_fu_297_p1;

assign grp_fu_1102_p_din1 = 47'd24190;

assign icmp_ln1035_fu_322_p2 = ((tmp_fu_312_p4 != 16'd0) ? 1'b1 : 1'b0);

assign icmp_ln1039_fu_287_p0 = grp_fc1_layer_Pipeline_VITIS_LOOP_139_1_VITIS_LOOP_140_2_fu_217_acc_V_2_out;

assign icmp_ln1039_fu_287_p2 = (($signed(icmp_ln1039_fu_287_p0) < $signed(25'd1)) ? 1'b1 : 1'b0);

assign icmp_ln137_fu_263_p2 = ((o_fu_196 == 6'd32) ? 1'b1 : 1'b0);

assign or_ln1039_fu_345_p2 = (icmp_ln1039_reg_608 | icmp_ln1035_fu_322_p2);

assign p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_10 = select_ln1039_1_fu_350_p3;

assign p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_11 = select_ln1039_1_fu_350_p3;

assign p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_12 = select_ln1039_1_fu_350_p3;

assign p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_13 = select_ln1039_1_fu_350_p3;

assign p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_14 = select_ln1039_1_fu_350_p3;

assign p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_15 = select_ln1039_1_fu_350_p3;

assign p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_16 = select_ln1039_1_fu_350_p3;

assign p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_17 = select_ln1039_1_fu_350_p3;

assign p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_18 = select_ln1039_1_fu_350_p3;

assign p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_19 = select_ln1039_1_fu_350_p3;

assign p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_20 = select_ln1039_1_fu_350_p3;

assign p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_21 = select_ln1039_1_fu_350_p3;

assign p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_22 = select_ln1039_1_fu_350_p3;

assign p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_23 = select_ln1039_1_fu_350_p3;

assign p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_24 = select_ln1039_1_fu_350_p3;

assign p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_25 = select_ln1039_1_fu_350_p3;

assign p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_26 = select_ln1039_1_fu_350_p3;

assign p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_27 = select_ln1039_1_fu_350_p3;

assign p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_28 = select_ln1039_1_fu_350_p3;

assign p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_29 = select_ln1039_1_fu_350_p3;

assign p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_30 = select_ln1039_1_fu_350_p3;

assign p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE3fc1_31 = select_ln1039_1_fu_350_p3;

assign scaled_V_1_fu_307_p2 = (scaled_V_reg_619 + 47'd8388608);

assign select_ln1039_1_fu_350_p3 = ((or_ln1039_fu_345_p2[0:0] == 1'b1) ? select_ln1039_fu_338_p3 : trunc_ln1_fu_328_p4);

assign select_ln1039_fu_338_p3 = ((icmp_ln1039_reg_608[0:0] == 1'b1) ? 8'd0 : 8'd127);

assign sext_ln8_fu_293_p0 = grp_fc1_layer_Pipeline_VITIS_LOOP_139_1_VITIS_LOOP_140_2_fu_217_acc_V_2_out;

assign sext_ln8_fu_293_p1 = sext_ln8_fu_293_p0;

assign tmp_fu_312_p4 = {{scaled_V_1_fu_307_p2[46:31]}};

assign trunc_ln149_fu_280_p1 = o_fu_196[4:0];

assign trunc_ln1_fu_328_p4 = {{scaled_V_1_fu_307_p2[31:24]}};

assign zext_ln137_fu_275_p1 = o_fu_196;

assign zext_ln8_fu_297_p1 = $unsigned(sext_ln8_fu_293_p1);

endmodule //cnn_accel_fc1_layer
