// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module cnn_accel_cnn_accel_Pipeline_pool1_loop_VITIS_LOOP_58_1_VITIS_LOOP_59_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE5pool1_0_0_address0,
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE5pool1_0_0_ce0,
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE5pool1_0_0_we0,
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE5pool1_0_0_d0,
        cnn_accel_ap_int_8_const_ap_uint_4_conv1_address0,
        cnn_accel_ap_int_8_const_ap_uint_4_conv1_ce0,
        cnn_accel_ap_int_8_const_ap_uint_4_conv1_q0,
        cnn_accel_ap_int_8_const_ap_uint_4_conv1_address1,
        cnn_accel_ap_int_8_const_ap_uint_4_conv1_ce1,
        cnn_accel_ap_int_8_const_ap_uint_4_conv1_q1,
        cnn_accel_ap_int_8_const_ap_uint_4_conv1_1_address0,
        cnn_accel_ap_int_8_const_ap_uint_4_conv1_1_ce0,
        cnn_accel_ap_int_8_const_ap_uint_4_conv1_1_q0,
        cnn_accel_ap_int_8_const_ap_uint_4_conv1_1_address1,
        cnn_accel_ap_int_8_const_ap_uint_4_conv1_1_ce1,
        cnn_accel_ap_int_8_const_ap_uint_4_conv1_1_q1,
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE5pool1_0_1_address0,
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE5pool1_0_1_ce0,
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE5pool1_0_1_we0,
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE5pool1_0_1_d0,
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE5pool1_0_2_address0,
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE5pool1_0_2_ce0,
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE5pool1_0_2_we0,
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE5pool1_0_2_d0,
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE5pool1_1_0_address0,
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE5pool1_1_0_ce0,
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE5pool1_1_0_we0,
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE5pool1_1_0_d0,
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE5pool1_1_1_address0,
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE5pool1_1_1_ce0,
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE5pool1_1_1_we0,
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE5pool1_1_1_d0,
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE5pool1_1_2_address0,
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE5pool1_1_2_ce0,
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE5pool1_1_2_we0,
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE5pool1_1_2_d0,
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE5pool1_2_0_address0,
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE5pool1_2_0_ce0,
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE5pool1_2_0_we0,
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE5pool1_2_0_d0,
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE5pool1_2_1_address0,
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE5pool1_2_1_ce0,
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE5pool1_2_1_we0,
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE5pool1_2_1_d0,
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE5pool1_2_2_address0,
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE5pool1_2_2_ce0,
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE5pool1_2_2_we0,
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE5pool1_2_2_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [7:0] p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE5pool1_0_0_address0;
output   p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE5pool1_0_0_ce0;
output   p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE5pool1_0_0_we0;
output  [7:0] p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE5pool1_0_0_d0;
output  [11:0] cnn_accel_ap_int_8_const_ap_uint_4_conv1_address0;
output   cnn_accel_ap_int_8_const_ap_uint_4_conv1_ce0;
input  [7:0] cnn_accel_ap_int_8_const_ap_uint_4_conv1_q0;
output  [11:0] cnn_accel_ap_int_8_const_ap_uint_4_conv1_address1;
output   cnn_accel_ap_int_8_const_ap_uint_4_conv1_ce1;
input  [7:0] cnn_accel_ap_int_8_const_ap_uint_4_conv1_q1;
output  [11:0] cnn_accel_ap_int_8_const_ap_uint_4_conv1_1_address0;
output   cnn_accel_ap_int_8_const_ap_uint_4_conv1_1_ce0;
input  [7:0] cnn_accel_ap_int_8_const_ap_uint_4_conv1_1_q0;
output  [11:0] cnn_accel_ap_int_8_const_ap_uint_4_conv1_1_address1;
output   cnn_accel_ap_int_8_const_ap_uint_4_conv1_1_ce1;
input  [7:0] cnn_accel_ap_int_8_const_ap_uint_4_conv1_1_q1;
output  [7:0] p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE5pool1_0_1_address0;
output   p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE5pool1_0_1_ce0;
output   p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE5pool1_0_1_we0;
output  [7:0] p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE5pool1_0_1_d0;
output  [7:0] p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE5pool1_0_2_address0;
output   p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE5pool1_0_2_ce0;
output   p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE5pool1_0_2_we0;
output  [7:0] p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE5pool1_0_2_d0;
output  [7:0] p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE5pool1_1_0_address0;
output   p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE5pool1_1_0_ce0;
output   p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE5pool1_1_0_we0;
output  [7:0] p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE5pool1_1_0_d0;
output  [7:0] p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE5pool1_1_1_address0;
output   p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE5pool1_1_1_ce0;
output   p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE5pool1_1_1_we0;
output  [7:0] p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE5pool1_1_1_d0;
output  [7:0] p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE5pool1_1_2_address0;
output   p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE5pool1_1_2_ce0;
output   p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE5pool1_1_2_we0;
output  [7:0] p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE5pool1_1_2_d0;
output  [7:0] p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE5pool1_2_0_address0;
output   p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE5pool1_2_0_ce0;
output   p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE5pool1_2_0_we0;
output  [7:0] p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE5pool1_2_0_d0;
output  [7:0] p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE5pool1_2_1_address0;
output   p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE5pool1_2_1_ce0;
output   p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE5pool1_2_1_we0;
output  [7:0] p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE5pool1_2_1_d0;
output  [7:0] p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE5pool1_2_2_address0;
output   p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE5pool1_2_2_ce0;
output   p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE5pool1_2_2_we0;
output  [7:0] p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE5pool1_2_2_d0;

reg ap_idle;
reg p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE5pool1_0_0_ce0;
reg p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE5pool1_0_0_we0;
reg cnn_accel_ap_int_8_const_ap_uint_4_conv1_ce0;
reg cnn_accel_ap_int_8_const_ap_uint_4_conv1_ce1;
reg cnn_accel_ap_int_8_const_ap_uint_4_conv1_1_ce0;
reg cnn_accel_ap_int_8_const_ap_uint_4_conv1_1_ce1;
reg p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE5pool1_0_1_ce0;
reg p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE5pool1_0_1_we0;
reg p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE5pool1_0_2_ce0;
reg p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE5pool1_0_2_we0;
reg p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE5pool1_1_0_ce0;
reg p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE5pool1_1_0_we0;
reg p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE5pool1_1_1_ce0;
reg p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE5pool1_1_1_we0;
reg p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE5pool1_1_2_ce0;
reg p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE5pool1_1_2_we0;
reg p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE5pool1_2_0_ce0;
reg p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE5pool1_2_0_we0;
reg p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE5pool1_2_1_ce0;
reg p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE5pool1_2_1_we0;
reg p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE5pool1_2_2_ce0;
reg p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE5pool1_2_2_we0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
wire    ap_block_state7_pp0_stage0_iter6;
wire    ap_block_state8_pp0_stage0_iter7;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln57_fu_323_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
reg   [3:0] y_5_reg_836;
reg   [0:0] icmp_ln57_reg_842;
reg   [0:0] icmp_ln57_reg_842_pp0_iter1_reg;
reg   [0:0] icmp_ln57_reg_842_pp0_iter2_reg;
reg   [0:0] icmp_ln57_reg_842_pp0_iter3_reg;
reg   [0:0] icmp_ln57_reg_842_pp0_iter4_reg;
reg   [0:0] icmp_ln57_reg_842_pp0_iter5_reg;
reg   [0:0] icmp_ln57_reg_842_pp0_iter6_reg;
wire   [0:0] icmp_ln58_fu_338_p2;
reg   [0:0] icmp_ln58_reg_846;
reg   [0:0] icmp_ln58_reg_846_pp0_iter1_reg;
reg   [0:0] icmp_ln58_reg_846_pp0_iter2_reg;
reg   [0:0] icmp_ln58_reg_846_pp0_iter3_reg;
reg   [0:0] icmp_ln58_reg_846_pp0_iter4_reg;
reg   [0:0] icmp_ln58_reg_846_pp0_iter5_reg;
reg   [0:0] icmp_ln58_reg_846_pp0_iter6_reg;
wire   [0:0] and_ln57_fu_364_p2;
reg   [0:0] and_ln57_reg_853;
reg   [0:0] and_ln57_reg_853_pp0_iter1_reg;
reg   [0:0] and_ln57_reg_853_pp0_iter2_reg;
reg   [0:0] and_ln57_reg_853_pp0_iter3_reg;
reg   [0:0] and_ln57_reg_853_pp0_iter4_reg;
reg   [0:0] and_ln57_reg_853_pp0_iter5_reg;
reg   [0:0] and_ln57_reg_853_pp0_iter6_reg;
wire   [3:0] add_ln58_fu_370_p2;
reg   [3:0] add_ln58_reg_859;
wire   [3:0] select_ln58_fu_382_p3;
reg   [3:0] select_ln58_reg_865;
reg   [3:0] select_ln58_reg_865_pp0_iter1_reg;
reg   [3:0] select_ln58_reg_865_pp0_iter2_reg;
reg   [3:0] select_ln58_reg_865_pp0_iter3_reg;
wire   [3:0] select_ln58_1_fu_390_p3;
reg   [3:0] select_ln58_1_reg_872;
reg   [3:0] select_ln58_1_reg_872_pp0_iter1_reg;
reg   [3:0] select_ln58_1_reg_872_pp0_iter2_reg;
wire   [3:0] select_ln58_2_fu_503_p3;
reg   [3:0] select_ln58_2_reg_877;
reg   [3:0] select_ln58_2_reg_877_pp0_iter2_reg;
wire   [3:0] select_ln57_1_fu_519_p3;
reg   [3:0] select_ln57_1_reg_882;
reg   [2:0] tmp_299_reg_890;
wire   [11:0] sub_ln61_1_fu_631_p2;
reg   [11:0] sub_ln61_1_reg_895;
wire   [7:0] add_ln68_3_fu_671_p2;
reg   [7:0] add_ln68_3_reg_901;
reg   [7:0] add_ln68_3_reg_901_pp0_iter4_reg;
reg   [7:0] add_ln68_3_reg_901_pp0_iter5_reg;
reg   [7:0] add_ln68_3_reg_901_pp0_iter6_reg;
wire   [63:0] zext_ln61_4_fu_693_p1;
reg   [63:0] zext_ln61_4_reg_906;
wire   [63:0] zext_ln62_1_fu_713_p1;
reg   [63:0] zext_ln62_1_reg_916;
wire   [7:0] m_V_5_fu_724_p3;
reg   [7:0] m_V_5_reg_936;
reg   [7:0] v3_V_reg_942;
wire   [7:0] m_V_7_fu_737_p3;
reg   [7:0] m_V_7_reg_948;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln68_10_fu_785_p1;
reg   [3:0] x_fu_96;
wire   [3:0] add_ln59_fu_410_p2;
wire    ap_loop_init;
reg   [3:0] ap_sig_allocacmp_x_load;
reg   [3:0] y_fu_100;
reg   [3:0] ap_sig_allocacmp_y_5;
reg   [7:0] indvar_flatten_fu_104;
wire   [7:0] select_ln58_4_fu_422_p3;
reg   [7:0] ap_sig_allocacmp_indvar_flatten_load;
reg   [3:0] c_fu_108;
reg   [10:0] indvar_flatten21_fu_112;
wire   [10:0] add_ln57_1_fu_329_p2;
reg   [10:0] ap_sig_allocacmp_indvar_flatten21_load;
wire   [1:0] select_ln58_3_fu_759_p3;
wire   [1:0] trunc_ln68_3_fu_797_p1;
wire   [7:0] m_V_8_fu_770_p3;
wire   [2:0] grp_fu_317_p1;
wire   [0:0] icmp_ln59_fu_358_p2;
wire   [0:0] xor_ln57_fu_352_p2;
wire   [3:0] select_ln57_fu_344_p3;
wire   [0:0] or_ln58_fu_376_p2;
wire   [2:0] grp_fu_398_p1;
wire   [2:0] grp_fu_404_p1;
wire   [7:0] add_ln58_1_fu_416_p2;
wire   [3:0] mul_ln68_fu_453_p0;
wire   [5:0] mul_ln68_fu_453_p1;
wire   [8:0] mul_ln68_fu_453_p2;
wire   [2:0] tmp_fu_459_p4;
wire   [3:0] zext_ln68_1_fu_469_p1;
wire   [3:0] mul_ln68_1_fu_483_p0;
wire   [5:0] mul_ln68_1_fu_483_p1;
wire   [8:0] mul_ln68_1_fu_483_p2;
wire   [2:0] tmp_298_fu_489_p4;
wire   [3:0] zext_ln68_5_fu_499_p1;
wire   [3:0] select_ln57_2_fu_473_p3;
wire   [3:0] add_ln57_fu_513_p2;
wire   [3:0] mul_ln68_2_fu_529_p0;
wire   [5:0] mul_ln68_2_fu_529_p1;
wire   [8:0] mul_ln68_2_fu_529_p2;
wire   [5:0] tmp_s_fu_553_p3;
wire   [6:0] zext_ln68_3_fu_560_p1;
wire   [6:0] zext_ln68_2_fu_550_p1;
wire   [7:0] tmp_289_fu_570_p3;
wire   [4:0] tmp_290_fu_581_p3;
wire   [8:0] zext_ln61_fu_577_p1;
wire   [8:0] zext_ln61_1_fu_588_p1;
wire   [8:0] sub_ln61_fu_592_p2;
wire  signed [9:0] sext_ln57_fu_598_p1;
wire   [9:0] zext_ln61_2_fu_602_p1;
wire   [9:0] add_ln61_fu_605_p2;
wire   [6:0] trunc_ln61_fu_611_p1;
wire   [11:0] p_shl7_fu_615_p3;
wire   [11:0] p_shl8_fu_623_p3;
wire   [6:0] add_ln68_fu_564_p2;
wire   [6:0] zext_ln68_6_fu_637_p1;
wire   [6:0] add_ln68_1_fu_640_p2;
wire   [5:0] trunc_ln68_1_fu_650_p1;
wire   [7:0] p_shl_fu_654_p3;
wire   [7:0] zext_ln68_7_fu_646_p1;
wire   [7:0] add_ln68_2_fu_662_p2;
wire   [7:0] zext_ln68_9_fu_668_p1;
wire   [4:0] shl_ln_fu_677_p3;
wire   [11:0] zext_ln61_3_fu_684_p1;
wire   [11:0] add_ln61_1_fu_688_p2;
wire   [4:0] or_ln62_fu_698_p2;
wire   [11:0] zext_ln62_fu_704_p1;
wire   [11:0] add_ln62_fu_708_p2;
wire   [0:0] icmp_ln1035_fu_718_p2;
wire   [0:0] icmp_ln1035_1_fu_732_p2;
wire   [1:0] grp_fu_317_p2;
wire   [1:0] trunc_ln68_fu_744_p1;
wire   [1:0] grp_fu_398_p2;
wire   [1:0] trunc_ln68_2_fu_755_p1;
wire   [1:0] select_ln57_3_fu_748_p3;
wire   [0:0] icmp_ln1035_2_fu_766_p2;
wire   [1:0] grp_fu_404_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire   [8:0] mul_ln68_1_fu_483_p00;
wire   [8:0] mul_ln68_2_fu_529_p00;
wire   [8:0] mul_ln68_fu_453_p00;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_done_reg = 1'b0;
end

cnn_accel_urem_4ns_3ns_2_8_1 #(
    .ID( 1 ),
    .NUM_STAGE( 8 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 3 ),
    .dout_WIDTH( 2 ))
urem_4ns_3ns_2_8_1_U31(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(ap_sig_allocacmp_y_5),
    .din1(grp_fu_317_p1),
    .ce(1'b1),
    .dout(grp_fu_317_p2)
);

cnn_accel_urem_4ns_3ns_2_8_1 #(
    .ID( 1 ),
    .NUM_STAGE( 8 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 3 ),
    .dout_WIDTH( 2 ))
urem_4ns_3ns_2_8_1_U32(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(add_ln58_fu_370_p2),
    .din1(grp_fu_398_p1),
    .ce(1'b1),
    .dout(grp_fu_398_p2)
);

cnn_accel_urem_4ns_3ns_2_8_1 #(
    .ID( 1 ),
    .NUM_STAGE( 8 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 3 ),
    .dout_WIDTH( 2 ))
urem_4ns_3ns_2_8_1_U33(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(select_ln58_fu_382_p3),
    .din1(grp_fu_404_p1),
    .ce(1'b1),
    .dout(grp_fu_404_p2)
);

cnn_accel_mul_4ns_6ns_9_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 9 ))
mul_4ns_6ns_9_1_1_U34(
    .din0(mul_ln68_fu_453_p0),
    .din1(mul_ln68_fu_453_p1),
    .dout(mul_ln68_fu_453_p2)
);

cnn_accel_mul_4ns_6ns_9_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 9 ))
mul_4ns_6ns_9_1_1_U35(
    .din0(mul_ln68_1_fu_483_p0),
    .din1(mul_ln68_1_fu_483_p1),
    .dout(mul_ln68_1_fu_483_p2)
);

cnn_accel_mul_4ns_6ns_9_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 9 ))
mul_4ns_6ns_9_1_1_U36(
    .din0(mul_ln68_2_fu_529_p0),
    .din1(mul_ln68_2_fu_529_p1),
    .dout(mul_ln68_2_fu_529_p2)
);

cnn_accel_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter7_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_exit_ready_pp0_iter6_reg == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_loop_exit_ready_pp0_iter7_reg <= 1'b0;
    end else if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            c_fu_108 <= 4'd0;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln57_reg_842_pp0_iter1_reg == 1'd0))) begin
            c_fu_108 <= select_ln57_1_fu_519_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln57_fu_323_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten21_fu_112 <= add_ln57_1_fu_329_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten21_fu_112 <= 11'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln57_fu_323_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten_fu_104 <= select_ln58_4_fu_422_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_104 <= 8'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln57_fu_323_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            x_fu_96 <= add_ln59_fu_410_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            x_fu_96 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln57_fu_323_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            y_fu_100 <= select_ln58_1_fu_390_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            y_fu_100 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln57_fu_323_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln58_reg_859 <= add_ln58_fu_370_p2;
        and_ln57_reg_853 <= and_ln57_fu_364_p2;
        icmp_ln58_reg_846 <= icmp_ln58_fu_338_p2;
        select_ln58_1_reg_872 <= select_ln58_1_fu_390_p3;
        select_ln58_reg_865 <= select_ln58_fu_382_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln57_reg_842_pp0_iter2_reg == 1'd0))) begin
        add_ln68_3_reg_901 <= add_ln68_3_fu_671_p2;
        sub_ln61_1_reg_895[11 : 2] <= sub_ln61_1_fu_631_p2[11 : 2];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        add_ln68_3_reg_901_pp0_iter4_reg <= add_ln68_3_reg_901;
        add_ln68_3_reg_901_pp0_iter5_reg <= add_ln68_3_reg_901_pp0_iter4_reg;
        add_ln68_3_reg_901_pp0_iter6_reg <= add_ln68_3_reg_901_pp0_iter5_reg;
        and_ln57_reg_853_pp0_iter2_reg <= and_ln57_reg_853_pp0_iter1_reg;
        and_ln57_reg_853_pp0_iter3_reg <= and_ln57_reg_853_pp0_iter2_reg;
        and_ln57_reg_853_pp0_iter4_reg <= and_ln57_reg_853_pp0_iter3_reg;
        and_ln57_reg_853_pp0_iter5_reg <= and_ln57_reg_853_pp0_iter4_reg;
        and_ln57_reg_853_pp0_iter6_reg <= and_ln57_reg_853_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        icmp_ln57_reg_842_pp0_iter2_reg <= icmp_ln57_reg_842_pp0_iter1_reg;
        icmp_ln57_reg_842_pp0_iter3_reg <= icmp_ln57_reg_842_pp0_iter2_reg;
        icmp_ln57_reg_842_pp0_iter4_reg <= icmp_ln57_reg_842_pp0_iter3_reg;
        icmp_ln57_reg_842_pp0_iter5_reg <= icmp_ln57_reg_842_pp0_iter4_reg;
        icmp_ln57_reg_842_pp0_iter6_reg <= icmp_ln57_reg_842_pp0_iter5_reg;
        icmp_ln58_reg_846_pp0_iter2_reg <= icmp_ln58_reg_846_pp0_iter1_reg;
        icmp_ln58_reg_846_pp0_iter3_reg <= icmp_ln58_reg_846_pp0_iter2_reg;
        icmp_ln58_reg_846_pp0_iter4_reg <= icmp_ln58_reg_846_pp0_iter3_reg;
        icmp_ln58_reg_846_pp0_iter5_reg <= icmp_ln58_reg_846_pp0_iter4_reg;
        icmp_ln58_reg_846_pp0_iter6_reg <= icmp_ln58_reg_846_pp0_iter5_reg;
        select_ln58_1_reg_872_pp0_iter2_reg <= select_ln58_1_reg_872_pp0_iter1_reg;
        select_ln58_2_reg_877_pp0_iter2_reg[2 : 0] <= select_ln58_2_reg_877[2 : 0];
        select_ln58_reg_865_pp0_iter2_reg <= select_ln58_reg_865_pp0_iter1_reg;
        select_ln58_reg_865_pp0_iter3_reg <= select_ln58_reg_865_pp0_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        and_ln57_reg_853_pp0_iter1_reg <= and_ln57_reg_853;
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        icmp_ln57_reg_842 <= icmp_ln57_fu_323_p2;
        icmp_ln57_reg_842_pp0_iter1_reg <= icmp_ln57_reg_842;
        icmp_ln58_reg_846_pp0_iter1_reg <= icmp_ln58_reg_846;
        select_ln58_1_reg_872_pp0_iter1_reg <= select_ln58_1_reg_872;
        select_ln58_reg_865_pp0_iter1_reg <= select_ln58_reg_865;
        y_5_reg_836 <= ap_sig_allocacmp_y_5;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln57_reg_842_pp0_iter4_reg == 1'd0))) begin
        m_V_5_reg_936 <= m_V_5_fu_724_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln57_reg_842_pp0_iter5_reg == 1'd0))) begin
        m_V_7_reg_948 <= m_V_7_fu_737_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln57_reg_842_pp0_iter1_reg == 1'd0))) begin
        select_ln57_1_reg_882 <= select_ln57_1_fu_519_p3;
        tmp_299_reg_890 <= {{mul_ln68_2_fu_529_p2[8:6]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln57_reg_842 == 1'd0))) begin
        select_ln58_2_reg_877[2 : 0] <= select_ln58_2_fu_503_p3[2 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter6 == 1'b1) & (icmp_ln57_reg_842_pp0_iter5_reg == 1'd0))) begin
        v3_V_reg_942 <= cnn_accel_ap_int_8_const_ap_uint_4_conv1_1_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln57_reg_842_pp0_iter3_reg == 1'd0))) begin
        zext_ln61_4_reg_906[11 : 1] <= zext_ln61_4_fu_693_p1[11 : 1];
        zext_ln62_1_reg_916[11 : 1] <= zext_ln62_1_fu_713_p1[11 : 1];
    end
end

always @ (*) begin
    if (((icmp_ln57_fu_323_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter7_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten21_load = 11'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten21_load = indvar_flatten21_fu_112;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten_load = 8'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten_load = indvar_flatten_fu_104;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_x_load = 4'd0;
    end else begin
        ap_sig_allocacmp_x_load = x_fu_96;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_y_5 = 4'd0;
    end else begin
        ap_sig_allocacmp_y_5 = y_fu_100;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        cnn_accel_ap_int_8_const_ap_uint_4_conv1_1_ce0 = 1'b1;
    end else begin
        cnn_accel_ap_int_8_const_ap_uint_4_conv1_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        cnn_accel_ap_int_8_const_ap_uint_4_conv1_1_ce1 = 1'b1;
    end else begin
        cnn_accel_ap_int_8_const_ap_uint_4_conv1_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        cnn_accel_ap_int_8_const_ap_uint_4_conv1_ce0 = 1'b1;
    end else begin
        cnn_accel_ap_int_8_const_ap_uint_4_conv1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        cnn_accel_ap_int_8_const_ap_uint_4_conv1_ce1 = 1'b1;
    end else begin
        cnn_accel_ap_int_8_const_ap_uint_4_conv1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE5pool1_0_0_ce0 = 1'b1;
    end else begin
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE5pool1_0_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter7 == 1'b1) & (trunc_ln68_3_fu_797_p1 == 2'd0) & (select_ln58_3_fu_759_p3 == 2'd0) & (icmp_ln57_reg_842_pp0_iter6_reg == 1'd0))) begin
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE5pool1_0_0_we0 = 1'b1;
    end else begin
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE5pool1_0_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE5pool1_0_1_ce0 = 1'b1;
    end else begin
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE5pool1_0_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter7 == 1'b1) & (trunc_ln68_3_fu_797_p1 == 2'd1) & (select_ln58_3_fu_759_p3 == 2'd0) & (icmp_ln57_reg_842_pp0_iter6_reg == 1'd0))) begin
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE5pool1_0_1_we0 = 1'b1;
    end else begin
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE5pool1_0_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE5pool1_0_2_ce0 = 1'b1;
    end else begin
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE5pool1_0_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~(trunc_ln68_3_fu_797_p1 == 2'd0) & ~(trunc_ln68_3_fu_797_p1 == 2'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter7 == 1'b1) & (select_ln58_3_fu_759_p3 == 2'd0) & (icmp_ln57_reg_842_pp0_iter6_reg == 1'd0))) begin
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE5pool1_0_2_we0 = 1'b1;
    end else begin
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE5pool1_0_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE5pool1_1_0_ce0 = 1'b1;
    end else begin
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE5pool1_1_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter7 == 1'b1) & (trunc_ln68_3_fu_797_p1 == 2'd0) & (select_ln58_3_fu_759_p3 == 2'd1) & (icmp_ln57_reg_842_pp0_iter6_reg == 1'd0))) begin
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE5pool1_1_0_we0 = 1'b1;
    end else begin
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE5pool1_1_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE5pool1_1_1_ce0 = 1'b1;
    end else begin
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE5pool1_1_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter7 == 1'b1) & (trunc_ln68_3_fu_797_p1 == 2'd1) & (select_ln58_3_fu_759_p3 == 2'd1) & (icmp_ln57_reg_842_pp0_iter6_reg == 1'd0))) begin
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE5pool1_1_1_we0 = 1'b1;
    end else begin
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE5pool1_1_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE5pool1_1_2_ce0 = 1'b1;
    end else begin
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE5pool1_1_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~(trunc_ln68_3_fu_797_p1 == 2'd0) & ~(trunc_ln68_3_fu_797_p1 == 2'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter7 == 1'b1) & (select_ln58_3_fu_759_p3 == 2'd1) & (icmp_ln57_reg_842_pp0_iter6_reg == 1'd0))) begin
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE5pool1_1_2_we0 = 1'b1;
    end else begin
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE5pool1_1_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE5pool1_2_0_ce0 = 1'b1;
    end else begin
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE5pool1_2_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~(select_ln58_3_fu_759_p3 == 2'd0) & ~(select_ln58_3_fu_759_p3 == 2'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter7 == 1'b1) & (trunc_ln68_3_fu_797_p1 == 2'd0) & (icmp_ln57_reg_842_pp0_iter6_reg == 1'd0))) begin
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE5pool1_2_0_we0 = 1'b1;
    end else begin
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE5pool1_2_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE5pool1_2_1_ce0 = 1'b1;
    end else begin
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE5pool1_2_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~(select_ln58_3_fu_759_p3 == 2'd0) & ~(select_ln58_3_fu_759_p3 == 2'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter7 == 1'b1) & (trunc_ln68_3_fu_797_p1 == 2'd1) & (icmp_ln57_reg_842_pp0_iter6_reg == 1'd0))) begin
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE5pool1_2_1_we0 = 1'b1;
    end else begin
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE5pool1_2_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE5pool1_2_2_ce0 = 1'b1;
    end else begin
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE5pool1_2_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~(select_ln58_3_fu_759_p3 == 2'd0) & ~(trunc_ln68_3_fu_797_p1 == 2'd0) & ~(trunc_ln68_3_fu_797_p1 == 2'd1) & ~(select_ln58_3_fu_759_p3 == 2'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter7 == 1'b1) & (icmp_ln57_reg_842_pp0_iter6_reg == 1'd0))) begin
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE5pool1_2_2_we0 = 1'b1;
    end else begin
        p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE5pool1_2_2_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln57_1_fu_329_p2 = (ap_sig_allocacmp_indvar_flatten21_load + 11'd1);

assign add_ln57_fu_513_p2 = (c_fu_108 + 4'd1);

assign add_ln58_1_fu_416_p2 = (ap_sig_allocacmp_indvar_flatten_load + 8'd1);

assign add_ln58_fu_370_p2 = (select_ln57_fu_344_p3 + 4'd1);

assign add_ln59_fu_410_p2 = (select_ln58_fu_382_p3 + 4'd1);

assign add_ln61_1_fu_688_p2 = (sub_ln61_1_reg_895 + zext_ln61_3_fu_684_p1);

assign add_ln61_fu_605_p2 = ($signed(sext_ln57_fu_598_p1) + $signed(zext_ln61_2_fu_602_p1));

assign add_ln62_fu_708_p2 = (sub_ln61_1_reg_895 + zext_ln62_fu_704_p1);

assign add_ln68_1_fu_640_p2 = (add_ln68_fu_564_p2 + zext_ln68_6_fu_637_p1);

assign add_ln68_2_fu_662_p2 = (p_shl_fu_654_p3 + zext_ln68_7_fu_646_p1);

assign add_ln68_3_fu_671_p2 = (add_ln68_2_fu_662_p2 + zext_ln68_9_fu_668_p1);

assign add_ln68_fu_564_p2 = (zext_ln68_3_fu_560_p1 + zext_ln68_2_fu_550_p1);

assign and_ln57_fu_364_p2 = (xor_ln57_fu_352_p2 & icmp_ln59_fu_358_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter7 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign cnn_accel_ap_int_8_const_ap_uint_4_conv1_1_address0 = zext_ln62_1_reg_916;

assign cnn_accel_ap_int_8_const_ap_uint_4_conv1_1_address1 = zext_ln61_4_reg_906;

assign cnn_accel_ap_int_8_const_ap_uint_4_conv1_address0 = zext_ln62_1_fu_713_p1;

assign cnn_accel_ap_int_8_const_ap_uint_4_conv1_address1 = zext_ln61_4_fu_693_p1;

assign grp_fu_317_p1 = 4'd3;

assign grp_fu_398_p1 = 4'd3;

assign grp_fu_404_p1 = 4'd3;

assign icmp_ln1035_1_fu_732_p2 = (($signed(cnn_accel_ap_int_8_const_ap_uint_4_conv1_1_q1) > $signed(m_V_5_reg_936)) ? 1'b1 : 1'b0);

assign icmp_ln1035_2_fu_766_p2 = (($signed(v3_V_reg_942) > $signed(m_V_7_reg_948)) ? 1'b1 : 1'b0);

assign icmp_ln1035_fu_718_p2 = (($signed(cnn_accel_ap_int_8_const_ap_uint_4_conv1_q0) > $signed(cnn_accel_ap_int_8_const_ap_uint_4_conv1_q1)) ? 1'b1 : 1'b0);

assign icmp_ln57_fu_323_p2 = ((ap_sig_allocacmp_indvar_flatten21_load == 11'd1568) ? 1'b1 : 1'b0);

assign icmp_ln58_fu_338_p2 = ((ap_sig_allocacmp_indvar_flatten_load == 8'd196) ? 1'b1 : 1'b0);

assign icmp_ln59_fu_358_p2 = ((ap_sig_allocacmp_x_load == 4'd14) ? 1'b1 : 1'b0);

assign m_V_5_fu_724_p3 = ((icmp_ln1035_fu_718_p2[0:0] == 1'b1) ? cnn_accel_ap_int_8_const_ap_uint_4_conv1_q0 : cnn_accel_ap_int_8_const_ap_uint_4_conv1_q1);

assign m_V_7_fu_737_p3 = ((icmp_ln1035_1_fu_732_p2[0:0] == 1'b1) ? cnn_accel_ap_int_8_const_ap_uint_4_conv1_1_q1 : m_V_5_reg_936);

assign m_V_8_fu_770_p3 = ((icmp_ln1035_2_fu_766_p2[0:0] == 1'b1) ? v3_V_reg_942 : m_V_7_reg_948);

assign mul_ln68_1_fu_483_p0 = mul_ln68_1_fu_483_p00;

assign mul_ln68_1_fu_483_p00 = add_ln58_reg_859;

assign mul_ln68_1_fu_483_p1 = 9'd22;

assign mul_ln68_2_fu_529_p0 = mul_ln68_2_fu_529_p00;

assign mul_ln68_2_fu_529_p00 = select_ln58_reg_865_pp0_iter1_reg;

assign mul_ln68_2_fu_529_p1 = 9'd22;

assign mul_ln68_fu_453_p0 = mul_ln68_fu_453_p00;

assign mul_ln68_fu_453_p00 = y_5_reg_836;

assign mul_ln68_fu_453_p1 = 9'd22;

assign or_ln58_fu_376_p2 = (icmp_ln58_fu_338_p2 | and_ln57_fu_364_p2);

assign or_ln62_fu_698_p2 = (shl_ln_fu_677_p3 | 5'd1);

assign p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE5pool1_0_0_address0 = zext_ln68_10_fu_785_p1;

assign p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE5pool1_0_0_d0 = m_V_8_fu_770_p3;

assign p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE5pool1_0_1_address0 = zext_ln68_10_fu_785_p1;

assign p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE5pool1_0_1_d0 = m_V_8_fu_770_p3;

assign p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE5pool1_0_2_address0 = zext_ln68_10_fu_785_p1;

assign p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE5pool1_0_2_d0 = m_V_8_fu_770_p3;

assign p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE5pool1_1_0_address0 = zext_ln68_10_fu_785_p1;

assign p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE5pool1_1_0_d0 = m_V_8_fu_770_p3;

assign p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE5pool1_1_1_address0 = zext_ln68_10_fu_785_p1;

assign p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE5pool1_1_1_d0 = m_V_8_fu_770_p3;

assign p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE5pool1_1_2_address0 = zext_ln68_10_fu_785_p1;

assign p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE5pool1_1_2_d0 = m_V_8_fu_770_p3;

assign p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE5pool1_2_0_address0 = zext_ln68_10_fu_785_p1;

assign p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE5pool1_2_0_d0 = m_V_8_fu_770_p3;

assign p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE5pool1_2_1_address0 = zext_ln68_10_fu_785_p1;

assign p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE5pool1_2_1_d0 = m_V_8_fu_770_p3;

assign p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE5pool1_2_2_address0 = zext_ln68_10_fu_785_p1;

assign p_ZZ9cnn_accelPK6ap_intILi8EER7ap_uintILi4EEE5pool1_2_2_d0 = m_V_8_fu_770_p3;

assign p_shl7_fu_615_p3 = {{trunc_ln61_fu_611_p1}, {5'd0}};

assign p_shl8_fu_623_p3 = {{add_ln61_fu_605_p2}, {2'd0}};

assign p_shl_fu_654_p3 = {{trunc_ln68_1_fu_650_p1}, {2'd0}};

assign select_ln57_1_fu_519_p3 = ((icmp_ln58_reg_846_pp0_iter1_reg[0:0] == 1'b1) ? add_ln57_fu_513_p2 : c_fu_108);

assign select_ln57_2_fu_473_p3 = ((icmp_ln58_reg_846[0:0] == 1'b1) ? 4'd0 : zext_ln68_1_fu_469_p1);

assign select_ln57_3_fu_748_p3 = ((icmp_ln58_reg_846_pp0_iter6_reg[0:0] == 1'b1) ? 2'd0 : trunc_ln68_fu_744_p1);

assign select_ln57_fu_344_p3 = ((icmp_ln58_fu_338_p2[0:0] == 1'b1) ? 4'd0 : ap_sig_allocacmp_y_5);

assign select_ln58_1_fu_390_p3 = ((and_ln57_fu_364_p2[0:0] == 1'b1) ? add_ln58_fu_370_p2 : select_ln57_fu_344_p3);

assign select_ln58_2_fu_503_p3 = ((and_ln57_reg_853[0:0] == 1'b1) ? zext_ln68_5_fu_499_p1 : select_ln57_2_fu_473_p3);

assign select_ln58_3_fu_759_p3 = ((and_ln57_reg_853_pp0_iter6_reg[0:0] == 1'b1) ? trunc_ln68_2_fu_755_p1 : select_ln57_3_fu_748_p3);

assign select_ln58_4_fu_422_p3 = ((icmp_ln58_fu_338_p2[0:0] == 1'b1) ? 8'd1 : add_ln58_1_fu_416_p2);

assign select_ln58_fu_382_p3 = ((or_ln58_fu_376_p2[0:0] == 1'b1) ? 4'd0 : ap_sig_allocacmp_x_load);

assign sext_ln57_fu_598_p1 = $signed(sub_ln61_fu_592_p2);

assign shl_ln_fu_677_p3 = {{select_ln58_reg_865_pp0_iter3_reg}, {1'd0}};

assign sub_ln61_1_fu_631_p2 = (p_shl7_fu_615_p3 - p_shl8_fu_623_p3);

assign sub_ln61_fu_592_p2 = (zext_ln61_fu_577_p1 - zext_ln61_1_fu_588_p1);

assign tmp_289_fu_570_p3 = {{select_ln57_1_reg_882}, {4'd0}};

assign tmp_290_fu_581_p3 = {{select_ln57_1_reg_882}, {1'd0}};

assign tmp_298_fu_489_p4 = {{mul_ln68_1_fu_483_p2[8:6]}};

assign tmp_fu_459_p4 = {{mul_ln68_fu_453_p2[8:6]}};

assign tmp_s_fu_553_p3 = {{select_ln57_1_reg_882}, {2'd0}};

assign trunc_ln61_fu_611_p1 = add_ln61_fu_605_p2[6:0];

assign trunc_ln68_1_fu_650_p1 = add_ln68_1_fu_640_p2[5:0];

assign trunc_ln68_2_fu_755_p1 = grp_fu_398_p2[1:0];

assign trunc_ln68_3_fu_797_p1 = grp_fu_404_p2[1:0];

assign trunc_ln68_fu_744_p1 = grp_fu_317_p2[1:0];

assign xor_ln57_fu_352_p2 = (icmp_ln58_fu_338_p2 ^ 1'd1);

assign zext_ln61_1_fu_588_p1 = tmp_290_fu_581_p3;

assign zext_ln61_2_fu_602_p1 = select_ln58_1_reg_872_pp0_iter2_reg;

assign zext_ln61_3_fu_684_p1 = shl_ln_fu_677_p3;

assign zext_ln61_4_fu_693_p1 = add_ln61_1_fu_688_p2;

assign zext_ln61_fu_577_p1 = tmp_289_fu_570_p3;

assign zext_ln62_1_fu_713_p1 = add_ln62_fu_708_p2;

assign zext_ln62_fu_704_p1 = or_ln62_fu_698_p2;

assign zext_ln68_10_fu_785_p1 = add_ln68_3_reg_901_pp0_iter6_reg;

assign zext_ln68_1_fu_469_p1 = tmp_fu_459_p4;

assign zext_ln68_2_fu_550_p1 = select_ln57_1_reg_882;

assign zext_ln68_3_fu_560_p1 = tmp_s_fu_553_p3;

assign zext_ln68_5_fu_499_p1 = tmp_298_fu_489_p4;

assign zext_ln68_6_fu_637_p1 = select_ln58_2_reg_877_pp0_iter2_reg;

assign zext_ln68_7_fu_646_p1 = add_ln68_1_fu_640_p2;

assign zext_ln68_9_fu_668_p1 = tmp_299_reg_890;

always @ (posedge ap_clk) begin
    select_ln58_2_reg_877[3] <= 1'b0;
    select_ln58_2_reg_877_pp0_iter2_reg[3] <= 1'b0;
    sub_ln61_1_reg_895[1:0] <= 2'b00;
    zext_ln61_4_reg_906[0] <= 1'b0;
    zext_ln61_4_reg_906[63:12] <= 52'b0000000000000000000000000000000000000000000000000000;
    zext_ln62_1_reg_916[0] <= 1'b1;
    zext_ln62_1_reg_916[63:12] <= 52'b0000000000000000000000000000000000000000000000000000;
end

endmodule //cnn_accel_cnn_accel_Pipeline_pool1_loop_VITIS_LOOP_58_1_VITIS_LOOP_59_2
