// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module cnn_accel_cnn_accel_Pipeline_pool2_loop_VITIS_LOOP_112_1_VITIS_LOOP_113_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        cnn_accel_ap_int_8_const_ap_uint_4_pool2_address0,
        cnn_accel_ap_int_8_const_ap_uint_4_pool2_ce0,
        cnn_accel_ap_int_8_const_ap_uint_4_pool2_we0,
        cnn_accel_ap_int_8_const_ap_uint_4_pool2_d0,
        cnn_accel_ap_int_8_const_ap_uint_4_conv2_address0,
        cnn_accel_ap_int_8_const_ap_uint_4_conv2_ce0,
        cnn_accel_ap_int_8_const_ap_uint_4_conv2_q0,
        cnn_accel_ap_int_8_const_ap_uint_4_conv2_address1,
        cnn_accel_ap_int_8_const_ap_uint_4_conv2_ce1,
        cnn_accel_ap_int_8_const_ap_uint_4_conv2_q1,
        cnn_accel_ap_int_8_const_ap_uint_4_conv2_2_address0,
        cnn_accel_ap_int_8_const_ap_uint_4_conv2_2_ce0,
        cnn_accel_ap_int_8_const_ap_uint_4_conv2_2_q0,
        cnn_accel_ap_int_8_const_ap_uint_4_conv2_2_address1,
        cnn_accel_ap_int_8_const_ap_uint_4_conv2_2_ce1,
        cnn_accel_ap_int_8_const_ap_uint_4_conv2_2_q1,
        cnn_accel_ap_int_8_const_ap_uint_4_pool2_3_address0,
        cnn_accel_ap_int_8_const_ap_uint_4_pool2_3_ce0,
        cnn_accel_ap_int_8_const_ap_uint_4_pool2_3_we0,
        cnn_accel_ap_int_8_const_ap_uint_4_pool2_3_d0,
        cnn_accel_ap_int_8_const_ap_uint_4_pool2_4_address0,
        cnn_accel_ap_int_8_const_ap_uint_4_pool2_4_ce0,
        cnn_accel_ap_int_8_const_ap_uint_4_pool2_4_we0,
        cnn_accel_ap_int_8_const_ap_uint_4_pool2_4_d0,
        cnn_accel_ap_int_8_const_ap_uint_4_pool2_5_address0,
        cnn_accel_ap_int_8_const_ap_uint_4_pool2_5_ce0,
        cnn_accel_ap_int_8_const_ap_uint_4_pool2_5_we0,
        cnn_accel_ap_int_8_const_ap_uint_4_pool2_5_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [7:0] cnn_accel_ap_int_8_const_ap_uint_4_pool2_address0;
output   cnn_accel_ap_int_8_const_ap_uint_4_pool2_ce0;
output   cnn_accel_ap_int_8_const_ap_uint_4_pool2_we0;
output  [7:0] cnn_accel_ap_int_8_const_ap_uint_4_pool2_d0;
output  [10:0] cnn_accel_ap_int_8_const_ap_uint_4_conv2_address0;
output   cnn_accel_ap_int_8_const_ap_uint_4_conv2_ce0;
input  [7:0] cnn_accel_ap_int_8_const_ap_uint_4_conv2_q0;
output  [10:0] cnn_accel_ap_int_8_const_ap_uint_4_conv2_address1;
output   cnn_accel_ap_int_8_const_ap_uint_4_conv2_ce1;
input  [7:0] cnn_accel_ap_int_8_const_ap_uint_4_conv2_q1;
output  [10:0] cnn_accel_ap_int_8_const_ap_uint_4_conv2_2_address0;
output   cnn_accel_ap_int_8_const_ap_uint_4_conv2_2_ce0;
input  [7:0] cnn_accel_ap_int_8_const_ap_uint_4_conv2_2_q0;
output  [10:0] cnn_accel_ap_int_8_const_ap_uint_4_conv2_2_address1;
output   cnn_accel_ap_int_8_const_ap_uint_4_conv2_2_ce1;
input  [7:0] cnn_accel_ap_int_8_const_ap_uint_4_conv2_2_q1;
output  [7:0] cnn_accel_ap_int_8_const_ap_uint_4_pool2_3_address0;
output   cnn_accel_ap_int_8_const_ap_uint_4_pool2_3_ce0;
output   cnn_accel_ap_int_8_const_ap_uint_4_pool2_3_we0;
output  [7:0] cnn_accel_ap_int_8_const_ap_uint_4_pool2_3_d0;
output  [7:0] cnn_accel_ap_int_8_const_ap_uint_4_pool2_4_address0;
output   cnn_accel_ap_int_8_const_ap_uint_4_pool2_4_ce0;
output   cnn_accel_ap_int_8_const_ap_uint_4_pool2_4_we0;
output  [7:0] cnn_accel_ap_int_8_const_ap_uint_4_pool2_4_d0;
output  [7:0] cnn_accel_ap_int_8_const_ap_uint_4_pool2_5_address0;
output   cnn_accel_ap_int_8_const_ap_uint_4_pool2_5_ce0;
output   cnn_accel_ap_int_8_const_ap_uint_4_pool2_5_we0;
output  [7:0] cnn_accel_ap_int_8_const_ap_uint_4_pool2_5_d0;

reg ap_idle;
reg cnn_accel_ap_int_8_const_ap_uint_4_pool2_ce0;
reg cnn_accel_ap_int_8_const_ap_uint_4_pool2_we0;
reg cnn_accel_ap_int_8_const_ap_uint_4_conv2_ce0;
reg cnn_accel_ap_int_8_const_ap_uint_4_conv2_ce1;
reg cnn_accel_ap_int_8_const_ap_uint_4_conv2_2_ce0;
reg cnn_accel_ap_int_8_const_ap_uint_4_conv2_2_ce1;
reg cnn_accel_ap_int_8_const_ap_uint_4_pool2_3_ce0;
reg cnn_accel_ap_int_8_const_ap_uint_4_pool2_3_we0;
reg cnn_accel_ap_int_8_const_ap_uint_4_pool2_4_ce0;
reg cnn_accel_ap_int_8_const_ap_uint_4_pool2_4_we0;
reg cnn_accel_ap_int_8_const_ap_uint_4_pool2_5_ce0;
reg cnn_accel_ap_int_8_const_ap_uint_4_pool2_5_we0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln111_fu_237_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire   [2:0] select_ln112_fu_342_p3;
reg   [2:0] select_ln112_reg_585;
wire   [9:0] add_ln115_fu_362_p2;
reg   [9:0] add_ln115_reg_590;
wire   [6:0] trunc_ln115_fu_368_p1;
reg   [6:0] trunc_ln115_reg_595;
reg   [6:0] trunc_ln115_reg_595_pp0_iter1_reg;
reg   [6:0] trunc_ln115_reg_595_pp0_iter2_reg;
reg   [6:0] trunc_ln115_reg_595_pp0_iter3_reg;
reg   [0:0] tmp_reg_601;
reg   [0:0] tmp_reg_601_pp0_iter1_reg;
reg   [0:0] tmp_reg_601_pp0_iter2_reg;
reg   [0:0] tmp_reg_601_pp0_iter3_reg;
wire   [1:0] trunc_ln122_fu_380_p1;
reg   [1:0] trunc_ln122_reg_606;
reg   [1:0] trunc_ln122_reg_606_pp0_iter1_reg;
reg   [1:0] trunc_ln122_reg_606_pp0_iter2_reg;
reg   [1:0] trunc_ln122_reg_606_pp0_iter3_reg;
wire   [63:0] zext_ln115_4_fu_466_p1;
reg   [63:0] zext_ln115_4_reg_610;
wire   [63:0] zext_ln116_1_fu_487_p1;
reg   [63:0] zext_ln116_1_reg_620;
wire   [7:0] m_V_1_fu_498_p3;
reg   [7:0] m_V_1_reg_640;
reg   [7:0] v3_V_reg_646;
wire   [7:0] m_V_3_fu_511_p3;
reg   [7:0] m_V_3_reg_652;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln122_fu_538_p1;
reg   [2:0] x_fu_84;
wire   [2:0] add_ln113_fu_384_p2;
wire    ap_loop_init;
reg   [2:0] ap_sig_allocacmp_x_load;
reg   [2:0] y_1_fu_88;
wire   [2:0] select_ln112_1_fu_350_p3;
reg   [2:0] ap_sig_allocacmp_y_1_load;
reg   [5:0] indvar_flatten28_fu_92;
wire   [5:0] select_ln112_2_fu_396_p3;
reg   [5:0] ap_sig_allocacmp_indvar_flatten28_load;
reg   [4:0] c_fu_96;
wire   [4:0] select_ln111_1_fu_278_p3;
reg   [4:0] ap_sig_allocacmp_c_load;
reg   [9:0] indvar_flatten42_fu_100;
wire   [9:0] add_ln111_1_fu_243_p2;
reg   [9:0] ap_sig_allocacmp_indvar_flatten42_load;
wire   [7:0] m_V_4_fu_522_p3;
wire   [0:0] icmp_ln112_fu_264_p2;
wire   [4:0] add_ln111_fu_258_p2;
wire   [7:0] tmp_s_fu_290_p3;
wire   [8:0] zext_ln115_1_fu_298_p1;
wire   [8:0] zext_ln115_fu_286_p1;
wire   [8:0] sub_ln115_fu_302_p2;
wire   [0:0] icmp_ln113_fu_318_p2;
wire   [0:0] xor_ln111_fu_312_p2;
wire   [2:0] select_ln111_fu_270_p3;
wire   [0:0] and_ln111_fu_324_p2;
wire   [0:0] or_ln112_fu_336_p2;
wire   [2:0] add_ln112_fu_330_p2;
wire  signed [9:0] sext_ln112_fu_308_p1;
wire   [9:0] zext_ln115_2_fu_358_p1;
wire   [5:0] add_ln112_1_fu_390_p2;
wire   [10:0] p_shl9_fu_429_p3;
wire   [10:0] p_shl_fu_436_p3;
wire   [3:0] shl_ln1_fu_449_p3;
wire   [10:0] sub_ln115_1_fu_443_p2;
wire   [10:0] zext_ln115_3_fu_456_p1;
wire   [10:0] add_ln115_1_fu_460_p2;
wire   [3:0] or_ln116_fu_471_p2;
wire   [10:0] zext_ln116_fu_477_p1;
wire   [10:0] add_ln116_fu_481_p2;
wire   [0:0] icmp_ln1035_fu_492_p2;
wire   [0:0] icmp_ln1035_1_fu_506_p2;
wire   [0:0] icmp_ln1035_2_fu_518_p2;
wire   [7:0] tmp_288_fu_532_p3;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_done_reg = 1'b0;
end

cnn_accel_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln111_fu_237_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            c_fu_96 <= select_ln111_1_fu_278_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            c_fu_96 <= 5'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln111_fu_237_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten28_fu_92 <= select_ln112_2_fu_396_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten28_fu_92 <= 6'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln111_fu_237_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten42_fu_100 <= add_ln111_1_fu_243_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten42_fu_100 <= 10'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln111_fu_237_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            x_fu_84 <= add_ln113_fu_384_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            x_fu_84 <= 3'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln111_fu_237_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            y_1_fu_88 <= select_ln112_1_fu_350_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            y_1_fu_88 <= 3'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln111_fu_237_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln115_reg_590 <= add_ln115_fu_362_p2;
        select_ln112_reg_585 <= select_ln112_fu_342_p3;
        tmp_reg_601 <= select_ln112_fu_342_p3[32'd2];
        trunc_ln115_reg_595 <= trunc_ln115_fu_368_p1;
        trunc_ln122_reg_606 <= trunc_ln122_fu_380_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        tmp_reg_601_pp0_iter1_reg <= tmp_reg_601;
        trunc_ln115_reg_595_pp0_iter1_reg <= trunc_ln115_reg_595;
        trunc_ln122_reg_606_pp0_iter1_reg <= trunc_ln122_reg_606;
        zext_ln115_4_reg_610[10 : 1] <= zext_ln115_4_fu_466_p1[10 : 1];
        zext_ln116_1_reg_620[10 : 1] <= zext_ln116_1_fu_487_p1[10 : 1];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        m_V_1_reg_640 <= m_V_1_fu_498_p3;
        m_V_3_reg_652 <= m_V_3_fu_511_p3;
        tmp_reg_601_pp0_iter2_reg <= tmp_reg_601_pp0_iter1_reg;
        tmp_reg_601_pp0_iter3_reg <= tmp_reg_601_pp0_iter2_reg;
        trunc_ln115_reg_595_pp0_iter2_reg <= trunc_ln115_reg_595_pp0_iter1_reg;
        trunc_ln115_reg_595_pp0_iter3_reg <= trunc_ln115_reg_595_pp0_iter2_reg;
        trunc_ln122_reg_606_pp0_iter2_reg <= trunc_ln122_reg_606_pp0_iter1_reg;
        trunc_ln122_reg_606_pp0_iter3_reg <= trunc_ln122_reg_606_pp0_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        v3_V_reg_646 <= cnn_accel_ap_int_8_const_ap_uint_4_conv2_2_q0;
    end
end

always @ (*) begin
    if (((icmp_ln111_fu_237_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_c_load = 5'd0;
    end else begin
        ap_sig_allocacmp_c_load = c_fu_96;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten28_load = 6'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten28_load = indvar_flatten28_fu_92;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten42_load = 10'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten42_load = indvar_flatten42_fu_100;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_x_load = 3'd0;
    end else begin
        ap_sig_allocacmp_x_load = x_fu_84;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_y_1_load = 3'd0;
    end else begin
        ap_sig_allocacmp_y_1_load = y_1_fu_88;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        cnn_accel_ap_int_8_const_ap_uint_4_conv2_2_ce0 = 1'b1;
    end else begin
        cnn_accel_ap_int_8_const_ap_uint_4_conv2_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        cnn_accel_ap_int_8_const_ap_uint_4_conv2_2_ce1 = 1'b1;
    end else begin
        cnn_accel_ap_int_8_const_ap_uint_4_conv2_2_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        cnn_accel_ap_int_8_const_ap_uint_4_conv2_ce0 = 1'b1;
    end else begin
        cnn_accel_ap_int_8_const_ap_uint_4_conv2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        cnn_accel_ap_int_8_const_ap_uint_4_conv2_ce1 = 1'b1;
    end else begin
        cnn_accel_ap_int_8_const_ap_uint_4_conv2_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        cnn_accel_ap_int_8_const_ap_uint_4_pool2_3_ce0 = 1'b1;
    end else begin
        cnn_accel_ap_int_8_const_ap_uint_4_pool2_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (trunc_ln122_reg_606_pp0_iter3_reg == 2'd1))) begin
        cnn_accel_ap_int_8_const_ap_uint_4_pool2_3_we0 = 1'b1;
    end else begin
        cnn_accel_ap_int_8_const_ap_uint_4_pool2_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        cnn_accel_ap_int_8_const_ap_uint_4_pool2_4_ce0 = 1'b1;
    end else begin
        cnn_accel_ap_int_8_const_ap_uint_4_pool2_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (trunc_ln122_reg_606_pp0_iter3_reg == 2'd2))) begin
        cnn_accel_ap_int_8_const_ap_uint_4_pool2_4_we0 = 1'b1;
    end else begin
        cnn_accel_ap_int_8_const_ap_uint_4_pool2_4_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        cnn_accel_ap_int_8_const_ap_uint_4_pool2_5_ce0 = 1'b1;
    end else begin
        cnn_accel_ap_int_8_const_ap_uint_4_pool2_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (trunc_ln122_reg_606_pp0_iter3_reg == 2'd3))) begin
        cnn_accel_ap_int_8_const_ap_uint_4_pool2_5_we0 = 1'b1;
    end else begin
        cnn_accel_ap_int_8_const_ap_uint_4_pool2_5_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        cnn_accel_ap_int_8_const_ap_uint_4_pool2_ce0 = 1'b1;
    end else begin
        cnn_accel_ap_int_8_const_ap_uint_4_pool2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (trunc_ln122_reg_606_pp0_iter3_reg == 2'd0))) begin
        cnn_accel_ap_int_8_const_ap_uint_4_pool2_we0 = 1'b1;
    end else begin
        cnn_accel_ap_int_8_const_ap_uint_4_pool2_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln111_1_fu_243_p2 = (ap_sig_allocacmp_indvar_flatten42_load + 10'd1);

assign add_ln111_fu_258_p2 = (ap_sig_allocacmp_c_load + 5'd1);

assign add_ln112_1_fu_390_p2 = (ap_sig_allocacmp_indvar_flatten28_load + 6'd1);

assign add_ln112_fu_330_p2 = (select_ln111_fu_270_p3 + 3'd1);

assign add_ln113_fu_384_p2 = (select_ln112_fu_342_p3 + 3'd1);

assign add_ln115_1_fu_460_p2 = (sub_ln115_1_fu_443_p2 + zext_ln115_3_fu_456_p1);

assign add_ln115_fu_362_p2 = ($signed(sext_ln112_fu_308_p1) + $signed(zext_ln115_2_fu_358_p1));

assign add_ln116_fu_481_p2 = (sub_ln115_1_fu_443_p2 + zext_ln116_fu_477_p1);

assign and_ln111_fu_324_p2 = (xor_ln111_fu_312_p2 & icmp_ln113_fu_318_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign cnn_accel_ap_int_8_const_ap_uint_4_conv2_2_address0 = zext_ln116_1_reg_620;

assign cnn_accel_ap_int_8_const_ap_uint_4_conv2_2_address1 = zext_ln115_4_reg_610;

assign cnn_accel_ap_int_8_const_ap_uint_4_conv2_address0 = zext_ln116_1_fu_487_p1;

assign cnn_accel_ap_int_8_const_ap_uint_4_conv2_address1 = zext_ln115_4_fu_466_p1;

assign cnn_accel_ap_int_8_const_ap_uint_4_pool2_3_address0 = zext_ln122_fu_538_p1;

assign cnn_accel_ap_int_8_const_ap_uint_4_pool2_3_d0 = m_V_4_fu_522_p3;

assign cnn_accel_ap_int_8_const_ap_uint_4_pool2_4_address0 = zext_ln122_fu_538_p1;

assign cnn_accel_ap_int_8_const_ap_uint_4_pool2_4_d0 = m_V_4_fu_522_p3;

assign cnn_accel_ap_int_8_const_ap_uint_4_pool2_5_address0 = zext_ln122_fu_538_p1;

assign cnn_accel_ap_int_8_const_ap_uint_4_pool2_5_d0 = m_V_4_fu_522_p3;

assign cnn_accel_ap_int_8_const_ap_uint_4_pool2_address0 = zext_ln122_fu_538_p1;

assign cnn_accel_ap_int_8_const_ap_uint_4_pool2_d0 = m_V_4_fu_522_p3;

assign icmp_ln1035_1_fu_506_p2 = (($signed(cnn_accel_ap_int_8_const_ap_uint_4_conv2_2_q1) > $signed(m_V_1_reg_640)) ? 1'b1 : 1'b0);

assign icmp_ln1035_2_fu_518_p2 = (($signed(v3_V_reg_646) > $signed(m_V_3_reg_652)) ? 1'b1 : 1'b0);

assign icmp_ln1035_fu_492_p2 = (($signed(cnn_accel_ap_int_8_const_ap_uint_4_conv2_q0) > $signed(cnn_accel_ap_int_8_const_ap_uint_4_conv2_q1)) ? 1'b1 : 1'b0);

assign icmp_ln111_fu_237_p2 = ((ap_sig_allocacmp_indvar_flatten42_load == 10'd784) ? 1'b1 : 1'b0);

assign icmp_ln112_fu_264_p2 = ((ap_sig_allocacmp_indvar_flatten28_load == 6'd49) ? 1'b1 : 1'b0);

assign icmp_ln113_fu_318_p2 = ((ap_sig_allocacmp_x_load == 3'd7) ? 1'b1 : 1'b0);

assign m_V_1_fu_498_p3 = ((icmp_ln1035_fu_492_p2[0:0] == 1'b1) ? cnn_accel_ap_int_8_const_ap_uint_4_conv2_q0 : cnn_accel_ap_int_8_const_ap_uint_4_conv2_q1);

assign m_V_3_fu_511_p3 = ((icmp_ln1035_1_fu_506_p2[0:0] == 1'b1) ? cnn_accel_ap_int_8_const_ap_uint_4_conv2_2_q1 : m_V_1_reg_640);

assign m_V_4_fu_522_p3 = ((icmp_ln1035_2_fu_518_p2[0:0] == 1'b1) ? v3_V_reg_646 : m_V_3_reg_652);

assign or_ln112_fu_336_p2 = (icmp_ln112_fu_264_p2 | and_ln111_fu_324_p2);

assign or_ln116_fu_471_p2 = (shl_ln1_fu_449_p3 | 4'd1);

assign p_shl9_fu_429_p3 = {{trunc_ln115_reg_595}, {4'd0}};

assign p_shl_fu_436_p3 = {{add_ln115_reg_590}, {1'd0}};

assign select_ln111_1_fu_278_p3 = ((icmp_ln112_fu_264_p2[0:0] == 1'b1) ? add_ln111_fu_258_p2 : ap_sig_allocacmp_c_load);

assign select_ln111_fu_270_p3 = ((icmp_ln112_fu_264_p2[0:0] == 1'b1) ? 3'd0 : ap_sig_allocacmp_y_1_load);

assign select_ln112_1_fu_350_p3 = ((and_ln111_fu_324_p2[0:0] == 1'b1) ? add_ln112_fu_330_p2 : select_ln111_fu_270_p3);

assign select_ln112_2_fu_396_p3 = ((icmp_ln112_fu_264_p2[0:0] == 1'b1) ? 6'd1 : add_ln112_1_fu_390_p2);

assign select_ln112_fu_342_p3 = ((or_ln112_fu_336_p2[0:0] == 1'b1) ? 3'd0 : ap_sig_allocacmp_x_load);

assign sext_ln112_fu_308_p1 = $signed(sub_ln115_fu_302_p2);

assign shl_ln1_fu_449_p3 = {{select_ln112_reg_585}, {1'd0}};

assign sub_ln115_1_fu_443_p2 = (p_shl9_fu_429_p3 - p_shl_fu_436_p3);

assign sub_ln115_fu_302_p2 = (zext_ln115_1_fu_298_p1 - zext_ln115_fu_286_p1);

assign tmp_288_fu_532_p3 = {{trunc_ln115_reg_595_pp0_iter3_reg}, {tmp_reg_601_pp0_iter3_reg}};

assign tmp_s_fu_290_p3 = {{select_ln111_1_fu_278_p3}, {3'd0}};

assign trunc_ln115_fu_368_p1 = add_ln115_fu_362_p2[6:0];

assign trunc_ln122_fu_380_p1 = select_ln112_fu_342_p3[1:0];

assign xor_ln111_fu_312_p2 = (icmp_ln112_fu_264_p2 ^ 1'd1);

assign zext_ln115_1_fu_298_p1 = tmp_s_fu_290_p3;

assign zext_ln115_2_fu_358_p1 = select_ln112_1_fu_350_p3;

assign zext_ln115_3_fu_456_p1 = shl_ln1_fu_449_p3;

assign zext_ln115_4_fu_466_p1 = add_ln115_1_fu_460_p2;

assign zext_ln115_fu_286_p1 = select_ln111_1_fu_278_p3;

assign zext_ln116_1_fu_487_p1 = add_ln116_fu_481_p2;

assign zext_ln116_fu_477_p1 = or_ln116_fu_471_p2;

assign zext_ln122_fu_538_p1 = tmp_288_fu_532_p3;

always @ (posedge ap_clk) begin
    zext_ln115_4_reg_610[0] <= 1'b0;
    zext_ln115_4_reg_610[63:11] <= 53'b00000000000000000000000000000000000000000000000000000;
    zext_ln116_1_reg_620[0] <= 1'b1;
    zext_ln116_1_reg_620[63:11] <= 53'b00000000000000000000000000000000000000000000000000000;
end

endmodule //cnn_accel_cnn_accel_Pipeline_pool2_loop_VITIS_LOOP_112_1_VITIS_LOOP_113_2
