// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module cnn_accel_fc1_layer_Pipeline_VITIS_LOOP_139_1_VITIS_LOOP_140_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        sext_ln138,
        phi_mul,
        acc_V_2_out,
        acc_V_2_out_ap_vld,
        cnn_accel_ap_int_8_const_ap_uint_4_pool2_address0,
        cnn_accel_ap_int_8_const_ap_uint_4_pool2_ce0,
        cnn_accel_ap_int_8_const_ap_uint_4_pool2_q0,
        cnn_accel_ap_int_8_const_ap_uint_4_pool2_address1,
        cnn_accel_ap_int_8_const_ap_uint_4_pool2_ce1,
        cnn_accel_ap_int_8_const_ap_uint_4_pool2_q1,
        cnn_accel_ap_int_8_const_ap_uint_4_pool2_3_address0,
        cnn_accel_ap_int_8_const_ap_uint_4_pool2_3_ce0,
        cnn_accel_ap_int_8_const_ap_uint_4_pool2_3_q0,
        cnn_accel_ap_int_8_const_ap_uint_4_pool2_3_address1,
        cnn_accel_ap_int_8_const_ap_uint_4_pool2_3_ce1,
        cnn_accel_ap_int_8_const_ap_uint_4_pool2_3_q1,
        cnn_accel_ap_int_8_const_ap_uint_4_pool2_4_address0,
        cnn_accel_ap_int_8_const_ap_uint_4_pool2_4_ce0,
        cnn_accel_ap_int_8_const_ap_uint_4_pool2_4_q0,
        cnn_accel_ap_int_8_const_ap_uint_4_pool2_4_address1,
        cnn_accel_ap_int_8_const_ap_uint_4_pool2_4_ce1,
        cnn_accel_ap_int_8_const_ap_uint_4_pool2_4_q1,
        cnn_accel_ap_int_8_const_ap_uint_4_pool2_5_address0,
        cnn_accel_ap_int_8_const_ap_uint_4_pool2_5_ce0,
        cnn_accel_ap_int_8_const_ap_uint_4_pool2_5_q0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [8:0] sext_ln138;
input  [12:0] phi_mul;
output  [24:0] acc_V_2_out;
output   acc_V_2_out_ap_vld;
output  [7:0] cnn_accel_ap_int_8_const_ap_uint_4_pool2_address0;
output   cnn_accel_ap_int_8_const_ap_uint_4_pool2_ce0;
input  [7:0] cnn_accel_ap_int_8_const_ap_uint_4_pool2_q0;
output  [7:0] cnn_accel_ap_int_8_const_ap_uint_4_pool2_address1;
output   cnn_accel_ap_int_8_const_ap_uint_4_pool2_ce1;
input  [7:0] cnn_accel_ap_int_8_const_ap_uint_4_pool2_q1;
output  [7:0] cnn_accel_ap_int_8_const_ap_uint_4_pool2_3_address0;
output   cnn_accel_ap_int_8_const_ap_uint_4_pool2_3_ce0;
input  [7:0] cnn_accel_ap_int_8_const_ap_uint_4_pool2_3_q0;
output  [7:0] cnn_accel_ap_int_8_const_ap_uint_4_pool2_3_address1;
output   cnn_accel_ap_int_8_const_ap_uint_4_pool2_3_ce1;
input  [7:0] cnn_accel_ap_int_8_const_ap_uint_4_pool2_3_q1;
output  [7:0] cnn_accel_ap_int_8_const_ap_uint_4_pool2_4_address0;
output   cnn_accel_ap_int_8_const_ap_uint_4_pool2_4_ce0;
input  [7:0] cnn_accel_ap_int_8_const_ap_uint_4_pool2_4_q0;
output  [7:0] cnn_accel_ap_int_8_const_ap_uint_4_pool2_4_address1;
output   cnn_accel_ap_int_8_const_ap_uint_4_pool2_4_ce1;
input  [7:0] cnn_accel_ap_int_8_const_ap_uint_4_pool2_4_q1;
output  [7:0] cnn_accel_ap_int_8_const_ap_uint_4_pool2_5_address0;
output   cnn_accel_ap_int_8_const_ap_uint_4_pool2_5_ce0;
input  [7:0] cnn_accel_ap_int_8_const_ap_uint_4_pool2_5_q0;

reg ap_idle;
reg acc_V_2_out_ap_vld;
reg cnn_accel_ap_int_8_const_ap_uint_4_pool2_ce0;
reg cnn_accel_ap_int_8_const_ap_uint_4_pool2_ce1;
reg cnn_accel_ap_int_8_const_ap_uint_4_pool2_3_ce0;
reg cnn_accel_ap_int_8_const_ap_uint_4_pool2_3_ce1;
reg cnn_accel_ap_int_8_const_ap_uint_4_pool2_4_ce0;
reg cnn_accel_ap_int_8_const_ap_uint_4_pool2_4_ce1;
reg cnn_accel_ap_int_8_const_ap_uint_4_pool2_5_ce0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
wire    ap_block_state7_pp0_stage0_iter6;
wire    ap_block_state8_pp0_stage0_iter7;
wire    ap_block_state9_pp0_stage0_iter8;
wire    ap_block_state10_pp0_stage0_iter9;
wire    ap_block_state11_pp0_stage0_iter10;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln139_fu_590_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [12:0] p_ZL5W_FC1_0_address0;
reg    p_ZL5W_FC1_0_ce0;
wire   [7:0] p_ZL5W_FC1_0_q0;
wire   [12:0] p_ZL5W_FC1_0_address1;
reg    p_ZL5W_FC1_0_ce1;
wire   [7:0] p_ZL5W_FC1_0_q1;
wire   [12:0] p_ZL5W_FC1_0_address2;
reg    p_ZL5W_FC1_0_ce2;
wire   [7:0] p_ZL5W_FC1_0_q2;
wire   [12:0] p_ZL5W_FC1_0_address3;
reg    p_ZL5W_FC1_0_ce3;
wire   [7:0] p_ZL5W_FC1_0_q3;
wire   [12:0] p_ZL5W_FC1_0_address4;
reg    p_ZL5W_FC1_0_ce4;
wire   [7:0] p_ZL5W_FC1_0_q4;
wire   [12:0] p_ZL5W_FC1_0_address5;
reg    p_ZL5W_FC1_0_ce5;
wire   [7:0] p_ZL5W_FC1_0_q5;
wire   [12:0] p_ZL5W_FC1_0_address6;
reg    p_ZL5W_FC1_0_ce6;
wire   [7:0] p_ZL5W_FC1_0_q6;
wire   [12:0] p_ZL5W_FC1_1_address0;
reg    p_ZL5W_FC1_1_ce0;
wire   [7:0] p_ZL5W_FC1_1_q0;
wire   [12:0] p_ZL5W_FC1_1_address1;
reg    p_ZL5W_FC1_1_ce1;
wire   [7:0] p_ZL5W_FC1_1_q1;
wire   [12:0] p_ZL5W_FC1_1_address2;
reg    p_ZL5W_FC1_1_ce2;
wire   [7:0] p_ZL5W_FC1_1_q2;
wire   [12:0] p_ZL5W_FC1_1_address3;
reg    p_ZL5W_FC1_1_ce3;
wire   [7:0] p_ZL5W_FC1_1_q3;
wire   [12:0] p_ZL5W_FC1_1_address4;
reg    p_ZL5W_FC1_1_ce4;
wire   [7:0] p_ZL5W_FC1_1_q4;
wire   [12:0] p_ZL5W_FC1_1_address5;
reg    p_ZL5W_FC1_1_ce5;
wire   [7:0] p_ZL5W_FC1_1_q5;
wire   [12:0] p_ZL5W_FC1_1_address6;
reg    p_ZL5W_FC1_1_ce6;
wire   [7:0] p_ZL5W_FC1_1_q6;
wire   [12:0] p_ZL5W_FC1_2_address0;
reg    p_ZL5W_FC1_2_ce0;
wire   [7:0] p_ZL5W_FC1_2_q0;
wire   [12:0] p_ZL5W_FC1_2_address1;
reg    p_ZL5W_FC1_2_ce1;
wire   [7:0] p_ZL5W_FC1_2_q1;
wire   [12:0] p_ZL5W_FC1_2_address2;
reg    p_ZL5W_FC1_2_ce2;
wire   [7:0] p_ZL5W_FC1_2_q2;
wire   [12:0] p_ZL5W_FC1_2_address3;
reg    p_ZL5W_FC1_2_ce3;
wire   [7:0] p_ZL5W_FC1_2_q3;
wire   [12:0] p_ZL5W_FC1_2_address4;
reg    p_ZL5W_FC1_2_ce4;
wire   [7:0] p_ZL5W_FC1_2_q4;
wire   [12:0] p_ZL5W_FC1_2_address5;
reg    p_ZL5W_FC1_2_ce5;
wire   [7:0] p_ZL5W_FC1_2_q5;
wire   [12:0] p_ZL5W_FC1_2_address6;
reg    p_ZL5W_FC1_2_ce6;
wire   [7:0] p_ZL5W_FC1_2_q6;
wire   [12:0] p_ZL5W_FC1_3_address0;
reg    p_ZL5W_FC1_3_ce0;
wire   [7:0] p_ZL5W_FC1_3_q0;
wire   [12:0] p_ZL5W_FC1_3_address1;
reg    p_ZL5W_FC1_3_ce1;
wire   [7:0] p_ZL5W_FC1_3_q1;
wire   [12:0] p_ZL5W_FC1_3_address2;
reg    p_ZL5W_FC1_3_ce2;
wire   [7:0] p_ZL5W_FC1_3_q2;
wire   [12:0] p_ZL5W_FC1_3_address3;
reg    p_ZL5W_FC1_3_ce3;
wire   [7:0] p_ZL5W_FC1_3_q3;
wire   [12:0] p_ZL5W_FC1_3_address4;
reg    p_ZL5W_FC1_3_ce4;
wire   [7:0] p_ZL5W_FC1_3_q4;
wire   [12:0] p_ZL5W_FC1_3_address5;
reg    p_ZL5W_FC1_3_ce5;
wire   [7:0] p_ZL5W_FC1_3_q5;
wire   [12:0] p_ZL5W_FC1_3_address6;
reg    p_ZL5W_FC1_3_ce6;
wire   [7:0] p_ZL5W_FC1_3_q6;
wire    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln139_reg_1256;
reg   [0:0] icmp_ln139_reg_1256_pp0_iter1_reg;
reg   [0:0] icmp_ln139_reg_1256_pp0_iter2_reg;
reg   [0:0] icmp_ln139_reg_1256_pp0_iter3_reg;
reg   [0:0] icmp_ln139_reg_1256_pp0_iter4_reg;
reg   [0:0] icmp_ln139_reg_1256_pp0_iter5_reg;
reg   [0:0] icmp_ln139_reg_1256_pp0_iter6_reg;
reg   [0:0] icmp_ln139_reg_1256_pp0_iter7_reg;
reg   [0:0] icmp_ln139_reg_1256_pp0_iter8_reg;
wire   [2:0] select_ln139_fu_620_p3;
reg   [2:0] select_ln139_reg_1260;
reg   [2:0] select_ln139_reg_1260_pp0_iter1_reg;
wire   [6:0] add_ln145_fu_666_p2;
reg   [6:0] add_ln145_reg_1271;
reg   [6:0] add_ln145_reg_1271_pp0_iter1_reg;
reg   [6:0] add_ln145_reg_1271_pp0_iter2_reg;
reg   [6:0] add_ln145_reg_1271_pp0_iter3_reg;
wire  signed [10:0] grp_fu_1170_p3;
reg  signed [10:0] empty_49_reg_1281;
reg  signed [10:0] empty_49_reg_1281_pp0_iter4_reg;
reg  signed [10:0] empty_49_reg_1281_pp0_iter5_reg;
reg  signed [8:0] trunc_ln186_1_reg_1289;
reg  signed [8:0] trunc_ln186_1_reg_1289_pp0_iter4_reg;
wire   [1:0] trunc_ln186_fu_729_p1;
reg   [1:0] trunc_ln186_reg_1295;
reg   [1:0] trunc_ln186_reg_1295_pp0_iter4_reg;
reg   [1:0] trunc_ln186_reg_1295_pp0_iter5_reg;
reg   [1:0] trunc_ln186_reg_1295_pp0_iter6_reg;
reg   [7:0] lshr_ln186_5_reg_1306;
reg   [7:0] lshr_ln186_5_reg_1306_pp0_iter4_reg;
wire   [7:0] tmp_9_fu_748_p3;
reg   [7:0] tmp_9_reg_1311;
wire   [63:0] zext_ln145_2_fu_755_p1;
reg   [63:0] zext_ln145_2_reg_1316;
reg   [63:0] zext_ln145_2_reg_1316_pp0_iter5_reg;
wire   [63:0] zext_ln145_3_fu_797_p1;
reg   [63:0] zext_ln145_3_reg_1353;
reg  signed [7:0] cnn_accel_ap_int_8_const_ap_uint_4_pool2_load_reg_1473;
wire   [7:0] tmp_fu_914_p6;
reg  signed [7:0] tmp_reg_1478;
reg  signed [7:0] cnn_accel_ap_int_8_const_ap_uint_4_pool2_5_load_reg_1558;
wire   [7:0] tmp_3_fu_1070_p6;
reg  signed [7:0] tmp_3_reg_1563;
reg  signed [7:0] cnn_accel_ap_int_8_const_ap_uint_4_pool2_3_load_1_reg_1568;
wire   [7:0] tmp_5_fu_1083_p6;
reg  signed [7:0] tmp_5_reg_1573;
wire  signed [16:0] grp_fu_1181_p3;
wire   [17:0] add_ln840_5_fu_1143_p2;
reg   [17:0] add_ln840_5_reg_1593;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln186_2_fu_784_p1;
wire   [63:0] zext_ln186_fu_814_p1;
wire   [63:0] zext_ln186_1_fu_846_p1;
wire   [63:0] zext_ln186_4_fu_890_p1;
wire   [63:0] zext_ln186_7_fu_906_p1;
wire   [63:0] zext_ln186_3_fu_972_p1;
wire   [63:0] zext_ln186_5_fu_1025_p1;
reg   [24:0] acc_V_fu_100;
wire   [24:0] acc_V_2_fu_1155_p2;
wire  signed [24:0] sext_ln138_cast_fu_563_p1;
wire    ap_loop_init;
reg   [2:0] y_fu_104;
wire   [2:0] add_ln140_fu_672_p2;
reg   [2:0] ap_sig_allocacmp_y_load;
reg   [4:0] c_fu_108;
wire   [4:0] select_ln139_1_fu_628_p3;
reg   [4:0] ap_sig_allocacmp_c_load;
reg   [6:0] indvar_flatten_fu_112;
wire   [6:0] add_ln139_1_fu_596_p2;
reg   [6:0] ap_sig_allocacmp_indvar_flatten_load;
wire    ap_block_pp0_stage0_01001;
wire   [0:0] icmp_ln140_fu_614_p2;
wire   [4:0] add_ln139_fu_608_p2;
wire   [3:0] trunc_ln145_fu_640_p1;
wire   [6:0] tmp_7_cast_fu_644_p3;
wire   [6:0] zext_ln145_fu_636_p1;
wire   [6:0] sub_ln145_fu_652_p2;
wire   [6:0] zext_ln145_1_fu_662_p1;
wire   [5:0] p_shl_fu_696_p3;
wire   [6:0] p_shl_cast_fu_703_p1;
wire   [6:0] zext_ln140_fu_693_p1;
wire  signed [6:0] empty_48_fu_707_p2;
wire   [9:0] trunc_ln145_1_fu_717_p1;
wire   [9:0] add_ln144_4_fu_732_p2;
(* use_dsp48 = "no" *) wire   [10:0] add_ln144_1_fu_760_p2;
wire   [8:0] trunc_ln186_3_fu_765_p4;
wire  signed [12:0] sext_ln186_7_fu_775_p1;
wire   [12:0] add_ln186_3_fu_779_p2;
wire   [7:0] or_ln145_fu_792_p2;
wire  signed [12:0] sext_ln186_3_fu_806_p1;
wire   [12:0] add_ln186_1_fu_809_p2;
(* use_dsp48 = "no" *) wire   [10:0] add_ln144_fu_822_p2;
wire   [8:0] trunc_ln186_2_fu_827_p4;
wire  signed [12:0] sext_ln186_5_fu_837_p1;
wire   [12:0] add_ln186_2_fu_841_p2;
wire  signed [7:0] tmp_2_fu_858_p6;
wire  signed [9:0] sext_ln186_1_fu_803_p1;
wire   [9:0] add_ln186_fu_875_p2;
wire  signed [12:0] sext_ln186_12_fu_881_p1;
wire   [12:0] add_ln186_5_fu_885_p2;
wire   [12:0] zext_ln186_6_fu_898_p1;
wire   [12:0] add_ln186_7_fu_901_p2;
wire  signed [7:0] tmp_1_fu_931_p6;
(* use_dsp48 = "no" *) wire   [10:0] add_ln144_2_fu_948_p2;
wire   [8:0] trunc_ln186_4_fu_953_p4;
wire  signed [12:0] sext_ln186_10_fu_963_p1;
wire   [12:0] add_ln186_4_fu_967_p2;
wire  signed [7:0] tmp_4_fu_984_p6;
(* use_dsp48 = "no" *) wire   [10:0] add_ln144_3_fu_1001_p2;
wire   [8:0] trunc_ln186_5_fu_1006_p4;
wire  signed [12:0] sext_ln186_13_fu_1016_p1;
wire   [12:0] add_ln186_6_fu_1020_p2;
wire  signed [7:0] tmp_6_fu_1037_p6;
wire  signed [15:0] mul_ln840_fu_1060_p2;
wire  signed [15:0] mul_ln840_3_fu_1102_p2;
wire  signed [15:0] mul_ln840_5_fu_1118_p2;
wire  signed [16:0] grp_fu_1189_p3;
wire  signed [16:0] grp_fu_1198_p3;
wire  signed [16:0] grp_fu_1207_p3;
wire  signed [17:0] sext_ln840_8_fu_1128_p1;
wire  signed [17:0] sext_ln840_9_fu_1131_p1;
wire   [17:0] add_ln840_4_fu_1137_p2;
wire  signed [17:0] sext_ln840_10_fu_1134_p1;
wire  signed [24:0] sext_ln840_11_fu_1152_p1;
wire   [4:0] grp_fu_1170_p0;
wire   [5:0] grp_fu_1170_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire   [10:0] grp_fu_1170_p00;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_done_reg = 1'b0;
end

cnn_accel_fc1_layer_Pipeline_VITIS_LOOP_139_1_VITIS_LOOP_140_2_p_ZL5W_FC1_0_ROM_AUTO_1R #(
    .DataWidth( 8 ),
    .AddressRange( 6272 ),
    .AddressWidth( 13 ))
p_ZL5W_FC1_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL5W_FC1_0_address0),
    .ce0(p_ZL5W_FC1_0_ce0),
    .q0(p_ZL5W_FC1_0_q0),
    .address1(p_ZL5W_FC1_0_address1),
    .ce1(p_ZL5W_FC1_0_ce1),
    .q1(p_ZL5W_FC1_0_q1),
    .address2(p_ZL5W_FC1_0_address2),
    .ce2(p_ZL5W_FC1_0_ce2),
    .q2(p_ZL5W_FC1_0_q2),
    .address3(p_ZL5W_FC1_0_address3),
    .ce3(p_ZL5W_FC1_0_ce3),
    .q3(p_ZL5W_FC1_0_q3),
    .address4(p_ZL5W_FC1_0_address4),
    .ce4(p_ZL5W_FC1_0_ce4),
    .q4(p_ZL5W_FC1_0_q4),
    .address5(p_ZL5W_FC1_0_address5),
    .ce5(p_ZL5W_FC1_0_ce5),
    .q5(p_ZL5W_FC1_0_q5),
    .address6(p_ZL5W_FC1_0_address6),
    .ce6(p_ZL5W_FC1_0_ce6),
    .q6(p_ZL5W_FC1_0_q6)
);

cnn_accel_fc1_layer_Pipeline_VITIS_LOOP_139_1_VITIS_LOOP_140_2_p_ZL5W_FC1_1_ROM_AUTO_1R #(
    .DataWidth( 8 ),
    .AddressRange( 6272 ),
    .AddressWidth( 13 ))
p_ZL5W_FC1_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL5W_FC1_1_address0),
    .ce0(p_ZL5W_FC1_1_ce0),
    .q0(p_ZL5W_FC1_1_q0),
    .address1(p_ZL5W_FC1_1_address1),
    .ce1(p_ZL5W_FC1_1_ce1),
    .q1(p_ZL5W_FC1_1_q1),
    .address2(p_ZL5W_FC1_1_address2),
    .ce2(p_ZL5W_FC1_1_ce2),
    .q2(p_ZL5W_FC1_1_q2),
    .address3(p_ZL5W_FC1_1_address3),
    .ce3(p_ZL5W_FC1_1_ce3),
    .q3(p_ZL5W_FC1_1_q3),
    .address4(p_ZL5W_FC1_1_address4),
    .ce4(p_ZL5W_FC1_1_ce4),
    .q4(p_ZL5W_FC1_1_q4),
    .address5(p_ZL5W_FC1_1_address5),
    .ce5(p_ZL5W_FC1_1_ce5),
    .q5(p_ZL5W_FC1_1_q5),
    .address6(p_ZL5W_FC1_1_address6),
    .ce6(p_ZL5W_FC1_1_ce6),
    .q6(p_ZL5W_FC1_1_q6)
);

cnn_accel_fc1_layer_Pipeline_VITIS_LOOP_139_1_VITIS_LOOP_140_2_p_ZL5W_FC1_2_ROM_AUTO_1R #(
    .DataWidth( 8 ),
    .AddressRange( 6272 ),
    .AddressWidth( 13 ))
p_ZL5W_FC1_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL5W_FC1_2_address0),
    .ce0(p_ZL5W_FC1_2_ce0),
    .q0(p_ZL5W_FC1_2_q0),
    .address1(p_ZL5W_FC1_2_address1),
    .ce1(p_ZL5W_FC1_2_ce1),
    .q1(p_ZL5W_FC1_2_q1),
    .address2(p_ZL5W_FC1_2_address2),
    .ce2(p_ZL5W_FC1_2_ce2),
    .q2(p_ZL5W_FC1_2_q2),
    .address3(p_ZL5W_FC1_2_address3),
    .ce3(p_ZL5W_FC1_2_ce3),
    .q3(p_ZL5W_FC1_2_q3),
    .address4(p_ZL5W_FC1_2_address4),
    .ce4(p_ZL5W_FC1_2_ce4),
    .q4(p_ZL5W_FC1_2_q4),
    .address5(p_ZL5W_FC1_2_address5),
    .ce5(p_ZL5W_FC1_2_ce5),
    .q5(p_ZL5W_FC1_2_q5),
    .address6(p_ZL5W_FC1_2_address6),
    .ce6(p_ZL5W_FC1_2_ce6),
    .q6(p_ZL5W_FC1_2_q6)
);

cnn_accel_fc1_layer_Pipeline_VITIS_LOOP_139_1_VITIS_LOOP_140_2_p_ZL5W_FC1_3_ROM_AUTO_1R #(
    .DataWidth( 8 ),
    .AddressRange( 6272 ),
    .AddressWidth( 13 ))
p_ZL5W_FC1_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL5W_FC1_3_address0),
    .ce0(p_ZL5W_FC1_3_ce0),
    .q0(p_ZL5W_FC1_3_q0),
    .address1(p_ZL5W_FC1_3_address1),
    .ce1(p_ZL5W_FC1_3_ce1),
    .q1(p_ZL5W_FC1_3_q1),
    .address2(p_ZL5W_FC1_3_address2),
    .ce2(p_ZL5W_FC1_3_ce2),
    .q2(p_ZL5W_FC1_3_q2),
    .address3(p_ZL5W_FC1_3_address3),
    .ce3(p_ZL5W_FC1_3_ce3),
    .q3(p_ZL5W_FC1_3_q3),
    .address4(p_ZL5W_FC1_3_address4),
    .ce4(p_ZL5W_FC1_3_ce4),
    .q4(p_ZL5W_FC1_3_q4),
    .address5(p_ZL5W_FC1_3_address5),
    .ce5(p_ZL5W_FC1_3_ce5),
    .q5(p_ZL5W_FC1_3_q5),
    .address6(p_ZL5W_FC1_3_address6),
    .ce6(p_ZL5W_FC1_3_ce6),
    .q6(p_ZL5W_FC1_3_q6)
);

cnn_accel_mux_42_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
mux_42_8_1_1_U310(
    .din0(p_ZL5W_FC1_2_q6),
    .din1(p_ZL5W_FC1_3_q6),
    .din2(p_ZL5W_FC1_0_q6),
    .din3(p_ZL5W_FC1_1_q6),
    .din4(trunc_ln186_reg_1295_pp0_iter4_reg),
    .dout(tmp_2_fu_858_p6)
);

cnn_accel_mux_42_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
mux_42_8_1_1_U311(
    .din0(p_ZL5W_FC1_0_q5),
    .din1(p_ZL5W_FC1_1_q5),
    .din2(p_ZL5W_FC1_2_q5),
    .din3(p_ZL5W_FC1_3_q5),
    .din4(trunc_ln186_reg_1295_pp0_iter5_reg),
    .dout(tmp_fu_914_p6)
);

cnn_accel_mux_42_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
mux_42_8_1_1_U312(
    .din0(p_ZL5W_FC1_1_q4),
    .din1(p_ZL5W_FC1_2_q4),
    .din2(p_ZL5W_FC1_3_q4),
    .din3(p_ZL5W_FC1_0_q4),
    .din4(trunc_ln186_reg_1295_pp0_iter5_reg),
    .dout(tmp_1_fu_931_p6)
);

cnn_accel_mux_42_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
mux_42_8_1_1_U313(
    .din0(p_ZL5W_FC1_0_q3),
    .din1(p_ZL5W_FC1_1_q3),
    .din2(p_ZL5W_FC1_2_q3),
    .din3(p_ZL5W_FC1_3_q3),
    .din4(trunc_ln186_reg_1295_pp0_iter5_reg),
    .dout(tmp_4_fu_984_p6)
);

cnn_accel_mux_42_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
mux_42_8_1_1_U314(
    .din0(p_ZL5W_FC1_2_q2),
    .din1(p_ZL5W_FC1_3_q2),
    .din2(p_ZL5W_FC1_0_q2),
    .din3(p_ZL5W_FC1_1_q2),
    .din4(trunc_ln186_reg_1295_pp0_iter5_reg),
    .dout(tmp_6_fu_1037_p6)
);

cnn_accel_mul_8s_8s_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
mul_8s_8s_16_1_1_U315(
    .din0(tmp_reg_1478),
    .din1(cnn_accel_ap_int_8_const_ap_uint_4_pool2_load_reg_1473),
    .dout(mul_ln840_fu_1060_p2)
);

cnn_accel_mux_42_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
mux_42_8_1_1_U316(
    .din0(p_ZL5W_FC1_3_q1),
    .din1(p_ZL5W_FC1_0_q1),
    .din2(p_ZL5W_FC1_1_q1),
    .din3(p_ZL5W_FC1_2_q1),
    .din4(trunc_ln186_reg_1295_pp0_iter6_reg),
    .dout(tmp_3_fu_1070_p6)
);

cnn_accel_mux_42_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
mux_42_8_1_1_U317(
    .din0(p_ZL5W_FC1_1_q0),
    .din1(p_ZL5W_FC1_2_q0),
    .din2(p_ZL5W_FC1_3_q0),
    .din3(p_ZL5W_FC1_0_q0),
    .din4(trunc_ln186_reg_1295_pp0_iter6_reg),
    .dout(tmp_5_fu_1083_p6)
);

cnn_accel_mul_8s_8s_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
mul_8s_8s_16_1_1_U318(
    .din0(tmp_3_reg_1563),
    .din1(cnn_accel_ap_int_8_const_ap_uint_4_pool2_5_load_reg_1558),
    .dout(mul_ln840_3_fu_1102_p2)
);

cnn_accel_mul_8s_8s_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
mul_8s_8s_16_1_1_U319(
    .din0(tmp_5_reg_1573),
    .din1(cnn_accel_ap_int_8_const_ap_uint_4_pool2_3_load_1_reg_1568),
    .dout(mul_ln840_5_fu_1118_p2)
);

cnn_accel_mac_muladd_5ns_6ns_7s_11_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 5 ),
    .din1_WIDTH( 6 ),
    .din2_WIDTH( 7 ),
    .dout_WIDTH( 11 ))
mac_muladd_5ns_6ns_7s_11_4_1_U320(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1170_p0),
    .din1(grp_fu_1170_p1),
    .din2(empty_48_fu_707_p2),
    .ce(1'b1),
    .dout(grp_fu_1170_p3)
);

cnn_accel_mac_muladd_8s_8s_16s_17_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 17 ))
mac_muladd_8s_8s_16s_17_4_1_U321(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_2_fu_858_p6),
    .din1(cnn_accel_ap_int_8_const_ap_uint_4_pool2_4_q1),
    .din2(mul_ln840_fu_1060_p2),
    .ce(1'b1),
    .dout(grp_fu_1181_p3)
);

cnn_accel_mac_muladd_8s_8s_17s_17_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 17 ),
    .dout_WIDTH( 17 ))
mac_muladd_8s_8s_17s_17_4_1_U322(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_1_fu_931_p6),
    .din1(cnn_accel_ap_int_8_const_ap_uint_4_pool2_3_q1),
    .din2(grp_fu_1181_p3),
    .ce(1'b1),
    .dout(grp_fu_1189_p3)
);

cnn_accel_mac_muladd_8s_8s_16s_17_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 17 ))
mac_muladd_8s_8s_16s_17_4_1_U323(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_4_fu_984_p6),
    .din1(cnn_accel_ap_int_8_const_ap_uint_4_pool2_q0),
    .din2(mul_ln840_3_fu_1102_p2),
    .ce(1'b1),
    .dout(grp_fu_1198_p3)
);

cnn_accel_mac_muladd_8s_8s_16s_17_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 17 ))
mac_muladd_8s_8s_16s_17_4_1_U324(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_6_fu_1037_p6),
    .din1(cnn_accel_ap_int_8_const_ap_uint_4_pool2_4_q0),
    .din2(mul_ln840_5_fu_1118_p2),
    .ce(1'b1),
    .dout(grp_fu_1207_p3)
);

cnn_accel_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter9_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            acc_V_fu_100 <= sext_ln138_cast_fu_563_p1;
        end else if ((ap_enable_reg_pp0_iter10 == 1'b1)) begin
            acc_V_fu_100 <= acc_V_2_fu_1155_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln139_fu_590_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            c_fu_108 <= select_ln139_1_fu_628_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            c_fu_108 <= 5'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln139_fu_590_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten_fu_112 <= add_ln139_1_fu_596_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_112 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln139_fu_590_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            y_fu_104 <= add_ln140_fu_672_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            y_fu_104 <= 3'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln139_fu_590_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln145_reg_1271 <= add_ln145_fu_666_p2;
        select_ln139_reg_1260 <= select_ln139_fu_620_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln145_reg_1271_pp0_iter1_reg <= add_ln145_reg_1271;
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        icmp_ln139_reg_1256 <= icmp_ln139_fu_590_p2;
        icmp_ln139_reg_1256_pp0_iter1_reg <= icmp_ln139_reg_1256;
        select_ln139_reg_1260_pp0_iter1_reg <= select_ln139_reg_1260;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        add_ln145_reg_1271_pp0_iter2_reg <= add_ln145_reg_1271_pp0_iter1_reg;
        add_ln145_reg_1271_pp0_iter3_reg <= add_ln145_reg_1271_pp0_iter2_reg;
        add_ln840_5_reg_1593 <= add_ln840_5_fu_1143_p2;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
        cnn_accel_ap_int_8_const_ap_uint_4_pool2_5_load_reg_1558 <= cnn_accel_ap_int_8_const_ap_uint_4_pool2_5_q0;
        empty_49_reg_1281_pp0_iter4_reg <= empty_49_reg_1281;
        empty_49_reg_1281_pp0_iter5_reg <= empty_49_reg_1281_pp0_iter4_reg;
        icmp_ln139_reg_1256_pp0_iter2_reg <= icmp_ln139_reg_1256_pp0_iter1_reg;
        icmp_ln139_reg_1256_pp0_iter3_reg <= icmp_ln139_reg_1256_pp0_iter2_reg;
        icmp_ln139_reg_1256_pp0_iter4_reg <= icmp_ln139_reg_1256_pp0_iter3_reg;
        icmp_ln139_reg_1256_pp0_iter5_reg <= icmp_ln139_reg_1256_pp0_iter4_reg;
        icmp_ln139_reg_1256_pp0_iter6_reg <= icmp_ln139_reg_1256_pp0_iter5_reg;
        icmp_ln139_reg_1256_pp0_iter7_reg <= icmp_ln139_reg_1256_pp0_iter6_reg;
        icmp_ln139_reg_1256_pp0_iter8_reg <= icmp_ln139_reg_1256_pp0_iter7_reg;
        lshr_ln186_5_reg_1306 <= {{add_ln144_4_fu_732_p2[9:2]}};
        lshr_ln186_5_reg_1306_pp0_iter4_reg <= lshr_ln186_5_reg_1306;
        tmp_3_reg_1563 <= tmp_3_fu_1070_p6;
        tmp_5_reg_1573 <= tmp_5_fu_1083_p6;
        tmp_9_reg_1311[7 : 1] <= tmp_9_fu_748_p3[7 : 1];
        tmp_reg_1478 <= tmp_fu_914_p6;
        trunc_ln186_1_reg_1289 <= {{grp_fu_1170_p3[10:2]}};
        trunc_ln186_1_reg_1289_pp0_iter4_reg <= trunc_ln186_1_reg_1289;
        trunc_ln186_reg_1295 <= trunc_ln186_fu_729_p1;
        trunc_ln186_reg_1295_pp0_iter4_reg <= trunc_ln186_reg_1295;
        trunc_ln186_reg_1295_pp0_iter5_reg <= trunc_ln186_reg_1295_pp0_iter4_reg;
        trunc_ln186_reg_1295_pp0_iter6_reg <= trunc_ln186_reg_1295_pp0_iter5_reg;
        zext_ln145_2_reg_1316[7 : 1] <= zext_ln145_2_fu_755_p1[7 : 1];
        zext_ln145_2_reg_1316_pp0_iter5_reg[7 : 1] <= zext_ln145_2_reg_1316[7 : 1];
        zext_ln145_3_reg_1353[7 : 1] <= zext_ln145_3_fu_797_p1[7 : 1];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
        cnn_accel_ap_int_8_const_ap_uint_4_pool2_3_load_1_reg_1568 <= cnn_accel_ap_int_8_const_ap_uint_4_pool2_3_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter6 == 1'b1))) begin
        cnn_accel_ap_int_8_const_ap_uint_4_pool2_load_reg_1473 <= cnn_accel_ap_int_8_const_ap_uint_4_pool2_q1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        empty_49_reg_1281 <= grp_fu_1170_p3;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln139_reg_1256_pp0_iter8_reg == 1'd1))) begin
        acc_V_2_out_ap_vld = 1'b1;
    end else begin
        acc_V_2_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln139_fu_590_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter9_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_c_load = 5'd0;
    end else begin
        ap_sig_allocacmp_c_load = c_fu_108;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten_load = 7'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten_load = indvar_flatten_fu_112;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_y_load = 3'd0;
    end else begin
        ap_sig_allocacmp_y_load = y_fu_104;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter6 == 1'b1))) begin
        cnn_accel_ap_int_8_const_ap_uint_4_pool2_3_ce0 = 1'b1;
    end else begin
        cnn_accel_ap_int_8_const_ap_uint_4_pool2_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        cnn_accel_ap_int_8_const_ap_uint_4_pool2_3_ce1 = 1'b1;
    end else begin
        cnn_accel_ap_int_8_const_ap_uint_4_pool2_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        cnn_accel_ap_int_8_const_ap_uint_4_pool2_4_ce0 = 1'b1;
    end else begin
        cnn_accel_ap_int_8_const_ap_uint_4_pool2_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        cnn_accel_ap_int_8_const_ap_uint_4_pool2_4_ce1 = 1'b1;
    end else begin
        cnn_accel_ap_int_8_const_ap_uint_4_pool2_4_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter6 == 1'b1))) begin
        cnn_accel_ap_int_8_const_ap_uint_4_pool2_5_ce0 = 1'b1;
    end else begin
        cnn_accel_ap_int_8_const_ap_uint_4_pool2_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        cnn_accel_ap_int_8_const_ap_uint_4_pool2_ce0 = 1'b1;
    end else begin
        cnn_accel_ap_int_8_const_ap_uint_4_pool2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        cnn_accel_ap_int_8_const_ap_uint_4_pool2_ce1 = 1'b1;
    end else begin
        cnn_accel_ap_int_8_const_ap_uint_4_pool2_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter6 == 1'b1))) begin
        p_ZL5W_FC1_0_ce0 = 1'b1;
    end else begin
        p_ZL5W_FC1_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter6 == 1'b1))) begin
        p_ZL5W_FC1_0_ce1 = 1'b1;
    end else begin
        p_ZL5W_FC1_0_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        p_ZL5W_FC1_0_ce2 = 1'b1;
    end else begin
        p_ZL5W_FC1_0_ce2 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        p_ZL5W_FC1_0_ce3 = 1'b1;
    end else begin
        p_ZL5W_FC1_0_ce3 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        p_ZL5W_FC1_0_ce4 = 1'b1;
    end else begin
        p_ZL5W_FC1_0_ce4 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        p_ZL5W_FC1_0_ce5 = 1'b1;
    end else begin
        p_ZL5W_FC1_0_ce5 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        p_ZL5W_FC1_0_ce6 = 1'b1;
    end else begin
        p_ZL5W_FC1_0_ce6 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter6 == 1'b1))) begin
        p_ZL5W_FC1_1_ce0 = 1'b1;
    end else begin
        p_ZL5W_FC1_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter6 == 1'b1))) begin
        p_ZL5W_FC1_1_ce1 = 1'b1;
    end else begin
        p_ZL5W_FC1_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        p_ZL5W_FC1_1_ce2 = 1'b1;
    end else begin
        p_ZL5W_FC1_1_ce2 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        p_ZL5W_FC1_1_ce3 = 1'b1;
    end else begin
        p_ZL5W_FC1_1_ce3 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        p_ZL5W_FC1_1_ce4 = 1'b1;
    end else begin
        p_ZL5W_FC1_1_ce4 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        p_ZL5W_FC1_1_ce5 = 1'b1;
    end else begin
        p_ZL5W_FC1_1_ce5 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        p_ZL5W_FC1_1_ce6 = 1'b1;
    end else begin
        p_ZL5W_FC1_1_ce6 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter6 == 1'b1))) begin
        p_ZL5W_FC1_2_ce0 = 1'b1;
    end else begin
        p_ZL5W_FC1_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter6 == 1'b1))) begin
        p_ZL5W_FC1_2_ce1 = 1'b1;
    end else begin
        p_ZL5W_FC1_2_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        p_ZL5W_FC1_2_ce2 = 1'b1;
    end else begin
        p_ZL5W_FC1_2_ce2 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        p_ZL5W_FC1_2_ce3 = 1'b1;
    end else begin
        p_ZL5W_FC1_2_ce3 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        p_ZL5W_FC1_2_ce4 = 1'b1;
    end else begin
        p_ZL5W_FC1_2_ce4 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        p_ZL5W_FC1_2_ce5 = 1'b1;
    end else begin
        p_ZL5W_FC1_2_ce5 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        p_ZL5W_FC1_2_ce6 = 1'b1;
    end else begin
        p_ZL5W_FC1_2_ce6 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter6 == 1'b1))) begin
        p_ZL5W_FC1_3_ce0 = 1'b1;
    end else begin
        p_ZL5W_FC1_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter6 == 1'b1))) begin
        p_ZL5W_FC1_3_ce1 = 1'b1;
    end else begin
        p_ZL5W_FC1_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        p_ZL5W_FC1_3_ce2 = 1'b1;
    end else begin
        p_ZL5W_FC1_3_ce2 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        p_ZL5W_FC1_3_ce3 = 1'b1;
    end else begin
        p_ZL5W_FC1_3_ce3 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        p_ZL5W_FC1_3_ce4 = 1'b1;
    end else begin
        p_ZL5W_FC1_3_ce4 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        p_ZL5W_FC1_3_ce5 = 1'b1;
    end else begin
        p_ZL5W_FC1_3_ce5 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        p_ZL5W_FC1_3_ce6 = 1'b1;
    end else begin
        p_ZL5W_FC1_3_ce6 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign acc_V_2_fu_1155_p2 = ($signed(acc_V_fu_100) + $signed(sext_ln840_11_fu_1152_p1));

assign acc_V_2_out = acc_V_fu_100;

assign add_ln139_1_fu_596_p2 = (ap_sig_allocacmp_indvar_flatten_load + 7'd1);

assign add_ln139_fu_608_p2 = (ap_sig_allocacmp_c_load + 5'd1);

assign add_ln140_fu_672_p2 = (select_ln139_fu_620_p3 + 3'd1);

assign add_ln144_1_fu_760_p2 = ($signed(empty_49_reg_1281) + $signed(11'd2));

assign add_ln144_2_fu_948_p2 = ($signed(empty_49_reg_1281_pp0_iter5_reg) + $signed(11'd3));

assign add_ln144_3_fu_1001_p2 = ($signed(empty_49_reg_1281_pp0_iter5_reg) + $signed(11'd5));

assign add_ln144_4_fu_732_p2 = (trunc_ln145_1_fu_717_p1 + 10'd6);

assign add_ln144_fu_822_p2 = ($signed(empty_49_reg_1281_pp0_iter4_reg) + $signed(11'd1));

assign add_ln145_fu_666_p2 = (sub_ln145_fu_652_p2 + zext_ln145_1_fu_662_p1);

assign add_ln186_1_fu_809_p2 = ($signed(phi_mul) + $signed(sext_ln186_3_fu_806_p1));

assign add_ln186_2_fu_841_p2 = ($signed(phi_mul) + $signed(sext_ln186_5_fu_837_p1));

assign add_ln186_3_fu_779_p2 = ($signed(phi_mul) + $signed(sext_ln186_7_fu_775_p1));

assign add_ln186_4_fu_967_p2 = ($signed(phi_mul) + $signed(sext_ln186_10_fu_963_p1));

assign add_ln186_5_fu_885_p2 = ($signed(phi_mul) + $signed(sext_ln186_12_fu_881_p1));

assign add_ln186_6_fu_1020_p2 = ($signed(phi_mul) + $signed(sext_ln186_13_fu_1016_p1));

assign add_ln186_7_fu_901_p2 = (phi_mul + zext_ln186_6_fu_898_p1);

assign add_ln186_fu_875_p2 = ($signed(sext_ln186_1_fu_803_p1) + $signed(10'd1));

assign add_ln840_4_fu_1137_p2 = ($signed(sext_ln840_8_fu_1128_p1) + $signed(sext_ln840_9_fu_1131_p1));

assign add_ln840_5_fu_1143_p2 = ($signed(add_ln840_4_fu_1137_p2) + $signed(sext_ln840_10_fu_1134_p1));

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state10_pp0_stage0_iter9 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage0_iter10 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter8 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign cnn_accel_ap_int_8_const_ap_uint_4_pool2_3_address0 = zext_ln145_3_reg_1353;

assign cnn_accel_ap_int_8_const_ap_uint_4_pool2_3_address1 = zext_ln145_2_reg_1316;

assign cnn_accel_ap_int_8_const_ap_uint_4_pool2_4_address0 = zext_ln145_3_fu_797_p1;

assign cnn_accel_ap_int_8_const_ap_uint_4_pool2_4_address1 = zext_ln145_2_fu_755_p1;

assign cnn_accel_ap_int_8_const_ap_uint_4_pool2_5_address0 = zext_ln145_2_reg_1316_pp0_iter5_reg;

assign cnn_accel_ap_int_8_const_ap_uint_4_pool2_address0 = zext_ln145_3_fu_797_p1;

assign cnn_accel_ap_int_8_const_ap_uint_4_pool2_address1 = zext_ln145_2_reg_1316;

assign empty_48_fu_707_p2 = (p_shl_cast_fu_703_p1 - zext_ln140_fu_693_p1);

assign grp_fu_1170_p0 = grp_fu_1170_p00;

assign grp_fu_1170_p00 = select_ln139_1_fu_628_p3;

assign grp_fu_1170_p1 = 11'd49;

assign icmp_ln139_fu_590_p2 = ((ap_sig_allocacmp_indvar_flatten_load == 7'd112) ? 1'b1 : 1'b0);

assign icmp_ln140_fu_614_p2 = ((ap_sig_allocacmp_y_load == 3'd7) ? 1'b1 : 1'b0);

assign or_ln145_fu_792_p2 = (tmp_9_reg_1311 | 8'd1);

assign p_ZL5W_FC1_0_address0 = zext_ln186_5_fu_1025_p1;

assign p_ZL5W_FC1_0_address1 = zext_ln186_3_fu_972_p1;

assign p_ZL5W_FC1_0_address2 = zext_ln186_7_fu_906_p1;

assign p_ZL5W_FC1_0_address3 = zext_ln186_4_fu_890_p1;

assign p_ZL5W_FC1_0_address4 = zext_ln186_1_fu_846_p1;

assign p_ZL5W_FC1_0_address5 = zext_ln186_fu_814_p1;

assign p_ZL5W_FC1_0_address6 = zext_ln186_2_fu_784_p1;

assign p_ZL5W_FC1_1_address0 = zext_ln186_5_fu_1025_p1;

assign p_ZL5W_FC1_1_address1 = zext_ln186_3_fu_972_p1;

assign p_ZL5W_FC1_1_address2 = zext_ln186_7_fu_906_p1;

assign p_ZL5W_FC1_1_address3 = zext_ln186_4_fu_890_p1;

assign p_ZL5W_FC1_1_address4 = zext_ln186_1_fu_846_p1;

assign p_ZL5W_FC1_1_address5 = zext_ln186_fu_814_p1;

assign p_ZL5W_FC1_1_address6 = zext_ln186_2_fu_784_p1;

assign p_ZL5W_FC1_2_address0 = zext_ln186_5_fu_1025_p1;

assign p_ZL5W_FC1_2_address1 = zext_ln186_3_fu_972_p1;

assign p_ZL5W_FC1_2_address2 = zext_ln186_7_fu_906_p1;

assign p_ZL5W_FC1_2_address3 = zext_ln186_4_fu_890_p1;

assign p_ZL5W_FC1_2_address4 = zext_ln186_1_fu_846_p1;

assign p_ZL5W_FC1_2_address5 = zext_ln186_fu_814_p1;

assign p_ZL5W_FC1_2_address6 = zext_ln186_2_fu_784_p1;

assign p_ZL5W_FC1_3_address0 = zext_ln186_5_fu_1025_p1;

assign p_ZL5W_FC1_3_address1 = zext_ln186_3_fu_972_p1;

assign p_ZL5W_FC1_3_address2 = zext_ln186_7_fu_906_p1;

assign p_ZL5W_FC1_3_address3 = zext_ln186_4_fu_890_p1;

assign p_ZL5W_FC1_3_address4 = zext_ln186_1_fu_846_p1;

assign p_ZL5W_FC1_3_address5 = zext_ln186_fu_814_p1;

assign p_ZL5W_FC1_3_address6 = zext_ln186_2_fu_784_p1;

assign p_shl_cast_fu_703_p1 = p_shl_fu_696_p3;

assign p_shl_fu_696_p3 = {{select_ln139_reg_1260_pp0_iter1_reg}, {3'd0}};

assign select_ln139_1_fu_628_p3 = ((icmp_ln140_fu_614_p2[0:0] == 1'b1) ? add_ln139_fu_608_p2 : ap_sig_allocacmp_c_load);

assign select_ln139_fu_620_p3 = ((icmp_ln140_fu_614_p2[0:0] == 1'b1) ? 3'd0 : ap_sig_allocacmp_y_load);

assign sext_ln138_cast_fu_563_p1 = $signed(sext_ln138);

assign sext_ln186_10_fu_963_p1 = $signed(trunc_ln186_4_fu_953_p4);

assign sext_ln186_12_fu_881_p1 = $signed(add_ln186_fu_875_p2);

assign sext_ln186_13_fu_1016_p1 = $signed(trunc_ln186_5_fu_1006_p4);

assign sext_ln186_1_fu_803_p1 = trunc_ln186_1_reg_1289_pp0_iter4_reg;

assign sext_ln186_3_fu_806_p1 = trunc_ln186_1_reg_1289_pp0_iter4_reg;

assign sext_ln186_5_fu_837_p1 = $signed(trunc_ln186_2_fu_827_p4);

assign sext_ln186_7_fu_775_p1 = $signed(trunc_ln186_3_fu_765_p4);

assign sext_ln840_10_fu_1134_p1 = grp_fu_1207_p3;

assign sext_ln840_11_fu_1152_p1 = $signed(add_ln840_5_reg_1593);

assign sext_ln840_8_fu_1128_p1 = grp_fu_1189_p3;

assign sext_ln840_9_fu_1131_p1 = grp_fu_1198_p3;

assign sub_ln145_fu_652_p2 = (tmp_7_cast_fu_644_p3 - zext_ln145_fu_636_p1);

assign tmp_7_cast_fu_644_p3 = {{trunc_ln145_fu_640_p1}, {3'd0}};

assign tmp_9_fu_748_p3 = {{add_ln145_reg_1271_pp0_iter3_reg}, {1'd0}};

assign trunc_ln145_1_fu_717_p1 = grp_fu_1170_p3[9:0];

assign trunc_ln145_fu_640_p1 = select_ln139_1_fu_628_p3[3:0];

assign trunc_ln186_2_fu_827_p4 = {{add_ln144_fu_822_p2[10:2]}};

assign trunc_ln186_3_fu_765_p4 = {{add_ln144_1_fu_760_p2[10:2]}};

assign trunc_ln186_4_fu_953_p4 = {{add_ln144_2_fu_948_p2[10:2]}};

assign trunc_ln186_5_fu_1006_p4 = {{add_ln144_3_fu_1001_p2[10:2]}};

assign trunc_ln186_fu_729_p1 = grp_fu_1170_p3[1:0];

assign zext_ln140_fu_693_p1 = select_ln139_reg_1260_pp0_iter1_reg;

assign zext_ln145_1_fu_662_p1 = select_ln139_fu_620_p3;

assign zext_ln145_2_fu_755_p1 = tmp_9_fu_748_p3;

assign zext_ln145_3_fu_797_p1 = or_ln145_fu_792_p2;

assign zext_ln145_fu_636_p1 = select_ln139_1_fu_628_p3;

assign zext_ln186_1_fu_846_p1 = add_ln186_2_fu_841_p2;

assign zext_ln186_2_fu_784_p1 = add_ln186_3_fu_779_p2;

assign zext_ln186_3_fu_972_p1 = add_ln186_4_fu_967_p2;

assign zext_ln186_4_fu_890_p1 = add_ln186_5_fu_885_p2;

assign zext_ln186_5_fu_1025_p1 = add_ln186_6_fu_1020_p2;

assign zext_ln186_6_fu_898_p1 = lshr_ln186_5_reg_1306_pp0_iter4_reg;

assign zext_ln186_7_fu_906_p1 = add_ln186_7_fu_901_p2;

assign zext_ln186_fu_814_p1 = add_ln186_1_fu_809_p2;

always @ (posedge ap_clk) begin
    tmp_9_reg_1311[0] <= 1'b0;
    zext_ln145_2_reg_1316[0] <= 1'b0;
    zext_ln145_2_reg_1316[63:8] <= 56'b00000000000000000000000000000000000000000000000000000000;
    zext_ln145_2_reg_1316_pp0_iter5_reg[0] <= 1'b0;
    zext_ln145_2_reg_1316_pp0_iter5_reg[63:8] <= 56'b00000000000000000000000000000000000000000000000000000000;
    zext_ln145_3_reg_1353[0] <= 1'b1;
    zext_ln145_3_reg_1353[63:8] <= 56'b00000000000000000000000000000000000000000000000000000000;
end

endmodule //cnn_accel_fc1_layer_Pipeline_VITIS_LOOP_139_1_VITIS_LOOP_140_2
